### ISSUE TITLE
ccu hat Port 90

### ISSUE THREAD

**Issue by arto5754** [ioBroker/ioBroker.hm-rega#100]
**Is your feature request related to a problem? Please describe.**
homematic (ccu) with e.g. port 90 not reachable from hm-rega, only with port 80. Possible to configure this?

**Additional context**

**Comment by arto5754** [comment]
ccu ist mit Port 90 konfiguriert und im Browser erreichbar. Iobroker Instanz hm-rpc.0 ist verbunden (grün) aber hm-rega.0 kann die Homematic (ccu) nicht erreichen (gelb). Mit CCU Port 80 möglich.Besteht eineMöglichkeit dieses zu konfigurieren?

**Comment by foxriver76** [comment]
You can do so, just edit the system.adapter.hm-rega.<instance-Id> Object there you find the homeaticPort configured to 8181 just change it. Until now it wasn’t necessary to make it configurable in frontend

**Comment by flecka87** [comment]
Hello

sorry that i reopen this case. But i have the same issue,

I have chenged the Port to 8085. Everything works finde but ioBroker instance hm-rega won't start because they got no Connection.

Could you told me wehere i must change this Port?
In the Webinterface or directly in any script?

Thanks.

**Comment by foxriver76** [comment]
This should help: https://github.com/ioBroker/ioBroker.hm-rega#my-ccu-webinterface-has-a-different-port-than-the-standard-httphttps-protocols-thus-no-connection-is-established-how-can-i-configure-the-adapter-to-use-a-custom-port-for-the-webinterface

**Comment by flecka87** [comment]
Hi,

thank you now. It works perfect.

Only the button you see below forward me to the wrong website:

![grafik](https://user-images.githubusercontent.com/81882842/113612914-bd280a00-9650-11eb-8b3e-d2bda8bacff1.png)


Do you have a tip to change this configuration,too? If there is only a complicated way there is no problem.

Thank you a lot.

**Comment by foxriver76** [comment]
Please try 3.0.18 the webif protocol as well as the port hasn't been respected on this button until now.
