### ISSUE TITLE
Errors und Warnings seit Update auf V 2.6.10

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.hm-rega#102]
**Describe the bug**
Seit dem heutigen Update auf die aktuelle Version 2.6.10 gibt es zahlreiche Errors/Warnings im Log die ich nicht nachvollziehen kann. An der CCU2 wurden keine Veränderungen an Einstellungen vorgenommen.

**To Reproduce**
Nach Update und Neustart des Pasrpberry erscheinen ständig Meldungen im Log. 

**Expected behavior**

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

hm-rega.0 | 2020-06-11 13:43:11.199 | error | (766) CCU 192.168.1.10 unreachable
-- | -- | -- | --
hm-rega.0 | 2020-06-11 13:43:11.198 | error | (766) post request error: socket hang up
hm-rega.0 | 2020-06-11 13:43:11.195 | warn | !# Dieses Script gibt die Werte aller Systemvariablen als J" timed out
hm-rega.0 | 2020-06-11 13:43:11.195 | warn | !#
hm-rega.0 | 2020-06-11 13:43:11.195 | warn | (766) "!# polling.fn 1.2

hm-rega.0 | 2020-06-11 15:14:06.705 | info | (1657) got state values
-- | -- | -- | --
hm-rega.0 | 2020-06-11 15:14:05.256 | info | (1657) request state values
hm-rega.0 | 2020-06-11 15:14:05.239 | info | (1657) added/updated 1 objects
hm-rega.0 | 2020-06-11 15:14:04.281 | info | (1657) deleted 0 variables
hm-rega.0 | 2020-06-11 15:14:04.280 | info | (1657) added/updated 48 variables
hm-rega.0 | 2020-06-11 15:14:03.892 | info | (1657) got 48 variables
hm-rega.0 | 2020-06-11 15:14:03.375 | info | (1657) update rooms to enum.rooms
hm-rega.0 | 2020-06-11 15:14:03.271 | info | (1657) update functions to enum.functions
hm-rega.0 | 2020-06-11 15:14:03.214 | info | (1657) time difference local-ccu 0s
hm-rega.0 | 2020-06-11 15:14:03.173 | info | (1657) ReGaHSS 192.168.1.10 up
hm-rega.0 | 2020-06-11 15:13:32.776 | error | (1657) CCU 192.168.1.10 unreachable
hm-rega.0 | 2020-06-11 15:13:32.774 | error | (1657) post request error: socket hang up
hm-rega.0 | 2020-06-11 15:13:32.772 | warn | !# Dieses Script gibt die Werte aller Systemvariablen als J" timed out
hm-rega.0 | 2020-06-11 15:13:32.772 | warn | !#
hm-rega.0 | 2020-06-11 15:13:32.772 | warn | (1657) "!# polling.fn 1.2

**Versions:**
Node.js: v12.18.0
NPM: 6.14.4
js-controller 3.1.5
HomeMatic ReGaHSS 2.6.10
HomeMatic RPC 1.14.8
CCU model: CCU2
CCU firmware: 2.51.6

**Additional context**

**Comment by foxriver76** [comment]
Ccu braucht mehr als 15 Sekunden um zu antworten daher läuft der request in einen Timeout. Evtl Netzwerkprobleme oder CCU überlastet. Man kann maximal die Zeit für das Timeout höher stellen.

**Comment by FabianHM** [comment]
Hi Moritz,
danke für die schnelle Antwort.
Meinst Du den "Wiederverbindungs-Intervall(sek)" ? Der steht seit ewig auf 30 sec. ohne Probleme.

Grüße
Fabian

**Comment by foxriver76** [comment]
Ne müsste ich im Code ändern. Mache später mal eine neue Version mit erhöhtem Timeout. Dachte eigentlich dass 15 Sek reichen sollten. Aber original ccu nicht so leistungsstark + viele Sysvars macht Evtl Probleme .. wenn es dass nicht ist muss es am Netzwerk liegen.

**Comment by FabianHM** [comment]
Was mir nebenbei auch auch aufgefallen ist, dass der Trigger Adapters "hm-rpc.0.BidCoS-RF.50.PRESS_SHORT" auch nicht mehr wirklich funktioniert.. Kann das evtl. damit zusamen hängen?

**Comment by foxriver76** [comment]
Jop wenn Rega nicht rund läuft, läuft der Trigger auch nicht.

**Comment by FabianHM** [comment]
Ich habe nun aeinmal manuell uter Objekte alles gelöscht, um die Menge an alten nicht mehr vorhandenen VAiablen zu reduzieren.
Hier noch ein aktuells Log mit neuerlichen Meldungen, vielleicht erklärt das ja noch mehr..

hm-rega.0 | 2020-06-11 16:29:43.015 | info | (2335) deleted 0 variables
-- | -- | -- | --
hm-rega.0 | 2020-06-11 16:29:43.014 | info | (2335) added/updated 45 variables
hm-rega.0 | 2020-06-11 16:29:42.667 | info | (2335) got 45 variables
hm-rega.0 | 2020-06-11 16:29:42.340 | info | (2335) hm-rpc.0.NEQ0027890.3 has been removed from room Wohnzimmer
hm-rega.0 | 2020-06-11 16:29:42.339 | info | (2335) hm-rpc.0.NEQ0027890.2 has been removed from room Wohnzimmer
hm-rega.0 | 2020-06-11 16:29:42.339 | info | (2335) hm-rpc.0.NEQ0027890.1 has been removed from room Wohnzimmer
hm-rega.0 | 2020-06-11 16:29:42.338 | info | (2335) hm-rpc.0.MEQ0214758.1 has been added to room Wohnzimmer
hm-rega.0 | 2020-06-11 16:29:42.338 | info | (2335) hm-rpc.0.KEQ0192111.1 has been added to room Wohnzimmer
hm-rega.0 | 2020-06-11 16:29:42.337 | info | (2335) hm-rpc.0.MEQ1549515.6 has been added to room Wohnzimmer
hm-rega.0 | 2020-06-11 16:29:42.324 | info | (2335) update rooms to enum.rooms
hm-rega.0 | 2020-06-11 16:29:42.205 | info | (2335) update functions to enum.functions
hm-rega.0 | 2020-06-11 16:29:42.133 | info | (2335) time difference local-ccu 0s
hm-rega.0 | 2020-06-11 16:29:42.084 | info | (2335) ReGaHSS 192.168.1.10 up
hm-rega.0 | 2020-06-11 16:29:41.785 | info | (2335) subscribe .hm-rpc.0.BidCoS-RF.50.PRESS_SHORT
hm-rega.0 | 2020-06-11 16:29:41.682 | info | (2335) starting. Version 2.6.10 in /opt/iobroker/node_modules/iobroker.hm-rega, node: v12.18.0, js-controller: 3.1.5
host.raspberrypi4 | 2020-06-11 16:29:39.890 | info | Do not restart adapter system.adapter.hm-rega.0 because desired by instance
host.raspberrypi4 | 2020-06-11 16:29:39.879 | error | instance system.adapter.hm-rega.0 terminated by request of the instance  itself and will not be restarted, before user restarts it.
hm-rega.0 | 2020-06-11 16:29:39.325 | warn | (2306) Got terminate signal. Checking desired PID: 2335 vs own PID 2306
hm-rega.0 | 2020-06-11 16:29:39.322 | info | (2306) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
hm-rega.0 | 2020-06-11 16:29:39.320 | info | (2306) terminating
hm-rega.0 | 2020-06-11 16:29:39.316 | warn | (2306) Got terminate signal. Checking desired PID: 0 vs own PID 2306
host.raspberrypi4 | 2020-06-11 16:29:39.307 | info | instance system.adapter.hm-rega.0 started with pid 2335
hm-rega.0 | 2020-06-11 16:26:11.125 | info | (2306) got state values
hm-rega.0 | 2020-06-11 16:26:10.007 | info | (2306) request state values

**Comment by foxriver76** [comment]
Habe das Timeout jetzt mal erhöht, war sowieso nicht wichtig, dass es so niedrig war, es sollte nur allgemein existieren, was früher nicht der Fall war. Die CCU hat nun bis zu 90 Sekunden Zeit ein Skript abzuarbeiten + zu beantworten. Bitte mal probieren ob es damit behoben ist. Ansonsten müssen wir das Skript mal so auf deiner CCU ausführen und schauen ob er echt so ewig braucht ;-)

**Comment by FabianHM** [comment]
> 
> 
> Habe das Timeout jetzt mal erhöht, war sowieso nicht wichtig, dass es so niedrig war, es sollte nur allgemein existieren, was früher nicht der Fall war. Die CCU hat nun bis zu 90 Sekunden Zeit ein Skript abzuarbeiten + zu beantworten. Bitte mal probieren ob es damit behoben ist. Ansonsten müssen wir das Skript mal so auf deiner CCU ausführen und schauen ob er echt so ewig braucht ;-)

Alles klar, ich teste es später direkt.
Danke!

**Comment by FabianHM** [comment]
Ich habe zunächst manuell alle Objekte von REGA und RPC gelöscht. 
Nach anschließendem Neustart tauchen die letzten Fehlermeldungen bisher nicht mehr auf. 
Ich werde es mal beobchten.

Kannst Du mir noch sagen, wieso der Adapter Änderungen an Raum Zuordnungen meldet, kann mich nicht erinnern Zuordnungen geändert zu haben. Woher holt der Adapter diese Infos??

hm-rega.0 | 2020-06-11 18:15:58.487 | info | (1118) hm-rpc.0.NEQ0027890.3 has been removed from room Wohnzimmer
-- | -- | -- | --
hm-rega.0 | 2020-06-11 18:15:58.486 | info | (1118) hm-rpc.0.NEQ00278.2 has been removed from room Wohnzimmer
hm-rega.0 | 2020-06-11 18:15:58.486 | info | (1118) hm-rpc.0.NEQ00278.1 has been removed from room Wohnzimmer
hm-rega.0 | 2020-06-11 18:15:58.485 | info | (1118) hm-rpc.0.MEQ02147.1 has been added to room Wohnzimmer
hm-rega.0 | 2020-06-11 18:15:58.485 | info | (1118) hm-rpc.0.KEQ01921.1 has been added to room Wohnzimmer
hm-rega.0 | 2020-06-11 18:15:58.484 | info | (1118) hm-rpc.0.MEQ15495.6 has been added to room Wohnzimmer

Danke und Grüße

**Comment by FabianHM** [comment]
Diese Log Einträge werden nun im Abstand von 5 Miuten wiederholt:

hm-rega.0 | 2020-06-11 18:24:34.033 | info | (1118) got state values
-- | -- | -- | --
hm-rega.0 | 2020-06-11 18:24:19.044 | info | (1118) request state values
hm-rega.0 | 2020-06-11 18:24:19.043 | info | (1118) added/updated 1 objects
hm-rega.0 | 2020-06-11 18:24:02.802 | info | (1118) deleted 0 variables
hm-rega.0 | 2020-06-11 18:24:02.802 | info | (1118) added/updated 45 variables
hm-rega.0 | 2020-06-11 18:24:02.452 | info | (1118) got 45 variables
hm-rega.0 | 2020-06-11 18:24:02.049 | info | (1118) hm-rpc.0.NEQ0027890.3 has been removed from room Wohnzimmer
hm-rega.0 | 2020-06-11 18:24:02.048 | info | (1118) hm-rpc.0.NEQ0027890.2 has been removed from room Wohnzimmer
hm-rega.0 | 2020-06-11 18:24:02.048 | info | (1118) hm-rpc.0.NEQ0027890.1 has been removed from room Wohnzimmer
hm-rega.0 | 2020-06-11 18:24:02.047 | info | (1118) hm-rpc.0.MEQ0214758.1 has been added to room Wohnzimmer
hm-rega.0 | 2020-06-11 18:24:02.046 | info | (1118) hm-rpc.0.KEQ0192111.1 has been added to room Wohnzimmer
hm-rega.0 | 2020-06-11 18:24:02.045 | info | (1118) hm-rpc.0.MEQ1549515.6 has been added to room Wohnzimmer
hm-rega.0 | 2020-06-11 18:24:02.032 | info | (1118) update rooms to enum.rooms
hm-rega.0 | 2020-06-11 18:24:01.835 | info | (1118) update functions to enum.functions
hm-rega.0 | 2020-06-11 18:24:01.763 | info | (1118) time difference local-ccu 1s
hm-rega.0 | 2020-06-11 18:24:01.732 | info | (1118) ReGaHSS 192.168.1.10 up
hm-rega.0 | 2020-06-11 18:23:31.375 | error | (1118) CCU 192.168.1.10 unreachable
hm-rega.0 | 2020-06-11 18:23:31.374 | error | (1118) post request error: connect ETIMEDOUT 192.168.1.10:8181
hm-rega.0 | 2020-06-11 18:23:29.380 | warn | (1118) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte aller Systemvariablen als J" ignored, because still pending.

**Comment by foxriver76** [comment]
Die Aufzählungen für die Räume sind die auf der CCU existenten Räume die nach ioBroker synchronisiert werden. Du kannst mal downgarden, es schaut bei dir eher nach Netzwerkproblemen aus, der ETIMEDOUT ist z. B. unabhängig von dem neu eingeführten Timeout.

**Comment by foxriver76** [comment]
Wegen dem Enum synchronisieren ohne Änderung, habe da nochmal was gefixt. Glaube das war seit eh und je nicht 100 % korrekt implementiert.

**Comment by FabianHM** [comment]
Ich bin gerade auf der alten Version 2.6.5, dabei kommen keine Fehlermeldungen mehr.
Gehe nun schrittweise wieder hoch

**Comment by FabianHM** [comment]
> 
> 
> Wegen dem Enum synchronisieren ohne Änderung, habe da nochmal was gefixt. Glaube das war seit eh und je nicht 100 % korrekt implementiert.
Ja, habe nun im Raum Wohnzimmer einmal im ioBroker bei Aufzählungen manuell aufgeräumt. Die Gerät wrden nicht korrekt aktualisiert. Es scheint, als hinge es mit dem Unterordnern 0 und 1 im RPC Adapter zusammen....

**Comment by foxriver76** [comment]
> Wegen dem Enum synchronisieren ohne Änderung, habe da nochmal was gefixt. Glaube das war seit eh und je nicht 100 % korrekt implementiert.
> 
> Ja, habe nun im Raum Wohnzimmer einmal im ioBroker bei Aufzählungen manuell aufgeräumt. Die Geräte wurden nicht korrekt aktualisiert. Es scheint, als hinge es mit dem Unterordnern 0 und 1 im RPC Adapter zusammen....
> ![grafik](https://user-images.githubusercontent.com/26110738/84422496-619e1300-ac1d-11ea-8319-5ab7ab6a3c48.png)

Das sollte dann ab 2.6.13 nicht mehr passieren.

**Comment by foxriver76** [comment]
> Ich bin gerade auf der alten Version 2.6.5, dabei kommen keine Fehlermeldungen mehr.
> Gehe nun schrittweise wieder hoch

Naja die Frage wäre auch ob Rega nicht nur keien Fehler schmeißt sondern es auch funktioniert hat. Debug Log würde zeigen ob es damals eine Antwort auf das Systemvariablen Skript gab.

**Comment by FabianHM** [comment]
> 
> 
> > Ich bin gerade auf der alten Version 2.6.5, dabei kommen keine Fehlermeldungen mehr.
> > Gehe nun schrittweise wieder hoch
> 
> Naja die Frage wäre auch ob Rega nicht nur keien Fehler schmeißt sondern es auch funktioniert hat. Debug Log würde zeigen ob es damals eine Antwort auf das Systemvariablen Skript gab.

Ich bin jetzt au der V 2.6.13.
- Das Thema `enum.rooms` scheint erledigt
- Die Fehlermeldungen bezüglich  `post request error: connect ETIMEDOUT  `erscheinen auch nicht mehr
- Mit aktivem Debug Log sehe ich nun auch, dass brav alle 30sec. wie eingstellt der Sycnc stattfindet

hm-rega.0 | 2020-06-11 20:39:27.638 | debug | (1267) --> polling.fn
-- | -- | -- | --
hm-rega.0 | 2020-06-11 20:38:57.725 | debug | (1267) <-- {"46157":[false,"1970-01-01 01:00:00"], "50769":[false,"1970-01-01 01:00:00"], "19476":[0,"2020-06-11 18:46:27"], "42087":[true,"2020-06-11 18:46:08"], "42082":[true,"2020-06-11 18:46:0
hm-rega.0 | 2020-06-11 20:38:57.645 | debug | (1267) --> !# polling.fn 1.2 !# !# Dieses Script gibt die Werte aller Systemvariablen als J
hm-rega.0 | 2020-06-11 20:38:57.638 | debug | (1267) --> polling.fn

Aber der Trigger spricht weiterhin nicht an `hm-rpc.0.BidCoS-RF.50.PRESS_SHORT`

**Comment by foxriver76** [comment]
d.h. wenn du polling triggerst wird von hm-rega auch nicht `pollingTrigger` geloggt?

**Comment by FabianHM** [comment]
Kann es sein, das HM States von Geräten und States von Sys Variablen unterschiedlich regieren über Polling?
Beispiel: Fensterkontakt Geräte State wird anscheinend sofort übertragen, jedoch die HM SyyVar nciht.

**Comment by foxriver76** [comment]
Systemvariablen müssen gepollt werden. Änderungen an Geräten wie du sie unter hm-rpc hast, werden aktiv von der CCU mitgeteilt und erscheinen somit automatisch in Nahezu-Echtzeit

**Comment by FabianHM** [comment]
Hab

> 
> 
> d.h. wenn du polling triggerst wird von hm-rega auch nicht `pollingTrigger` geloggt?

Nein, ich sehe im Log keinen Eintrag zu  `pollingTrigger`

**Comment by FabianHM** [comment]
> 
> 
> Systemvariablen müssen gepollt werden. Änderungen an Geräten wie du sie unter hm-rpc hast, werden aktiv von der CCU mitgeteilt und erscheinen somit automatisch in Nahezu-Echtzeit

Okay, ich habe s alos korrekt verstanden. Dannn funktioniert der Polling Trigger aus SysVar bei mir def. nicht

**Comment by foxriver76** [comment]
Ja weil es genau das Skript ist, was bei dir so lange braucht

**Comment by foxriver76** [comment]
Bzw zeig doch mal das das Log vom Pollen mittels Trigger. Ist der Trigger korrekt gesetzt in den Rega Einstellungen?

**Comment by FabianHM** [comment]
> 
> 
> Ja weil es genau das Skript ist, was bei dir so lange braucht

Ich hab sogar zum Thema Netzwerk nochmals die CCU gecheckt. Alles okay. Feste IP, Firewall auf Eingeschränkt mit IP Freigabe für IoBroker. Mehr fällt mir dazu nicht ein...

**Comment by FabianHM** [comment]
> 
> 
> Bzw zeig doch mal das das Log vom Pollen mittels Trigger. Ist der Trigger korrekt gesetzt in den Rega Einstellungen?



> 
> 
> 

![grafik](https://user-images.githubusercontent.com/26110738/84431826-42f34880-ac2c-11ea-9228-a148595481af.png)

![grafik](https://user-images.githubusercontent.com/26110738/84431937-68805200-ac2c-11ea-8594-3f01b5d1c702.png)

**Comment by foxriver76** [comment]
Mach mal `hm-rpc.0` vorne weg

**Comment by FabianHM** [comment]
> 
> 
> Mach mal `hm-rpc.0` vorne weg

Jaaa, das wars 👍 
Moritz, vielen Dank!!! und einen schönen HM freien Restabend

**Comment by foxriver76** [comment]
Top, gerne. Danke ebenso.

**Comment by FabianHM** [comment]
Hab gerade mal auf das System geschaut. Nun läuft der Trigger dauerhaft und der normale Trigger wird zusätzlich alle 30sec ausgelöst...
![grafik](https://user-images.githubusercontent.com/26110738/84481237-183dda00-ac96-11ea-8583-c62a891f02a9.png)

**Comment by foxriver76** [comment]
Kann es sein, dass du ein Skript hast, was den Trigger auslöst? Das normale polling findet so statt, wie es konfiguriert ist in der Konfig, kannst es auch raus nehmen, wenn du nur über Trigger arbeitest, wenn du die aktualisierten Werte benötigst.

**Comment by FabianHM** [comment]
> 
> 
> Kann es sein, dass du ein Skript hast, was den Trigger auslöst? Das normale polling findet so statt, wie es konfiguriert ist in der Konfig, kannst es auch raus nehmen, wenn du nur über Trigger arbeitest, wenn du die aktualisierten Werte benötigst.

Ich suche nun einmal alle CCU2 Programme durch, ob evtl. versehentlich irgendwo der Trigger ständig ausgelöst wird, wobei ich da lange nichts mehr geändert habe...

**Comment by FabianHM** [comment]
Oh je, bei einem ganz alten Testscript der CCU2, was eigentlich deaktiviert war, hatte sich wohl versehentlich die Checkbox "aktiv" gesetzt.. dieses Script hatte keine Bedingung auf Änderung, so dass hier ständig ein Polling beim ioBroker ausgelöst wurde, was ja aufgrund der falschen Syntax in der Konfig nicht wirklich gezogen hat!
Dafür hat die gute, alte CCU2 aber lange unter hoher Last durchgehalten ;-)
