### ISSUE TITLE
State value to set is invalid for mqtt.0.hm.status since js controller update to 3.1.4

### ISSUE THREAD

**Issue by dilmash** [ioBroker/ioBroker.hm-rega#103]
**Describe the bug**
After installation of js controller 3.1.4 the log is flooded with messages from hm-rega: see below:

```
mqtt.0 | 2020-06-16 11:00:52.263 | warn | (14125) State value to set is invalid for mqtt.0.hm.status.AussenTempFeuchte.HUMIDITY: The state contains the forbidden properties hm!
mqtt.0 | 2020-06-16 11:00:52.259 | warn | (14125) This value will not be set in future versions. Please report this to the developer.
mqtt.0 | 2020-06-16 11:00:52.258 | warn | (14125) State value to set is invalid for mqtt.0.hm.status.AussenTempFeuchte.TEMPERATURE: The state contains the forbidden properties hm!
...
etc ..
```

**To Reproduce**
Occurred after installation of js controller 3.1.4

**Expected behavior**
Logs are not expected

**Versions:**
 - hm-rpc version: 1.14.2
 - hm-rega version: 2.5.5
 - JS-Controller version: 3.1.4
 - Node version: 10.19.0
 - Operating system: Linux
 - CCU model: raspberrymatic
 - CCU firmware: 3.51.6.20200613

**Comment by foxriver76** [comment]
This is a state of the mqtt adapter ..
