### ISSUE TITLE
Feature Request zu pollingTrigger

### ISSUE THREAD

**Issue by FabianHM** [ioBroker/ioBroker.hm-rega#105]
Hallo Max @foxriver76  
**Is your feature request related to a problem? Please describe.**
Kein Bug.

** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Ich habe gelegentlich die Meldung:

```
hm-rega.0 | 2020-08-15 10:35:07.998 | warn | (23918) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
-- | -- | -- | --
hm-rega.0 | 2020-08-15 10:35:07.871 | info | (23918) pollingTrigger
```
Wenn ich es korrekt verstanden habe, läuft das Script "!# polling.fn 1.2 !# !# gemäß der eingestellten Zeit unter "Wiederverbindungsintervall (s)" und liest alle Werte. 
Der Polling Trigger wie gewünscht beim Aulösen des Triggers "BidCoS-RF.50.PRESS_SHORT".
Soweit okay, jedoch wenn anscheinend beide Events zusammen fallen wird die o.g. Meldung im Log geworfen, korrekt?

**Describe the solution you'd like**
Um nun zu erkennen welches HM Gerät den Triger ausgelöst hat und um weniger pollingTrigger zu verwenden, wäre es klasse wenn im Log Eintrag "pollingTrigger" auch das auslösende Gerät mit angegeben werden könnte. Damit könte man schnell analysieren welches Device es gerade war. _z.B. : "pollingTrigger - Terrassentuer Wohnzimmer.STATE"_

**Describe alternatives you've considered**

**Additional context**
Evtl. ist das ja auch von allgemeinem Interesse. Danke fürs checken vorab.
Viele Grüße
Fabian

**Comment by FabianHM** [comment]
Ups Sorry, der Eintrag sollte auch zu reag.. die Hitze ;-)

**Comment by FabianHM** [comment]
Hallo Max,
zunächst einmal danke für die schnelle Umsetzung.
Ich hab mir die Version 2.6.16 natürlich direkt angeschaut.
Kannst Du bitte den HM Device Name ausgeben, der aktuelle Log Eintrag im ioBroker lautet:
`

hm-rega.0 | 2020-08-16 18:34:31.355 | info | (28856) pollingTrigger - hm-rpc.0.BidCoS-RF.50.PRESS_SHORT
-- | -- | -- | --


`
Die Stelle im Code habe ich immerhin gefunden ;-)

`                    adapter.log.info(`pollingTrigger - ${id}`);`

**Comment by foxriver76** [comment]
Hm.. naja wäre möglich aber würde ein extra Skript auslösen, oder man müsste den Objektnamen des States holen der aber theoretisch nicht immer übereinstimmt. 
Was ist denn der Grund, dafür dass du unbedingt den Namen brauchst?

**Comment by FabianHM** [comment]
Na der Grund ist "**um nun zu erkennen welches HM Gerät den Triger ausgelöst hat. Um weniger pollingTrigger Events in der alten CCU2 zu verwenden möchte ich einen Überblick haben welche Geräte wann feuern. Man könnnte so schnell analysieren welches Device es gerade war.**  z.B. : "pollingTrigger - Terrassentuer Wohnzimmer.STATE".

Dass der pollingTrigger ausglöst wurde durch  "hm-rpc.0.BidCoS-RF.50.PRESS_SHORT" wußte man ja auch vorher.
Auch für Auswertungn, z.b. über den Adapter "Log Parser" würden sich viele einfache Möglichkeiten ergeben.
Mit Bordmitteln sehe ich so keine Chance das auslösende Gerät zu identifizieren.

**Comment by foxriver76** [comment]
Ich verstehe grob was du meinst, aber wie soll das funktionieren? Der PollingTrigger wird ja nicht durch ein Gerät ausgelöst sondern durch ein Skript oder manuelles betätigen..

**Comment by FabianHM** [comment]
Mein Ziel ist es, dass die Änderung mancher HM Geräte in nahezu realtime im ioBroker ankommt, also arbeite ich bei Änderungen an Systemvariablen mit pollingTriggern in den Programmen.

Wenn also z.B. ein Polling Trigger vom Haustür Kontakt per CCU Script ausglöst wird, ändert sich dieser state des Haustür Kontakts im ioBroker. Das Script schreibt ja in diesem Fall alle Rega Variablen neu, es müsste doch also auch erkennen können über eine Schleife, welches der übertragenen Objekte/States sich gerade geändert hat, und eben dieses Device im Log aufzeigen. 

Ich hoffe mein usecase wird nun verständlicher, war vorher wohl schlecht formuliert.

**Comment by foxriver76** [comment]
> Mein Ziel ist es, dass die Änderung mancher HM Geräte in nahezu realtime im ioBroker ankommt, also arbeite ich bei Änderungen an Systemvariablen mit pollingTriggern in den Programmen.

Genau dafür ist der Trigger ja gedacht. :+1:


> Wenn also z.B. ein Polling Trigger vom Haustür Kontakt per CCU Script ausglöst wird, ändert sich dieser state des Haustür Kontakts im ioBroker. Das Script schreibt ja in diesem Fall alle Rega Variablen neu, es müsste doch also auch erkennen können über eine Schleife, welches der übertragenen Objekte/States sich gerade geändert hat, und eben dieses Device im Log aufzeigen.

Das Skript liest aber lediglich die Systemvariablen aus, nicht alle Datenpunkte. Die Antwort auf so eine Skriptausführung schaut z. B. so aus:

```
{"1235":[false,"1970-01-01 01:00:00"],
"950":[true,"1970-01-01 01:01:56"],
"3323":[3.000000,"2020-08-17 09:23:00"],
"3320":[false,"2020-07-30 11:03:39"],
"40":[0,"2020-07-30 11:03:39"],
"41":[1,"2020-08-17 09:23:33"]}
```

Lediglich die Systemvariablen als ID, mit aktuellem Wert und wann diese geändert wurden.

Um dein Use-Case zu ermöglichen, müsste man alle Datenpunkte auslesen, was aus Performance Gründen schon mal unschick wäre. Dann schaue ich, welcher DP hat sich zuletzt geändert. Und __hoffe__ dann, dass das der war der den Trigger ausgelöst hat. Gerade bei größeren Installationen wird es vorkommen, dass sich da Dinge in die Quere kommen. z. B. mein Türkontakt regelt auch die Heizung runter und löst ein pollingTrigger aus. Dann wäre es durchaus möglich, dass bis zur Überprüfung durch das Skript die letzte Änderung schon die Heizung ist und nicht der Türkontakt.

In meinen Augen gefällt mir die Logik auch nicht, da der Trigger nicht durch Geräte sondern durch Skripte ausgelöst wird.

**Comment by FabianHM** [comment]
> Um dein Use-Case zu ermöglichen, müsste man alle Datenpunkte auslesen, was aus Performance Gründen schon mal unschick wäre. Dann schaue ich, welcher DP hat sich zuletzt geändert. Und **hoffe** dann, dass das der war der den Trigger ausgelöst hat. Gerade bei größeren Installationen wird es vorkommen, dass sich da Dinge in die Quere kommen. z. B. mein Türkontakt regelt auch die Heizung runter und löst ein pollingTrigger aus. Dann wäre es durchaus möglich, dass bis zur Überprüfung durch das Skript die letzte Änderung schon die Heizung ist und nicht der Türkontakt.

Da hast Du natürlich völlig recht. Erstens bleibt es dann unklar ob der Polling Event tatsächlich  auch von der Änderung des vermeintlichen DP stammt und ausserdem wäre es aus Performance Gründen in der Tat nicht sinnig alle Datenpunkte ständig auzuslesen.

Das Thema hat jedoch bei mir gerade die Frage aufgeworfen, ob ich nun meine gesamte auf Jahre gewachsenen CCU Scripte alle umbauen muss. 

Nur kurz zum Hintergrund, vielleicht liege ich da ja auch schon ewig völlig falsch:
Zu Beginn meiner CCU Script Zeit habe ich in vielen Foren und Blogs den Hinweis beherzigt, keine Aktoren usw. direkt abzufragen  sondern deren States immer nur über Systemvriablen zu setzen.
Ich gehe daher immer den Umweg über eine Systemvariable, statt einen Aktor direkt zu schalten, wird eine Systemvariable mit dem neuen Wert gesetzt.
Beispiel:
![HM Code](https://user-images.githubusercontent.com/26110738/90377004-a14b0600-e077-11ea-91af-9f7d3f4e09c0.JPG)

Aber das sind CCU Themen und mein Porblem welchen weg ich hier gehe...die haben hier aber nichts zu suchen... 

**Hinsichtlich des Polling Triggers lass es besser wie es vorher war (Version 2.6.15), sonst haben andere evtl Probleme falls sie den pollingTriger filtern.**
