### ISSUE TITLE
Systemvariablen werden nicht mehr aktualisiert 

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/ioBroker.hm-rega#107]
Bei mir werden mit der 2.6.18 keine Systemvariablen mehr aktualisiert.
Bin zurück auf 2.6.17 und da war gleich wieder alles i.O.
Ich glaube, dass betrifft nicht nur mich

[Link zum Forumbeitrag](https://forum.iobroker.net/topic/36151/hm-rega-fehler-nach-update-auf-2-6-18-cannot-parse-answer/11)

Aktives System:
RaspberryMatic  Version 3.51.6.20200621
IoBroker im Docker
Betriebssystem - linux
Architektur - x64
Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM 11.55 GB
Node.js v12.18.3
NPM 6.14.6

**Comment by foxriver76** [comment]
Ups, ja da ist was falsch, wenn man unsichtbare vars synchronisiert
