### ISSUE TITLE
iobroker fehleinträge Objekte ab dem 10 HM-RPC Instanz  

### ISSUE THREAD

**Issue by zano-5702** [ioBroker/ioBroker.hm-rega#111]
Gute Tag Miteinander

Wenn man mehr als 10 HM-RPC Instanzen macht führt die 10 Instanz zu fehleinträge in den Objekten in der HM-RPC 1 Instanz.

Die ist ca. seit einem Jahr so, meine Aktuellen Versionen unten ersichtlich, vielleicht kann das jemand beheben.

Besten Dank für die Unterstützung.

gruss oliver

Node.js  (passierte auch bei früheren Versionen)
v10.22.1 

HM-RPC (passierte auch bei früheren Versionen)
1.14.23

ReGaHSS 2.6.20 (passierte auch bei früheren Versionen)

Admin 4.1.8 (passierte auch bei früheren Versionen)

**Comment by foxriver76** [comment]
Sollte gefixt sein mit hm-rega 2.6.21

**Comment by zano-5702** [comment]
jetzt funktioniert alles wie es sollte, besten dank

**Comment by zano-5702** [comment]
Ist der Fehler wieder drin??????
Habe nicht lange Analysiert aber sieht so aus, gleich wie vorher  RPC1.14.23 / ReGA 2.6.21

**Comment by zano-5702** [comment]
![2020-09-27 19_15_00_ccu_fehler](https://user-images.githubusercontent.com/71638545/94371309-dc6c3a80-00f5-11eb-9499-e7f84632bd8b.png)

**Comment by foxriver76** [comment]
Ne, gab seitdem keine Änderung. Upload gemacht? Und sicher, dass die States nicht mit alter Version schon angelegt wurden?

**Comment by zano-5702** [comment]
Komisch, auch nach einem reboot, objekte rpc 10 und 1 gelöscht genau das gleiche alle einträge in den objekte 10 werden in das objekt 1 geschrieben, adapter neu gestartet das gleiche..... komischerweise passiert das bei rpc 11,12,13,14,15 nicht mehr nur noch die 10 und eins scheinen verbunden zu sein......

**Comment by foxriver76** [comment]
ah.. es gibt noch ne stelle, welche ich nicht angepasst habe..

**Comment by foxriver76** [comment]
Hoffentlich jetzt mit 2.6.22 gefixt

**Comment by zano-5702** [comment]
jetzt (version 2.6.22) ist es definitiv gefixt, merci
