### ISSUE TITLE
hm-rega 2.6.19 and up crashes REGA process on CCU-2

### ISSUE THREAD

**Issue by dwm66** [ioBroker/ioBroker.hm-rega#113]
A old problem is back:
After running the adapter about 24h, the adapter causes the rega process on my old CCU-2 to crash out.
This starts with version 2.6.19. Version 2.6.17 is still running rock stable.

Moreover, this crash is not detected by the adapter.
The datapoint "hm-rega.0.info.ccuRegaUp" still shows "true", causing also my programmed Watchdog to fail.
The log shows the parts of the error page of the CCU-2 when polling Rega:

```
hm-rega.0	2020-10-23 10:04:31.068	error	(23775) "<html>\r\n<head>\r\n\t<title>HomeMatic</title>\r\n \r\n <style rel=\"stylesheet\" type=\"text/css\">\r\n \r\n .Invisible {\r\n display: none;\r\n }\r\n \r\n </style>\r\n

hm-rega.0	2020-10-23 10:04:31.068	error	(23775) <-- invalid response:
```

**To Reproduce**
1. Have a old CCU-2, quite clean, no load from programs running.
2. Install the hm-rega adapter 2.6.19 or above
3. Wait 24h

**Expected behavior**
- CCU-2 to run stable
- IF an error happens, the datapoint hm-rega.0.info.ccuRegaUp should go to "false"

**Versions:**
 - hm-rpc version: 1.14.24
 - hm-rega version: 2.6.19
 - JS-Controller version: 3.1.4
 - Node version: 10.22.0
 - Operating system: Docker buanet image 4.20, running debian 
 - CCU model: CCU-2
 - CCU firmware: 2.35.16

**Comment by foxriver76** [comment]
I will have a look at the wrong state value of ccuRegaUp, however, the only thing changed between 2.6.17 and 2.6.19 is an adjustment in the polling script https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rega/master/regascripts/polling.fn, try to execute it manually on your CCU, however I don't know why it should work for 24 hours and then stop working..

**Comment by Apollon77** [comment]
I use hm-rega with 2.6.21 without any problem ...

**Comment by dwm66** [comment]
Thank you for the quick state fix.
Installed now the new 2.6.24.

From the statements above, there has to be some issue also on the CCU2 ... not too much one can do there.
I'm now trying to remove old inactive programs and variables, and try to move to the latest firmware.

Lets see and wait a day :+1: 

TNX
Werner

**Comment by dwm66** [comment]
Ok ...
using now the 2.6.24 module, together with the 2.53.27 firmware on the CCU2.

This is now running stable since 5 days, so the issue seems to be resolved. 
Not really sure if the firmware did it or deleting about 10 old programs and variables. These have been inactive, but who knows the riddles of REGA ...

Thanks for the support - I'm closing the issue now.
