### ISSUE TITLE
Räume werden in englischer Sprache dargestellt

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.hm-rega#116]
Hallo,
wieso werden die Räume in englischer Sprache dargestellt, anstatt wie in der CCU3 definiert, in deutsch?
Oder muss ich das in der CCU3 definieren?

**Comment by foxriver76** [comment]
Mal bitte Screenshot zeigen, was konkret gemeint ist

**Comment by Schmakus** [comment]
![Uploading Bildschirmfoto 2020-12-16 um 17.04.03.png…]()

**Comment by foxriver76** [comment]
I will look into it but Id will stay in English but name should be translated. You can also change the name manually
