### ISSUE TITLE
Keine Werte mit 0 , wenn CCU neu gestartet wurde und keine Werte der Geräte vorliegen

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.hm-rega#118]
Es müsste eine Einstellung geben, welche unterbindet, dass 0 Werte übernommen werden, wenn nach einem Neustart der CCU noch keine Werte der Geräte vorliegen.
Durch die Übernahme von 0 Werten, werden alle Diagramme und History-Einträge verfälscht.

**Comment by Apollon77** [comment]
Die Frage ist ja wie der Adapter den regulären Wert 0 und den falschen Wert 0 unterscheiden soll

**Comment by Hirsch-DE** [comment]
Bei jeder Message sollte doch der RSSI-Device-Wert mitgeliefert werden, oder? Bis auf die CCU selbst sind dann immer Werte von RSSI-Device <> 0 gültige Werte. Muss natürlich noch geprüft werden, ist nur eine Idee.

**Comment by foxriver76** [comment]
Ich bin kein Fan solcher Heuristiken wenn der Fehler offensichtlich an einer anderen Stelle liegt!

**Comment by Hirsch-DE** [comment]
Das Problem ist, dass alle Werte beim Start des Moduls mittels Script "datapoints.fn" abgerufen werden. Ich habe mal zusätzlich den Timestamp des Datenpunkts mit abgefragt. Das Ergebnis war, dass er 0 ist, wenn keine aktuellen Daten vorliegen.
Mein Vorschlag, Zeile 24 von 
" if (oDP)"
in  
" if (oDP && oDP.Timestamp().ToInteger() > 0) {"
ändern. Damit werden nur aktuelle Werte abgefragt und geliefert!

**Comment by foxriver76** [comment]
Man kann das wie gesagt selbstverständlich im Adapter abhandeln, die Quelle des Problems ist es trotzallem nicht. Wenn eine Rega falsche Daten liefert, ist das nicht ok. Grundsätzlich habe ich das Gefühl, dass das ignoriert wird was ich schreibe. Wenn du es im Adapter abgehandelt wissen möchtest, kannst du gerne einen PR stellen.

**Comment by Hirsch-DE** [comment]
Sorry, wenn es so bei Dir ankommt.
Ich habe aber mal die einzelnen Schritte vom hm-rega durchgesehen und festgestellt, dass dieser bei Start das Script "datapoints.fn" ausführt, ohne die Werte auf Gültigkeit zu Prüfen, in diesem Fall ohne den Zeitstempel des letzten Wertes aus der CCU auszuwerten. Also nicht Rega ist der Verursacher, sondern das Script.
Ein PR werde ich mal anlegen.

**Comment by foxriver76** [comment]
Wenn Rega invalide Werte liefert, ist das meines Erachtens nach der Verursacher.

**Comment by Hirsch-DE** [comment]
Was soll den der Rega für Werte liefern, wenn auf der CCU mittels Script alle Datenpunte abgefragt werden und es noch keine aktuellen Werte gibt. Dann ist doch das Ergebnis 0 richtig, oder würdest Du sagen "NULL" ist besser?

**Comment by foxriver76** [comment]
Zum Beispiel, einen potentiell validen Wert zu liefern, z. B. Rollo Level 0, den man als plausibel annehmen könnte stiftet Verwirrung.
