### ISSUE TITLE
Meldung mit js-controller 3.2.12

### ISSUE THREAD

**Issue by darkman242** [ioBroker/ioBroker.hm-rega#123]
Hi, mit der aktuellen Adapter-Version 3.0.12 tritt das Hinweis mit dem js-controller 3.2.12 immernoch auf.

hm-rega.0 | 2021-01-30 13:21:47.924 | warn | (3790) State "hm-rpc.2.CUX2801001.0.STICKY_UNREACH" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
hm-rega.0 | 2021-01-30 13:21:47.880 | warn | (3790) State "hm-rpc.2.CUX2801001.0.UNREACH" has no existing object, this might lead to an error in future versions
hm-rega.0 | 2021-01-30 13:21:47.835 | warn | (3790) State "hm-rpc.2.CUX2801001.0.LOWBAT" has no existing object, this might lead to an error in future versions

**Comment by foxriver76** [comment]
Gibt es? CUX2801001 Unter hm-rpc.2 denn? Bitte hm-rpc.2 Konfig mal zeigen.

**Comment by darkman242** [comment]
hängt vlt mit dem Homematic RPC Adapter zusammen. Der startet ja aktuell mit der 1.14.32 die CUxD-Install nicht.

```
{
  "_id": "system.adapter.hm-rpc.2",
  "common": {
    "name": "hm-rpc",
    "title": "HomeMatic RPC (CUxD)",
    "version": "1.14.32",
    "authors": [
      "hobbyquaker <hq@ccu.io>",
      "Moritz Heusinger <moritz.heusinger@gmail.com>"
    ],
    "license": "MIT",
    "mode": "daemon",
    "platform": "Javascript/Node.js",
    "loglevel": "warn",
    "readme": "https://github.com/ioBroker/ioBroker.hm-rpc/blob/master/README.md",
    "icon": "homematic.png",
    "materialize": true,
    "compact": true,
    "extIcon": "https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rpc/master/admin/homematic.png",
    "keywords": [
      "homematic",
      "bidcos",
      "eq3",
      "ELV",
      "CCU",
      "CCU1",
      "CCU2",
      "rpc",
      "xmlrpc",
      "homegear",
      "binrpc",
      "CUxD",
      "FS20",
      "FHT",
      "HMS",
      "EnOcean"
    ],
    "type": "iot-systems",
    "supportStopInstance": true,
    "messagebox": true,
    "installedVersion": "1.14.32",
    "enabled": false,
    "host": "iobroker-01",
    "dependencies": [
      {
        "js-controller": ">=2.0.0"
      }
    ],
    "installedFrom": "iobroker.hm-rpc@1.14.32",
    "connectionType": "local",
    "dataSource": "push",
    "plugins": {
      "sentry": {
        "dsn": "https://1bc0c96f48e44483b283bc5fc0ca91e2@sentry.iobroker.net/10",
        "pathWhitelist": [],
        "errorBlacklist": [
          "SyntaxError"
        ]
      }
    }
  },
  "native": {
    "homematicAddress": "192.168.10.20",
    "homematicPort": "8701",
    "adapterAddress": "192.168.10.16",
    "port": "0",
    "daemon": "CUxD",
    "type": "bin",
    "forceReInit": false,
    "callbackAddress": "",
    "checkInitInterval": "180",
    "reconnectInterval": "30",
    "dontDelete": false,
    "useHttps": false,
    "username": "",
    "password": ""
  }
}
```

**Comment by foxriver76** [comment]
Das passt.
Und
> Gibt es CUX2801001 Unter hm-rpc.2 denn?

Im Endeffekt vermute ich, dass es in der Rega API die DPs gibt in der RPC nicht, vermutlich hat das Gerät ja nicht wirklich einen Unreach und Lowbat State, da rein virtuell? Und Meldung nur einmalig bei Start oder wenn die DPs geupdated werden? Lösung wird da vermutlich nur sein, vorher zu prüfen ob es das Objekt gibt, wenn da Inkonsistenzen zwischen den APIs sind.

**Comment by foxriver76** [comment]
v3.0.13 checkt das nun, interessant wäre ein Debug Log eines hm-rega Startes mit 3.0.13 um zu checken ob das alles tut.

**Comment by darkman242** [comment]
Komischerweise hat das Gerät 1 die beide Stati obwohl virtuell :-\ Die Meldung kam nur, wenn die Instanz neu gestartet wurde.
[Rega_Start_Debug_3.0.13.txt](https://github.com/ioBroker/ioBroker.hm-rega/files/5898296/Rega_Start_Debug_3.0.13.txt)

**Comment by foxriver76** [comment]
Jein, es hat die ALARM DPs die wurden nämlich von Rega angelegt, aber keine DP's ohne `ALARM`, die Rega versucht hat zu setzen.

**Comment by darkman242** [comment]
okay, wenn du es sagst. Danke
