### ISSUE TITLE
CCU not available anymore after adapter update

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.hm-rega#128]
Hi,

I just updated the HM Rega Adapter (3.0.16) and see that in my log I get messages
CCU 192.168.1.181 unreachable

If I open the URL of my CCU I get the message
Not Found

I think that has happened at the last update as well. My CCU is a Raspberry running RaspberryMatic.

Not sure how this can happen, not sure if the adapter update can DDOS the CCU.

**Comment by foxriver76** [comment]
Wenn Verbindung verloren, wird nur im Rahmen des wiederverbindungsintervalls eine Anfrage an die ccu gesendet, sollte also nicht sein, bei jeder ausgehenden Anfrage wird auch ein logging erzeugt.

Bei update passiert nichts groß anderes als ein Adapter restart. Wäre mir auch nichts bekannt und konnte ich selbst nie bei einem upgrade feststellen.
