### ISSUE TITLE
Control Mode is not sent back to iobroker if changed via raspberryMatic

### ISSUE THREAD

**Issue by ckoop** [ioBroker/ioBroker.hm-rega#129]
**Describe the bug**
Control Mode is not sent back to iobroker if changed via raspberryMatic

**Steps to reproduce the behavior**

Control Mode changed via iobroker, it is sent to raspberryMatic
Control Mode changed via raspberryMatic, it will be not sent back to iobroker
if the set point temperaure is changed via iobroker, it sent to raspberryMatic and vise versa
Control Mode changed via raspberryMatic, it will be not sent back to iobroker

**Expected behavior**
the behavior would be that the Control Mode (AUTOMATIC/MANUAL) is sent back to iobroker if changed via raspberryMatic

Screenshots
...

**System information:**

RaspberryMatic Version: RaspberryMatic 3.57.4.20210320
IOB HomeMatic RPC: 1.14.35
IOB HomeMatic ReGaHSS: 3.0.16
IOB Node.js: v12.21.0
IOB NPM: 6.14.11
IOB JS controller: 3.1.6
Used Hardware: Raspi4 4GB, Ubuntu Server
Used HomeMatic RF-Module: HmIP-RFUSB

**Comment by foxriver76** [comment]
Most likely write only dp

**Comment by ckoop** [comment]
But what does it mean? If I change the setpoint temp via rasberryMatic it is sent back to IOB but not the control mode. Where is the difference?

**Comment by foxriver76** [comment]
It depends on the datapoint, see the RAW of the object, if it's `read: false` then you won't get a status back. If `read` is true, then also check that it's not only an admin issue displaying the wrong state. If you speak German I would really recommend you to ask your question in the forum first, because here I am the only one who will answer you and my time is limited.

**Comment by ckoop** [comment]
Hi Max, thx for the hint. I found it now. The current status seems to be read back via SET_POINT_MODE. I will close it here :)

**Comment by ckoop** [comment]
Solved, read back via SET_POINT_MODE is already available
