### ISSUE TITLE
Keine Liesmich Anzeige mehr seit 3.0.17

### ISSUE THREAD

**Issue by heitec11** [ioBroker/ioBroker.hm-rega#131]
Nach dem Update auf 3.0.17 gibt es keine Möglichkeit mehr die Infos anzuzeigen.

**Comment by foxriver76** [comment]
Anhand der Beschreibung, habe ich leider keine Ahnung worum es geht.

**Comment by kaen-guruh** [comment]
In der Adapter-Ansicht kann man nicht mehr, mit einem Klick auf das Fragezeichen-Symbol, in die Readme gelangen... Das wird heitec11 wohl meinen ;) 
Eventuel hängt es damit zusammen, dass auch in der Instanz-Ansicht der "Adapter - Webseite öffnen" - Link nicht richtig funktioniert. Es wird bei mir versucht über Port 0 zu öffnen

**Comment by foxriver76** [comment]
Off-Topic: Okay, nach wie vor keine Ahnung wie ich da durch die Beschreibung hätte drauf kommen können. Was hat das mit "Lies mich" zu tun? Ist doch ein Link zu deiner CCU Weboberfläche.

Naja, zum Thema, ja es ist jetzt Port abhängig und bei einer bestehenden Instanz kann es da zu Problemen kommen. Versuch mal bitte die Instanz konfig zu öffnen, kurz was zu tippen, das wieder löschen damit der Speichern Button geht und dann neu Speichern drücken. Das sollte den Port anpassen.

**Comment by kaen-guruh** [comment]
Nach der Änderung der Konfig und Abspeichern ist der Port jetzt 80 - Danke für den Tip!

**Comment by foxriver76** [comment]
Bzgl der Readme per ?-Button ist wenn dann ein Admin Issue, dann hat admin evtl das title Attribut aus der io-Package genutzt welches vor einiger Zeit deprecated und auch aus hm-rega entfernt wurde benötigt.

**Comment by Knallochse** [comment]
Ich habe bei mir ebenfalls diese fehlerhafte Anzeige.
Es wird auch kein Adapter Name angezeigt
![32EFB025-D2AD-4B54-AB29-5A9CAC028721](https://user-images.githubusercontent.com/36857242/115137560-174ca600-a027-11eb-93e1-e6313a7144f4.jpeg)
Betroffen ist aber wohl nur der hm-rega Adapter.
Mein System:
Admin 4.2.1
JS-Controller 3.2.16
