### ISSUE TITLE
Description parse error in Easy Admin

### ISSUE THREAD

**Issue by Zentauer** [ioBroker/ioBroker.hm-rega#132]
**Describe the bug**
Easy Admin cannot parse the adapter description.

**To Reproduce**
1. Go to Easy Admin

**Screenshots & Logfiles**
[618609281227.log](https://github.com/ioBroker/ioBroker.hm-rega/files/6328027/192.168.50.55-1618609281227.log)
![Bildschirmfoto vom 2021-04-17 00-00-16](https://user-images.githubusercontent.com/35875079/115088223-ffcec980-9f0f-11eb-8844-3f5e49d66fbc.png)
![Bildschirmfoto vom 2021-04-16 23-50-06](https://user-images.githubusercontent.com/35875079/115087775-1fb1bd80-9f0f-11eb-80bf-21702e3f87b8.png)

**Versions:**
 - hm-rpc version: 1.14.35
 - hm-rega version: 3.0.16
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: linux
 - CCU model: CCU3
 - CCU firmware: 3.57.5

**Comment by foxriver76** [comment]
> Easy Admin cannot parse the adapter description

Then open up an admin issue. Thanks
