### ISSUE TITLE
Why tile in Intro-Tab can't hide anymore?

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.hm-rega#134]
System.config:
```
},
    "intro": {
      "hm-rega.0": {
        "_default": false
      },
      "roomba.0": false,
      "roomba.1": false,
      "alexa2.0": false,
      "plex.0": false,
      "hue-extended.0": false,
      "material.0": false,
      "flot.0": false,
      "simple-api.0": false,
      "nuki-extended.0": false,
      "vis.0.vis runtime": true,
      "vis.0": true,
      "system.host.iobroker-d": true,
      "tr-064.0": false,
      "bolio.0": false
    }
```
Tile is greyed out but showing.

**Comment by Apollon77** [comment]
This should have nothign to do witj adapter ... this is an admin feature

**Comment by RP70DP** [comment]
Thanks for nothing...

**Comment by Apollon77** [comment]
Ok, sorry: to be more exact: Please create this issue in Admin Project

**Comment by RP70DP** [comment]
Okay, you are the developer and i'am just a user but are you really sure that this is an Admin problem? Because the Admin don't decides wether ore not an adapter has a tile. Right? This problem exist only with the hm-rega tile. Unfortunately i am not sure since which version of hm-rega the issue exist.

**Comment by foxriver76** [comment]
Since localLink has been deprecated the adapter has changed tobte localLinks property as stated in the official docs and this provided in the schema https://github.com/ioBroker/ioBroker.js-controller/blob/02a6c829e3f8a0c09c2e4a2c8cf0251aebf2df20/schemas/io-package.json#L449

if admin does not correctly support the official property then it’s an admin issue 

> Thanks for nothing...

https://m.youtube.com/watch?v=BYq0rJS0Eig

**Comment by RP70DP** [comment]
Don't get me wrong, please! I appreciate your work a lot!
But the whole time i hear you developer praying "please open an issue", "please open an issue" and then closing an issue in a couple of minutes feels a little bit like "fu** of with your sh**".

Thanks for your work!
