### ISSUE TITLE
Adpater Info wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.hm-rega#135]
Seit der Version 3.0.17 wird im Admin - Tab Adapter beim Click auf das Fragezeichen beim HomeMatic ReGaHSS Adapter kein Fenster mehr geöffnet in dem Info, Änderungsprotokoll, etc. angezeigt werden. Dies tritt sowohl bei Admin Version 4.2.1 als auch bei Admin 5.0.7 auf. Es passiert beim Click auf das Fragezeichen schlicht gar nichts. Beim HomeMatic RPC Adapter ist hingegen alles ok. Alle Adapter sind bei mir aktuell (Beta rep.), JS-Controller 3.2.16, Betriebssystem Linux und auch Raspberry,

![image](https://user-images.githubusercontent.com/56516310/115954242-2c767880-a4f0-11eb-803d-8860fe8e286e.png)

**Comment by foxriver76** [comment]
Mit 3.0.20?

**Comment by MK-66** [comment]
@foxriver76 Das gleiche Verhalten ist auch bei 3.0.20. 
Bei 3.0.17 war im Übrigen auch der Text HomeMatic ReGaHSS bei den Adaptern leer/nicht sichtbar, dies ist aber inzwischen mit 3.0.20 wieder behoben.

**Comment by foxriver76** [comment]
Ah okay weiß woran es liegt
