### ISSUE TITLE
Update js-controllers V 3.3.1 Warnmeldungen

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.hm-rega#144]
Hallo,

nach einen Update des js-controllers auf V 3.3.1 kommen folgende Warnmeldungen:

`
`

hm-rega.0 | 2021-04-30 06:46:16.063 | warn | (9264) State value to set for "hm-rega.0.QEQ1300156.0.DUTY_CYCLE" has wrong type "string" but has to be "number"
-- | -- | -- | --

`

**Comment by foxriver76** [comment]
Danke
