### ISSUE TITLE
JS-Controller Update 3.3 warning messages

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.hm-rega#145]
hm-rega.0 | 2021-04-30 14:52:59.277 | warn | State value to set for "hm-rega.0.QEQ0688574.0.countPrograms" has wrong type "number" but has to be "string"
-- | -- | -- | --
hm-rega.0 | 2021-04-30 14:52:59.262 | warn | State value to set for "hm-rega.0.QEQ0688574.0.countSystemVariables" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:59.210 | warn | State value to set for "hm-rega.0.QEQ0688574.0.countDatapoints" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:59.197 | warn | State value to set for "hm-rega.0.QEQ0688574.0.countChannels" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:59.130 | warn | State value to set for "hm-rega.0.QEQ0688574.0.countDevices" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:59.094 | warn | State value to set for "hm-rega.0.QEQ0688574.0.DEFAULT" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 14:52:59.042 | warn | State value to set for "hm-rega.0.QEQ0688574.0.CONNECTED" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 14:52:58.971 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.countPrograms" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:58.915 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.countSystemVariables" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:58.896 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.countDatapoints" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:58.839 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.countChannels" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:58.775 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.countDevices" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 14:52:58.737 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.DEFAULT" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 14:52:58.725 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.CONNECTED" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 14:52:57.824 | warn | State value to set for "hm-rpc.1.00189BE99F3AA4.0.RSSI_DEVICE" has value "147" greater than max "127"
hm-rega.0 | 2021-04-30 14:52:57.313 | warn | State value to set for "hm-rpc.1.000857099102A0.0.RSSI_DEVICE" has value "191" greater than max "127"
hm-rega.0 | 2021-04-30 14:52:57.102 | warn | State value to set for "hm-rpc.1.0009170993339E.0.RSSI_DEVICE" has value "183" greater than max "127"

**Comment by foxriver76** [comment]
Ah da sind ja noch mehr ;-)

Danke fürs posten, mache heute o. morgen neue Version.

**Comment by foxriver76** [comment]
Should be fixed with https://github.com/ioBroker/ioBroker.hm-rega/commit/a8c0323917bcd6d6003668df0c74ed6ab5f8ea26, please try the new version.
