### ISSUE TITLE
JS-Controller 3.3 - warnings

### ISSUE THREAD

**Issue by kueppert** [ioBroker/ioBroker.hm-rega#146]
Hi fox,
ich hab noch welche :) gerade die neue Version Version 3.0.22 drauf und das ist der Output im Log:

hm-rega.0 | 2021-04-30 15:26:23.472 | warn | State value to set for "hm-rega.0.NEQ1328102.0.countPrograms" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 15:26:23.410 | warn | State value to set for "hm-rega.0.NEQ1328102.0.countSystemVariables" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 15:26:23.329 | warn | State value to set for "hm-rega.0.NEQ1328102.0.countDatapoints" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 15:26:23.278 | warn | State value to set for "hm-rega.0.NEQ1328102.0.countChannels" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 15:26:23.210 | warn | State value to set for "hm-rega.0.NEQ1328102.0.countDevices" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 15:26:23.111 | warn | State value to set for "hm-rega.0.NEQ1328102.0.DEFAULT" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 15:26:23.054 | warn | State value to set for "hm-rega.0.NEQ1328102.0.CONNECTED" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 15:26:22.885 | info | Updated all datapoints
hm-rega.0 | 2021-04-30 15:26:22.663 | warn | State value to set for "hm-rpc.0.0001D709900CCD.0.RSSI_DEVICE" has value "192" greater than max "127"
hm-rega.0 | 2021-04-30 15:26:22.430 | warn | State value to set for "hm-rpc.0.000A5A49A595CD.0.RSSI_DEVICE" has value "222" greater than max "127"
hm-rega.0 | 2021-04-30 15:26:22.340 | warn | State value to set for "hm-rpc.0.0000D7099A2F33.0.RSSI_DEVICE" has value "211" greater than max "127"
hm-rega.0 | 2021-04-30 15:26:22.246 | warn | State value to set for "hm-rpc.0.0000D709925D62.0.RSSI_DEVICE" has value "188" greater than max "127"

**Comment by foxriver76** [comment]
Müsste ich haben, mit der 3.0.23: https://github.com/ioBroker/ioBroker.hm-rega/issues/145

Nur mit RSSI Workaround muss ich nochmal genauer schauen

**Comment by MarkSau** [comment]
bin auf 3.0.23

hm-rega.0 | 2021-04-30 17:04:00.556 | warn | State value to set for "hm-rega.0.QEQ0688574.0.countDevices" has wrong type "number" but has to be "string"
-- | -- | -- | --
hm-rega.0 | 2021-04-30 17:04:00.517 | warn | State value to set for "hm-rega.0.QEQ0688574.0.DEFAULT" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 17:04:00.504 | warn | State value to set for "hm-rega.0.QEQ0688574.0.CONNECTED" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 17:04:00.292 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.countDevices" has wrong type "number" but has to be "string"
hm-rega.0 | 2021-04-30 17:04:00.197 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.DEFAULT" has wrong type "string" but has to be "number"
hm-rega.0 | 2021-04-30 17:04:00.175 | warn | State value to set for "hm-rega.0.CCU2GW0001.0.CONNECTED" has wrong type "string" but has to be "number"

**Comment by foxriver76** [comment]
Next try 3.0.24 ;-)
