### ISSUE TITLE
Fehler bei Update 3.0.24

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.hm-rega#148]
Hallo,

kann Version nicht installieren, Code 25

![Screenshot (3746)](https://user-images.githubusercontent.com/41079106/116773436-af9a5000-aa55-11eb-8d2f-5b85fbfa2046.png)

Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.1
NPM: 6.14.12
JS Controller: 3.3.4
Admin: 5.0.11
Web: 3.4.0
Socket.io: 3.1.4
Script Engine: 5.1.3
IOT: 1.8.16
VIS: 1.3.9
HM-Rega: 3.0.21
HM-RPC: 1.14.37
Jarvis: 2.2.0
Backitup: 2.1.4
Cloud: 4.0.10
ICal: 1.9.3
iQontrol: 1.8.0
fb-checkpresence: 1.1.3

**Comment by foxriver76** [comment]
Ressource busy or locked, nix mit dem adapter zu tun... vielleicht hast du ein File gerade geöffnet oder permission Probleme. Bitte Forum nutzen.
