### ISSUE TITLE
Adapterwebseite öffnen von admin aus geht nicht V3.0.24

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.hm-rega#149]
Ich habe versucht, die Adapterwebseite (CCU3-Webseite) von der Admin->Instanzen aus zu öffnen. Leider hat es nicht funktioniert.
`"localLinks": {
            "_default": "%webinterfaceProtocol%://%homematicAddress%:%webinterfacePort%"
        },`
Die Wert von %webinterfacePort% ist bei mir 0.
Wo wird dieser Wert eingestellt?

Gruß Thomas

**Comment by foxriver76** [comment]
Man muss leider mit bestehenden Installationen aufgrund der Änderung ein mal die Konfig neu speichern, oder eben manuell das Instanz-Objekt editieren. Sprich, hm-rega Konfig öffnen, was ändern und gleich wieder zurück, damit man den Speichern Button drücken kann. Evtl. werde ich da mal noch was einbauen, was dann aber leider einen Instanz-Restart erzwingen würde.
