### ISSUE TITLE
still pending warnings

### ISSUE THREAD

**Issue by aba320** [ioBroker/ioBroker.hm-rega#162]
as it was in issue #101 it is still here. see a log of 30 mins.
`

hm-rega.0 | 2021-06-17 19:40:16.529 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
-- | -- | -- | --
hm-rega.0 | 2021-06-17 19:40:11.697 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:40:11.697 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:40:11.697 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:40:11.697 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:40:11.697 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:40:11.696 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:40:11.696 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:40:10.538 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:35:14.596 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:35:14.596 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:35:14.595 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:35:12.846 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:35:12.845 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:35:10.578 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
host.raspberrypi | 2021-06-17 19:30:36.820 | info | instance system.adapter.ical.2 terminated with code 0 (NO_ERROR)
host.raspberrypi | 2021-06-17 19:30:18.696 | info | instance system.adapter.ical.2 started with pid 8793
hm-rega.0 | 2021-06-17 19:30:15.813 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:30:15.812 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:30:15.812 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:30:13.771 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:30:13.771 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:30:12.446 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:29:58.022 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:25:18.997 | warn | (736) Script "!# system.fn 0.1 !# !# Dieses Script gibt die FW-Versionsnummer und mehr systems" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:25:15.180 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:25:15.179 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:25:15.179 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:25:15.179 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:24:59.394 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:24:59.393 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:24:59.393 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:20:16.996 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:20:12.267 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:20:12.267 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:20:12.267 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:20:12.267 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:20:12.266 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:20:12.266 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:19:54.231 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:20.123 | warn | (736) Script "!# system.fn 0.1 !# !# Dieses Script gibt die FW-Versionsnummer und mehr systems" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:17.534 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:17.534 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:17.534 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:06.787 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:05.266 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:05.266 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:04.241 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:15:04.240 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:10:14.348 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:10:14.347 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:10:14.347 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:10:14.347 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:10:14.347 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:10:14.346 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:10:10.547 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:10:10.547 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:05:16.240 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:05:16.240 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:05:16.240 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:05:14.522 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:05:13.322 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:04:59.136 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:04:59.136 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
host.raspberrypi | 2021-06-17 19:00:40.632 | info | instance system.adapter.ical.2 terminated with code 0 (NO_ERROR)
hm-rega.0 | 2021-06-17 19:00:19.936 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
host.raspberrypi | 2021-06-17 19:00:19.135 | info | instance system.adapter.ical.2 started with pid 14505
hm-rega.0 | 2021-06-17 19:00:14.205 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:00:14.204 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:00:14.204 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:00:11.949 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:00:11.949 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:00:11.948 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:00:11.948 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-06-17 19:00:11.948 | warn | (736) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.

`

**Versions:**
 - hm-rpc version: 1.14.37
 - hm-rega version: 3.0.16
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: linux
 - CCU model: raspberrymatic
 - CCU firmware: 3.57.5.20210525
iobroker raspi 4b 4 GB
raspimatic Raspi3 B+

**Additional context**
not a big problem but destroys overview of the log.

**Comment by foxriver76** [comment]
Maybe very low polling interval, just says that script is not finished executing and it has been send again.

**Comment by aba320** [comment]
is 30s
![20210618 Screenshot 2021-06-18 at 10-38-19 instances - ioBroker](https://user-images.githubusercontent.com/85011830/122533059-6f048f00-d021-11eb-8ef1-a4095df07ca3.png)

**Comment by foxriver76** [comment]
Das Skript hat einen eigenes Intervall, siehe Tab "Synchronisiere"

**Comment by aba320** [comment]
sorry wusste ich nicht ist auf 2 sec

**Comment by foxriver76** [comment]
Kein Stress 😎 

Klingt sehr sportlich, stell das mal bitte hoch, insbesondere wenn die anderen Skripte zwischen rein fallen, wird er das so schnell nicht abarbeiten können. Habe da z. B. 60 Sekunden, wobei es sicher auch z. B. mit 30 oder weniger geht.

**Comment by aba320** [comment]
ok 60s folgen

**Comment by aba320** [comment]
Danke das war es! vielleicht für "Übereifrige" wie mich nen Hinweis einbauen.
