### ISSUE TITLE
Rasperrimatic werden zeitgesteuerte Programme teilweise nicht mehr ausgeführt

### ISSUE THREAD

**Issue by Kampfratte** [ioBroker/ioBroker.hm-rega#166]
Seit der Version 3.0.26 werden Zeitgesteuerte Programme nicht teilweise nicht mehr ausgeführt.
Bin nun wieder zurück auf die 3.0.25 und alles läuft wieder wie gewohnt.

Habe es gemerkt, da ein Programm alle 5 Minuten ausführen sollte und diese aber nur alle 15 bis 20 min nur ausgeführt wurden.
Programme, die alle 24h ausgeführt werden sollten, liefen teilweise garnicht.

**Comment by foxriver76** [comment]
Wie schauen die Programme denn aus wird getIdByName genutzt? @GermanBluefox hat etwas an den Channel Namen geändert soweit ich weiß sonst gab es keine Änderung

**Comment by Kampfratte** [comment]
ganz normale Programme, die dann alle 5 min. z. B. ausgeführt werden. Und nein, getIdByName wird nicht genutzt. Das ist ja das komische.

**Comment by foxriver76** [comment]
Also ich sehe keine Änderung welche etwas derartiges verursachen kann.
