### ISSUE TITLE
empty program names, these are the old versions of edited programs

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.hm-rega#167]
Hi,
since some time (~3 months) I recognise a lot of empty programs, with no name an no type, just the id.

to see:
restart rega instance
open hm-rega
you see some programs, some variables with names, but also a lot of programs without name and type

after openning the id (without name) it opens to Active and ProgramExecute now with! the name and type

The same name is also found with an id AND name AND type. From the numbers used in id I guess, that the unnamed artifacts are the id of EDITED programs.

hm-rpc:: 1.14.42
hm-rega: 3.0.26
js-controler: 3.3.14
node: v12.22.1 
raspberrymatic 3.57.5.20210525

![grafik](https://user-images.githubusercontent.com/10156426/123643855-20c36d00-d825-11eb-95de-e0e2428c6912.png)

**Comment by harvey637** [comment]
Any idea how to get rid of the old versions of edited programs?

ca
Harvey

**Comment by foxriver76** [comment]
Yes, you have to do it manually once. Unfortunately, there was a bug that only the parent object has been deleted when a program is deleted from CCU, thus the name etc is missing but the children are still there.

**Comment by harvey637** [comment]
perfect answer - worked!

maybe a line in the FAQs would help users stumbling into this - thy

cu
Harvey

**Comment by foxriver76** [comment]
Yes, thanks for reporting, we weren't aware of this problem until you have reported it. So up from 3.0.27 programs which you delete will be fully removed in ioBroker. I've also added a note: https://github.com/ioBroker/ioBroker.hm-rega#3027-2021-06-28

**Comment by harvey637** [comment]
extra five stars to you * * * * *   :-)
