### ISSUE TITLE
keine ALARM Datenpunkte angelegt

### ISSUE THREAD

**Issue by Bratwurst0815** [ioBroker/ioBroker.hm-rega#174]
Hallo,

ich habe mit einer kompletten Neuinstallation auf einer SSD begonnen (basierend auf dem piVCCU3 Image).
Leider fehlen mir aktuell alle ALARM Datenpunkte (z.B. unreach, low_bat, ...).
Installiert habe ich die aktuelle 3.0.25, in welche Richtung muss ich den Fehler suchen?

Vielen Dank!

**Comment by foxriver76** [comment]
Die DPs werdende hm-rpc Instanzen müssen in der Rega Instanz konfiguriert sein. Ansonsten packe ich mal eine neue Version ins stable da sich da kürzlich was geändert hat, da von manchen virtuellen Gruppen die dps nicht erzeugt wurden

**Comment by Bratwurst0815** [comment]
Mega, scheint zu funktionieren... vielen vielen Dank!
