### ISSUE TITLE
State value to set for "hm-rpc.1.NBO0022371.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"

### ISSUE THREAD

**Issue by pdbjjens** [ioBroker/ioBroker.hm-rega#181]
**Describe the bug**
`
<html>
<body>

hm-rega.0 | 2021-08-08 18:14:58.142 | warn | State value to set for "hm-rpc.1.NEQ1765181.1.STATE" has value "0" greater than max "-1"
-- | -- | -- | --
hm-rega.0 | 2021-08-08 18:14:53.454 | warn | State value to set for "hm-rpc.1.NBO0022371.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.406 | warn | State value to set for "hm-rpc.1.NBO0022371.1.ERROR_ALARM_TEST" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.388 | warn | State value to set for "hm-rpc.1.NBO0022383.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.325 | warn | State value to set for "hm-rpc.1.NBO0022383.1.ERROR_ALARM_TEST" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.192 | warn | State value to set for "hm-rpc.1.NBO0022393.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.160 | warn | State value to set for "hm-rpc.1.NBO0022393.1.ERROR_ALARM_TEST" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.133 | warn | State value to set for "hm-rpc.1.NBO0022399.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.078 | warn | State value to set for "hm-rpc.1.NBO0022399.1.ERROR_ALARM_TEST" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.067 | warn | State value to set for "hm-rpc.1.NBO0023478.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.060 | warn | State value to set for "hm-rpc.1.NBO0023478.1.ERROR_ALARM_TEST" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:53.043 | warn | State value to set for "hm-rpc.1.NBO0022542.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:52.993 | warn | State value to set for "hm-rpc.1.NBO0022542.1.ERROR_ALARM_TEST" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:52.947 | warn | State value to set for "hm-rpc.1.NBO0022176.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:52.941 | warn | State value to set for "hm-rpc.1.NBO0022176.1.ERROR_ALARM_TEST" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:52.922 | warn | State value to set for "hm-rpc.1.NBO0022519.1.ERROR_SMOKE_CHAMBER" has value "0" greater than max "-1"
hm-rega.0 | 2021-08-08 18:14:52.876 | warn | State value to set for "hm-rpc.1.NBO0022519.1.ERROR_ALARM_TEST" has value "0" greater than max "-1"

</body>
</html>`

**To Reproduce**
stop and restart the adapter

**Expected behavior**
no warnings should be generated

**Screenshots & Logfiles**
see above

**Versions:**
 - hm-rpc version: <1.14.43>
 - hm-rega version: <3.0.29>
 - JS-Controller version: <3.3.15>
 - Node version: <12.22.1>
 - Operating system: <linux/Raspberry OS>
 - CCU model: <CCU3>
 - CCU firmware: <3.59.6>

**Additional context**

**Comment by foxriver76** [comment]
Please delete the objects once and let them be recreated by the adapter

**Comment by pdbjjens** [comment]
@foxriver76 
Tried that for hm-rpc.1.NBO0022393. The result was that the recreated object did not have the smoke detector icon anymore and no values were generated in channel 0 and channel 1.

**Comment by foxriver76** [comment]
Thanks for the feedback if the problem occurs, please reopen, but I assume it should be fixed.
