### ISSUE TITLE
Neuere Versionen nicht mehr kompatibel mit CCU1 (FW 1.519) ?

### ISSUE THREAD

**Issue by rentner62** [ioBroker/ioBroker.hm-rega#185]
In den regascripts werden "esleif" benutzt. (z.B. in variables.fn)
Ich hab noch eine der ersten CCUs mit FW 1.519 (letzte von eq3). Die kennt leider noch kein esleif. Erst ab CCU2.
Was kann ich da  tun?

**Comment by foxriver76** [comment]
Und die FW ist aktuell? Neben der offensichtlichen Lösung neuere Hardware einzusetzen, würde eine alte Adapterversion welche noch kein elseif nutzt wohl funktionsfähig. 

CCU1 ist leider schon sehr alt und ich bin mir nicht sicher ob das der einzige break ist.

**Comment by rentner62** [comment]
FW 1.519 ist jedenfalls die letzte, die ich bei eq3 für die CCU finde. Wollte sowieso bald mal auf Raspberrymatic umsteigen.
