### ISSUE TITLE
CCU Connection not found

### ISSUE THREAD

**Issue by stschulze1972** [ioBroker/ioBroker.hm-rega#198]
**Describe the bug**
latest ioBroker + ioBroker HomeMatic ReGaHSS Adapter v3.0.31
- Adapter install goes wrong
-  no CCU-IP found
-  if CCU IP is found - not the correct

-> only one CCU is used: 192.168.0.10

**Comment by Apollon77** [comment]
@stschulze1972 Please read your issue ... and then try to think like the developer ... what would you do with this issue ... no logs in, no other details ... If I wpuld be the dev I would eimply close as "not reproducable" ... glad I'm not the dev currently.
