### ISSUE TITLE
hm-rega schreibt 100-fachen Wert in LEVEL

### ISSUE THREAD

**Issue by RK62** [ioBroker/ioBroker.hm-rega#207]
Der Adapter hm-rega schreibt scheinbar falsche Werte in den State hm-rpc.1.INT000000X.1.LEVEL:
Der Wert ist um den Faktor 100 zu hoch.

Siehe Auszug History:
![2021-10-14 20_04_40-ioBroker-ESK01](https://user-images.githubusercontent.com/39200469/137372341-61329606-1551-40a8-8655-426149ecd21e.png)

**Versions:**
 - hm-rpc version: 1.14.45
 - hm-rega version: 3.0.31
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: Docker / Image buanet
 - CCU model: CCU3
 - CCU firmware: 3.59.6

**Comment by sigi2345** [comment]
Hallo, Fehler kommt mit Version 3.0.32

https://forum.iobroker.net/topic/48543/darstellung-des-level-wertes-der-ventil%C3%B6ffnung-fehlerhaft/2?_=1634538546986

Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.7
NPM: 6.14.15
JS Controller: 3.3.18
Admin: 5.1.25
Web: 3.4.9
Socket.io: 3.1.4
Script Engine: 5.2.13
IOT: 1.8.23
VIS: 1.4.5
HM-Rega: 3.0.32
HM-RPC: 1.14.45
