### ISSUE TITLE
Log-Eintrag in der CCU2 bei jedem Instanzen start

### ISSUE THREAD

**Issue by AlGu318** [ioBroker/ioBroker.hm-rega#21]
Hallo,

ich glaube ich habe einen Bug bei mir beseitigen können.
Bei jedem Neustart des Adapters/Instanz wurde auf der CCU ein Log-Eintrag erzeugt "homematic-ccu2 local0.err ReGaHss: Error: Content-Length or Postback Param size incorrect! PostParam=&!# devices.fn 1.4^M !#^M !# Dieses Homematic-Script..."
Dann habe ich mir die "devices.fn" Datei mal angeschaut und 3 Änderungen vorgenommen:
1. Die Zeilen "string sDevId;" und "string sChnId;" unter die Zeile "Write('{');" verschoben.
2. Alle überflüssigen Zeilenumbrüche entfernt
3. Den beginn gekürzt auf "!# devices.fn 1.4" ohne die weiteren Kommentare

Falls jemand das hier liest und umbauen möchte, kann er das ja Schrittweise machen und sieht dann ggf. woran genau es lag. (Dann könnte z.B. der Kommentar, von wem das ursprüngliche Script war, drin bleiben)

Gruß AlGu

**Comment by AlGu318** [comment]
Ich habe das ganze noch mal auf einem neuen System (CCU2 + ioBroker) getestet und es liegt nur an dem "ä" in dem Kommentar bei "Geraete/Kan**ä**le" in der Datei "devices.fn". Vielleicht könnte das ja ein Entwickler ändern in "ae". Dann kommt der Fehler im CCU Log nicht mehr.

Danke und Gruß
AlGu

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.hm-rega/commit/7aaa380764807bfcd49196cc8d912e73e7a364a6
