### ISSUE TITLE
v3.0.32 holt keine _Alarm States von CCU

### ISSUE THREAD

**Issue by Quarkmax** [ioBroker/ioBroker.hm-rega#216]
Mit Version .32 werden von neu hinzugefügten Geräten keine States mit *_Alarm gezogen. Ein downgrade auf .31 behebt das Problem. Der Zustand ist bei mir reproduzierbar.

hier der Screenshot v.31
![image](https://user-images.githubusercontent.com/93822511/140607373-78978c8c-870c-444f-aa4d-b229ff457ebe.png)

hier der Screenshot v.32
![image](https://user-images.githubusercontent.com/93822511/140607403-27e9cf84-16cb-4421-bea7-5c55338344ad.png)

**Comment by foxriver76** [comment]
Wurde diesbezüglich nichts geändert

**Comment by Quarkmax** [comment]
Danke foxdriver, rega neu aufgebaut und reboot, jetzt werden die States angezeigt
