### ISSUE TITLE
Cannot parse answer for devices

### ISSUE THREAD

**Issue by hdering** [ioBroker/ioBroker.hm-rega#219]
**Describe the bug**
Ich habe heute auf der CCU einige Geräte umbenannt. Vorallem ü ä ö durch ue ae und oe ersetzt.
Irgendwann ist mir aufgefallen, dass die rega Instanz folgenden Fehler ausgibt:

`Cannot parse answer for devices: {"*NEQ0009362":{"Name":"Alle_Rauchmelder","Interface":"BidCos-RF"}, "*NEQ0009362:0":{"Name":"Alle_Rauchmelder%3A0","Interface":"BidCos-RF"}, .........`

_Ich kann den erstlichen Inhalt nicht einfügen, da dort ja alle Seriennummern ersichtlich sind._

Ich habe zunächst die alte Instanz gelöscht und eine neue Instanz erstellt. Kein Erfolg.
Danach hab ich mir das komplette JSON Objekt in Notepad++ kopiert und wollte dies mit einem JSON Viewer strukturiert anzeigen lassen, jedoch hat das Plugin ebenfalls einen Fehler angezeigt. Das JSON hat eine falsche Syntax.

Ich hab mir das JSON nochmal genau angesehen. Am Ende fehlt ein "}". Wenn ich das hinzufüge, kann zumindest Notepad++ das JSON strukturiert anzeigen.

Jetzt ist die Frage: Ist das umbenennen der Geräte das ursächliche Problem oder ist es doch etwas anderes?

**Versions:**
 - hm-rpc version: 1.14.50
 - hm-rega version: 3.0.33
 - JS-Controller version: 3.3.18
 - Node version: v12.22.7
 - Operating system: ubuntu 20.04
 - CCU model: raspberrymatic
 - CCU firmware: 3.61.5.20211113

**Comment by foxriver76** [comment]
Zeig mal das ganze JSON, ich gehe nicht davon aus, dass irgendjemand was mit deinen Seriennummern anfangen kann, ansonsten darfst du es mir auch gerne per Mail schicken. 

Interessant wäre ob alle Geräte in dem JSON sind oder ob da zwischendurch die Übertragung unterbrochen wurde und wir deshalb nur ein partielles Ergebnis bekommen.

**Comment by hdering** [comment]
moritz.heusinger@gmail.com das ist deine mailadresse?

**Comment by foxriver76** [comment]
Mal bitte das Skript unter https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rega/master/regascripts/devices.fn via Skript testen auf CCU ausführen Output auch mal schicken/zeigen, damit man sieht obs am Skript liegt oder der Übertragung.

**Comment by hdering** [comment]
Ich möchte ungern meine Liste hier reinposten. Lautet deine E-Mail wie oben geschrieben?
Ich habe das Skript ausgeführt und tatsächlich, er bricht genau an dem Eintrag ab, welcher auch bei der rega Instanz als letzter Eintrag ankommt.

**Comment by foxriver76** [comment]
Ja die Mail passt, die von vorhin habe ich erhalten.

**Comment by foxriver76** [comment]
Wenns 1 zu 1 genauso ausschaut musst du es nicht nochmal schicken, wir hatten so ein ähnliches Problem schon mal, da musste iwas auf der CCU angepasst werden. Ich suche mal was das war.

**Comment by foxriver76** [comment]
Prüfe mal bitte das analog zu dem Post https://forum.iobroker.net/topic/29724/hm-rega-sync-schlägt-mit-cannot-parse-answer-for-xxxx-fehl/9

**Comment by hdering** [comment]
Wenn ich das erste Skript vom Post ausführe, erhalte ich nur folgende Ausgabe:
`Start
itemid: 10467 | item: Alle_Rauchmelder`

**Comment by foxriver76** [comment]
Hast du seit dem mal die CCU neugestartet? Evtl. ist da nur was temporär im argen.

**Comment by hdering** [comment]
Tatsächlich nicht. Mach ich sofort.

**Comment by hdering** [comment]
Neustart hat leider nicht geholfen. Ich habe dir die Ausgabe vom zweiten Skript vom Post per Mail geschickt.
Dort werden alle Geräte ausgegeben.

**Comment by hdering** [comment]
Ich habe eine Lösung gefunden.

Ich hatte vor längerer Zeit eine Meldung erhalten, dass für cuxd ein Update zur Verfügung steht. Scheinbar hatte ich damals die falsche Version installiert (für ccu3 und nicht für raspberrymatic).
Gestern oder vorgestern hatte ich cuxd auf der ccu deinstalliert. Ich vermute, durch das falsche Update, sind die Geräte, welche von cuxd angelegt worden sind, nicht gelöscht worden. Da ist die hm-rega nämlich abgebrochen.

Ich habe zunächst die korrekte Version von cuxd installiert und wieder deinstalliert.
=> Kein Erfolg. cuxd Leiche war noch immer drin.

In der Geräteliste war noch folgendes Gerät drin:
`
...
8386"CUX2801001":"CUxD-EXEC",
"CUX2801001:0":"CUxD-EXEC%3A0",
"CUX2801001:1":"CUxD-EXEC%20Duty%20Cycle",
"CUX2801001:2":"CUxD-EXEC%3A2",
"CUX2801001:3":"CUxD-EXEC%3A3",
"CUX2801001:4":"CUxD-EXEC%3A4",
"CUX2801001:5":"CUxD-EXEC%3A5",
"CUX2801001:6":"CUxD-EXEC%3A6",
"CUX2801001:7":"CUxD-EXEC%3A7",
"CUX2801001:8":"CUxD-EXEC%3A8",
"CUX2801001:9":"CUxD-EXEC%3A9",
"CUX2801001:10":"CUxD-EXEC%3A10",
"CUX2801001:11":"CUxD-EXEC%3A11",
"CUX2801001:12":"CUxD-EXEC%3A12",
"CUX2801001:13":"CUxD-EXEC%3A13",
"CUX2801001:14":"CUxD-EXEC%3A14",
"CUX2801001:15":"CUxD-EXEC%3A15",
"CUX2801001:16":"CUxD-EXEC%3A16",
...`

Folgende Forenbeiträge haben mir dabei geholfen cuxd leichen zu entfernen:
https://homematic-forum.de/forum/viewtopic.php?f=37&t=39299&start=20#p541171

Danach habe ich versucht über folgenden Befehl das Gerät über ein Skript zu löschen. Auch das hatte nicht funktioniert:
`WriteLine (xmlrpc.DeleteDevices (interfaces.Get ("CUxD"),"SeriennumerDesZuKillendenDevice",true));`

Folgender Hinweis hat dann geholfen:
https://homematic-forum.de/forum/viewtopic.php?t=56662#p562901

Mit diesem Befehl wurde das Gerät gelöscht:
`dom.DeleteObject (8386);`

Nun funktioniert hm-rega wieder und die Geräte werden umbenannt.


Noch eine weitere Auffälligkeit. Ich habe mit einem hohen DutyCycle zu kämpfen (immer > 50%). Ich bin gerade dabei die Ursache zu finden.
Interessanterweise, seit das cuxd Gerät entfernt ist, liegt er aktuell bei 20%. Mal schauen ob das so bleibt.

**Comment by hdering** [comment]
Vielen Dank für deine Hilfe auch zu so später Stunde :).
