### ISSUE TITLE
Error: The "enum.favorites." is invalid. 

### ISSUE THREAD

**Issue by haarchri** [ioBroker/ioBroker.hm-rega#227]
**Describe the bug**
see the following message since i updates my raspberry-matic in iobroker:

```
(18289) Could not synchronize favorites of user "": Error: The "enum.favorites." is invalid. Ids are not allowed to end in "."
--
```

<br class="Apple-interchange-newline">

**To Reproduce**

**Expected behavior**

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
raspberry-matic: 3.61.7.20211218
 - hm-rpc version: iobroker: 1.14.50
 - hm-rega version: iobroker:  3.0.33
 - JS-Controller version: <js-controller-version>
 - Node version: <node-version>
 - Operating system: <os-name>
 - CCU model: <raspberrymatic/CCU/...>
 - CCU firmware: <ccu-version>

**Additional context**

**Comment by foxriver76** [comment]
Please execute https://raw.githubusercontent.com/ioBroker/ioBroker.hm-rega/master/regascripts/favorites.fn on your CCU and show the output.

**Comment by Cr4zyM1K4** [comment]
I had the same problem, fixed it for me by adding a mail address to the users in "Settings > User management" at my raspberry-matic web interface.
However this is error related to the mail address.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/151591465-3764875b-0936-419e-8c29-0991d75cb704.png)

**Comment by foxriver76** [comment]
Then it’s really an user named empty string
