### ISSUE TITLE
Channel rename auf der CCU2 schlägt sich nur teilweise im iobroker nieder

### ISSUE THREAD

**Issue by udochrist** [ioBroker/ioBroker.hm-rega#24]
Hallo,

 ich habe die verschiedenen Channels einer Komponente umbenannt damit die in Scripten einfacher identifizierbar werden. Das Gerät war dabei bereits in iobroker bekannt.

Betroffen sind die Channels 6 und 7 eines Wandthermostaten. Hier aus dem Log nach dem restart des rega adapters. Umbenennung sollte also angekommen sein:

`hm-rega.0	2017-03-05 07:33:29.140	info	renamed hm-rpc.0.LTK4443419.6 to "Gallery.Thermostat:6"`
`hm-rega.0	2017-03-05 07:33:29.136	info	renamed hm-rpc.0.LTK4443419.7 to "Gallery.Thermostat:7"`

im Tab instanzen ists jetzt aber so, dass der Datenpunkt DECISION_VALUE auf :7 noch den alten Namen hat, wohingegen die andern Datenpunkte alle umbenannt sind:

```
LTK4443419		Gallery.Thermostat	device	light.dimmer	Gallery		

0		Gallery.Thermostat:0	channel		Gallery			
1		Gallery.Thermostat.Weather	channel		Gallery, Gallery	Battery Operated, Environment		
		HUMIDITY	state	Gallery.Thermostat.Weather.HUMIDITY	state	value.humidity	Gallery, Gallery	Battery Operated, Environment	32 %	
		TEMPERATURE	state	Gallery.Thermostat.Weather.TEMPERATURE	state	value.temperature	Gallery, Gallery	Battery Operated, Environment	22.3 °C	

2		Gallery.Thermostat.Climate	channel		Gallery, Gallery	Heating		
		PARTY_START_YEAR		state	Gallery.Thermostat.Climate.PARTY_START_YEAR	state		Gallery, Gallery	Heating	0 year	
		SET_TEMPERATURE			state	Gallery.Thermostat.Climate.SET_TEMPERATURE	state	level.temperature	Gallery, Gallery	Heating	22 °C	
		WINDOW_OPEN_REPORTING	state	Gallery.Thermostat.Climate.WINDOW_OPEN_REPORTING	state		Gallery, Gallery	Heating	false	

7		Gallery.Thermostat:7	channel		Gallery			
		DECISION_VALUE			state	HM-TC-IT-WM-W-EU LTK4442319:7.DECISION_VALUE	state		Gallery		0	

```

Was mich ausserdem wundert ist dass der Datenpunkt :6 (der fensterkontakt) gar nicht erst gelistet wird... (das kann aber auch ein hm-rpc problem sein. 

Weitere infos / tests gerne...

Grüße
Udo

**Comment by Apollon77** [comment]
Bitte aktuelle Version vom Github versuchen ... sollte gefixt sein
