### ISSUE TITLE
Wrong values for blind level in 1.4.7

### ISSUE THREAD

**Issue by nobodyMO** [ioBroker/ioBroker.hm-rega#25]
Seit dem Update werden die Level-Werte für die Jalousie-Aktoren nicht mehr in Prozent umgerechnet. 
Statt 100 Prozent werden von HM-Rega nun 1 und für 30% nun 0,3% geschrieben.

**Comment by Apollon77** [comment]
fixed?

**Comment by nobodyMO** [comment]
The isssue is fixed in the current version
