### ISSUE TITLE
Homematic Variablen werden falsch angelegt.

### ISSUE THREAD

**Issue by Burgruine** [ioBroker/ioBroker.hm-rega#268]
Seit aktueller Version folgendes Verhalten: Legt man in der Homematic eine Variable an mit Werteliste z.B. Wert 1; Wert 2; Wert 3 dann erscheint in den Objekten nur 1; 2; 3 mit alter Version sah es so aus;  Wert 1(0); Wert 2(1); Wert 3(2). Installiert man z.B. Version 3.0.33 dann werden die Werte wieder so angelegt wie früher. Nach update auf aktuelle Version bleiben die Werte erhalten und können nachträglich auch verändert werden. Manche neu angelegten Variablen legt er in Objekten unter einen Programm Ordner an und überschreibt irgendeinen.

**Comment by foxriver76** [comment]
Am besten die Objekte posten, damit mir der Unterschied klar wird

**Comment by Burgruine** [comment]
Testvariable und Test3 der Unterschied

![4](https://user-images.githubusercontent.com/84285066/160212627-fa9bb076-5760-4df9-87e5-b219d17d7aca.jpg)


![3](https://user-images.githubusercontent.com/84285066/160212670-ccc2411e-9575-45a2-8eab-ab48d9af6496.jpg)
![5](https://user-images.githubusercontent.com/84285066/160212680-862191e0-68bc-4b78-a945-bff67f045e5a.jpg)

Hier noch die Programme die er überschreibt: Dort wo "Variable Test 2" steht war vorher "Wetterwarnung"

![2](https://user-images.githubusercontent.com/84285066/160212729-ca97635c-5f8b-4634-b163-025d7d59b6a5.jpg)

**Comment by foxriver76** [comment]
Hm ok das einzige was sein kann ist das https://github.com/ioBroker/ioBroker.hm-rega/commit/bc9ca74b9447d778759c8cd0ae5f72f3eaec9084

mit 3.0.34 ist es schon kaputt oder?

**Comment by Burgruine** [comment]
Ja, habs jetzt kurz getestet mit 3.0.34 Fehler auch da.

**Comment by foxriver76** [comment]
Ok, dann muss ich da nochmal rein schauen.

**Comment by Burgruine** [comment]
Ok Danke.

**Comment by foxriver76** [comment]
Aber mal bitte noch bei beiden hinten auf den Stift klicken, und den Inhalt vom Reiter raw posten. Die verlinkte Änderung meinerseits dürfte eigentlich keinen Einfluss haben, aber wenn du sagst ab 3.0.34 kaputt ist es Strange, da das die einzige Änderung ist.

**Comment by Burgruine** [comment]
In Ordnung:

- {
  "_id": "hm-rega.0.49027",
  "type": "state",
  "common": {
    "name": "Testvariable",
    "type": "number",
    "read": true,
    "write": true,
    "role": "state",
    "states": {
      "0": "Wert 1",
      "1": "Wert 2",
      "2": "Wert 3"
    },
    "min": 0,
    "max": 2
  },
  "native": {
    "Name": "Testvariable",
    "TypeName": "VARDP",
    "DPInfo": "",
    "ValueMin": null,
    "ValueMax": null,
    "ValueUnit": "",
    "ValueType": 16,
    "ValueSubType": 29,
    "ValueList": ""
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1648249875883,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

falsch:

- {
  "_id": "hm-rega.0.49061",
  "type": "state",
  "common": {
    "name": "Test3",
    "type": "number",
    "read": true,
    "write": true,
    "role": "state"
  },
  "native": {
    "Name": "Test3",
    "TypeName": "VARDP",
    "DPInfo": "",
    "ValueMin": null,
    "ValueMax": null,
    "ValueUnit": "",
    "ValueType": 16,
    "ValueSubType": 29,
    "ValueList": ""
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1648249875894,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by foxriver76** [comment]
Hm die hast du jetzt beide mit einer Version raus gezogen oder?

**Comment by isi07** [comment]
Hallo
bin mir nicht sicher, ob meine Beobachtung direkt damit zusammenhängt...
Ich habe gerade die neue Version v.3.0.38 installiert. (kann aber nicht sagen, ob es vorher auch schon so war)

Ich habe nun bei allen Datenpunkten von Systemvariablen -also auch bei reinen Zahlen- das Phänomen, dass irgend eine statelist im iobroker Objekt gezogen und hinzugefügt wird.
Hier ein Beispiel eines Temperatur-Datenpunktes mit min -50 und max 50

> {
>   "_id": "hm-rega.0.15732",
>   "type": "state",
>   "common": {
>     "name": "SV_Beschattung_Forecast_Temp",
>     "type": "number",
>     "read": true,
>     "write": true,
>     "role": "state",
>     "min": -50,
>     "max": 50,
>     "unit": "ºC",
>     "desc": "Typ Zahl mit -50 bis +50 ºC",
**>     "states": {
>       "0": "Ruhe",
>       "1": "Oben",
>       "2": "Unten",
>       "3": "Schatten"
>     },**
>     "custom": {
>       "influxdb.0": {
>         "enabled": true,
>         "storageType": "",
>         "aliasId": "",
>         "changesOnly": true,
>         "debounce": "1000",
>         "changesRelogInterval": 60,
>         "changesMinDelta": "0"
>       }
>     }
>   },
>   "native": {
>     "Name": "SV_Beschattung_Forecast_Temp",
>     "TypeName": "VARDP",
>     "DPInfo": "Typ Zahl mit -50 bis +50 ºC",
>     "ValueMin": -50,
>     "ValueMax": 50,
>     "ValueUnit": "ºC",
>     "ValueType": 4,
>     "ValueSubType": 0,
>     "ValueList": "Ruhe;Oben;Unten;Schatten"
>   },
>   "acl": {
>     "object": 1636,
>     "state": 1636,
>     "owner": "system.user.admin",
>     "ownerGroup": "system.group.administrator"
>   },
>   "from": "system.adapter.hm-rega.0",
>   "user": "system.user.admin",
>   "ts": 1648289712645
> }

Ich hatte nach der Installation des Adapters aus einem anderen Grund (einige Systemvariablen waren als Ordner angelegt), alle Objekte unter hm-rega.0. einmal gelöscht und neu synchronisieren lassen.

Ist das normal? Mache ich etwas falsch oder sollte ich einen neuen issue aufmachen?
Viele Grüße
Christian

**Comment by foxriver76** [comment]
Hm da ist aber ne value list in der ccu bei deinem dp. Vorher war es anders I’m iob für paar Versionen da bug ab 3.0.34, check mal die sysvar in der ccu

**Comment by isi07** [comment]
In der Homematic ist die Variable als Zahl angelegt.
![grafik](https://user-images.githubusercontent.com/65848350/160237948-7e465511-1cac-4633-9cd2-4487e1c3036d.png)

Hatte es oben nur als Update hinzugefügt.
Ich bin zurück auf Version v.3.0.37 und hab alle Objekte unter hm-rega.0. gelöscht und neu anlegen lassen.
Danach ist das Problem verschwunden.

**Comment by harvey637** [comment]
Hi,
kann das Problem bestätigen mit 3.0.38:
eine Zahl bekommt plötzlich eine Werteliste:

Die Zahl ist als "Zahl, 0 - 65000, kWh" angelegt, daraus wird (auch nach löschen und neustart iobroker.rega):
```
{
  "_id": "hm-rega.0.31426",
  "type": "state",
  "common": {
    "name": "WP-cooling_now",
    "type": "number",
    "read": true,
    "write": true,
    "role": "state",
    "min": 0,
    "max": 65000,
    "unit": "kWh",
    "desc": "Bosch Kühlung Verbrauch akt. Stunde",
    "states": {
      "0": "7.10",
      "1": "8.15",
      "2": "9.05",
      "3": "9.10",
      "4": "9.00",
      "5": "10.00"
    }
  },
  "native": {
    "Name": "WP-cooling_now",
    "TypeName": "VARDP",
    "DPInfo": "Bosch Kühlung Verbrauch akt. Stunde",
    "ValueMin": 0,
    "ValueMax": 65000,
    "ValueUnit": "kWh",
    "ValueType": 4,
    "ValueSubType": 0,
    "ValueList": "7.10;8.15;9.05;9.10;9.00;10.00"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1648301160710,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
```

Lustig ist, dass es auf dem Common-Reiter korrekt als "Zahl" dargestellt wird. Die Darstellung als Objekt ist dann allerdings "durcheinander": es wird ein unsinniger Wert aus einer Werteliste (die zu einer ganz anderen Variable gehört), die richtige Einheit und der richtige Wert in Klammern angezeigt.

Wenn noch was gebraucht wird .... gerne melden

**Comment by harvey637** [comment]
Nur als Zusatz: die falsche Werteliste taucht auch bei anderen Variablen auf. Sichtbar wird es allerdings nur bei Variablen, deren werte innerhalb der Werteliste umsetzbar sind, also bei 0(=null), 1(=eins). Bei 5400 (also weit außerhalb) tritt der Darstellungsfehler nicht auf. Hier ein Beispiel, das optisch ok aussieht, aber intern auch die falsche Werteliste enthält:

```
{
  "_id": "hm-rega.0.28696",
  "type": "state",
  "common": {
    "name": "WP-compressor_h",
    "type": "number",
    "read": true,
    "write": true,
    "role": "state",
    "min": 0,
    "max": 65000,
    "unit": "kWh",
    "desc": "Bosch Compressor Stunde",
    "states": {
      "0": "7.10",
      "1": "8.15",
      "2": "9.05",
      "3": "9.10",
      "4": "9.00",
      "5": "10.00"
    }
  },
  "native": {
    "Name": "WP-compressor_h",
    "TypeName": "VARDP",
    "DPInfo": "Bosch Compressor Stunde",
    "ValueMin": 0,
    "ValueMax": 65000,
    "ValueUnit": "kWh",
    "ValueType": 4,
    "ValueSubType": 0,
    "ValueList": "7.10;8.15;9.05;9.10;9.00;10.00"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1648301160446,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by foxriver76** [comment]
3.0.39 auf dem Weg, damit sollte es dann hoffentlich tun. Danke für die Hinweise

**Comment by isi07** [comment]
Danke. In der 3.0.39 sieht es bei mir ok aus.

**Comment by Burgruine** [comment]
Mit der aktuellen Version läuft bis jetzt alles bestens, Danke!

**Comment by harvey637** [comment]
yes Sir, I can boogie - läuft!
