### ISSUE TITLE
Wallswitch HM-PB-2-WM55-2 Not working

### ISSUE THREAD

**Issue by jhg28** [ioBroker/ioBroker.hm-rega#269]
I use a Wall Switch HM-PB-2-WM55-2 to switch a Yeelight ceiling lamp.
Since I've updated the new version 3.0.39, of this adapter the signal from the wall switch is not synced with ioBroker.
All of the other switches are working properly.

Had this issue also with older version, worked perfect after an update, but now it's once more there.

I can see in the Homematic protokoll that the button at the switch is pushed.
But no reaction on ioBroker.

**Comment by foxriver76** [comment]
Rega is only updating datapoints once at the start of the rega adapter, so I guess what you are observing is not due to the Rega update.

**Comment by jhg28** [comment]
Did now additional checks.
Noticed that the connection from ioBroker to the Yeelight is lost.
Apologize for opening the issue.
Can be closed.
