### ISSUE TITLE
Hm-rega verbindet sich nicht

### ISSUE THREAD

**Issue by ymurawski** [ioBroker/ioBroker.hm-rega#284]
Hallo ,
ich habe einen Raspberry Pi mit iobroker drauf und Raspberrymatic als docker . Dem entsprechend sind natürlich iobroker und Raspberrymatic auf der gleichen ip zu erreichen.

Iobroker erreiche ich unter 192.168.1.205:8090 und Raspberrymatic unter 192.168.1.205:8080

Jetzt habe ich die hm-rpc laufen mit den settings siehe Screenshot. Diese Instanz ist auch grün.
Jedoch bekomme ich die hm-rega Instanz nicht grün. Ich habe per terminal den Port auf 8080 geändert...weiß aber nicht ob das der richtige für die Kommunikation ist.

Jemand ein Hinweis ? 
![Screenshot_20220507-143155_Chrome](https://user-images.githubusercontent.com/46036625/167256483-5302c891-c985-401f-9d6e-39824e1c1823.jpg)
![Screenshot_20220507-143142_Chrome](https://user-images.githubusercontent.com/46036625/167256486-776c09dd-4ce0-4862-964f-8b77e9d78558.jpg)
![Screenshot_20220507-143031_Chrome](https://user-images.githubusercontent.com/46036625/167256489-f63d1f6e-bb19-4706-bbf6-6b59dd9e1a2b.jpg)
![Screenshot_20220507-143044_Chrome](https://user-images.githubusercontent.com/46036625/167256495-f522c9c3-6e59-4cce-88eb-0048f401fb88.jpg)
![Screenshot_20220507-152922_Chrome](https://user-images.githubusercontent.com/46036625/167256518-506dda07-762c-479f-9f23-266c5000e662.jpg)

**Comment by krobipd** [comment]
Ich weiss nicht ob das noch aktuell ist aber du ja beides auf dem selben Rechner laufen. Daher gib mal als ip der ccu 127.0.0.1 ein - port natürlich dazu.

**Comment by 63chris** [comment]
@ymurawski - hast Du mal in RM unter Einstellungen - Systemsteuerung - Sicherheit mal geschaut, ob der Haken bei "Authentifizierung Aktiv" gesetzt ist? Dann musst Du den raus nehmen, oder eben im REGA Adapter Benutzer und Passwort für den HTTPS Zugriff angeben.
War bei mir zumindestens so

**Comment by 63chris** [comment]
Ich hänge mich hier mal rein, da ich am gleichen Problem rumdoktore. Raspberrymatic unter Docker auf Debian. IOB auf dem gleichen Rechner.
Habe auch mit "iob set hm-rega.0 --webinterfacePort 8080" den Zugang geschafft. RPC sowie REGA Adapter sind verbunden - **leider nur, wenn ich die IP des Rechners (192.168.x.x) benutze. Sobald ich 127.0.0.1 oder localhost angebe, verbindet sich der REGA Adapter nicht mehr.**
 
Fehlermeldungen sind  
- hm-rega.0  post request error: read ECONNRESET oder
- hm-rega.0  post request error: socket hang up
- hm-rega.0  CCU 127.0.0.1 unreachable

Die Verbindung über 127.0.0.1 machen zu können ist mir wichtig, damit ich den Router in der WE-Hütte nicht die ganze Zeit laufen lassen muss, wenn ich nicht da bin (Strom ist da recht teuer).

Bin Dankbar für Tips

**Comment by foxriver76** [comment]
Ich denke hier scheitert es an den Docker Basics. Läuft ioB in einem anderen Docker Container oder nativ auf dem System?

**Comment by 63chris** [comment]
iob läuft nativ

**Comment by foxriver76** [comment]
Ein Docker Container kann im „klassischen“ Netzwerk Modus nicht auf den restlichen Host via localhost zugreifen, sondern nur auf Dienste im Container.

falls du Linux nutzt sollte `172.17.0.1` funktionieren.

**Comment by foxriver76** [comment]
Zeig mal das compose File von dem CCU Docker.

**Comment by 63chris** [comment]
Hallo,

Danke für die Mühe. Ich habe das Problem jetzt anders gelößt (mit Debmatic). Ist zwar nicht ideal, aber läuft seamlessly.

Vielen Dank und happy season
Chris

**Comment by Baenker** [comment]
könnte dann das Issue geschlossen werden?

Ersteller hat sich nicht mehr gemeldet und das andere Problem besteht nicht mehr
