### ISSUE TITLE
State value to set for "hm-rega.0.CCU2GW0001.0.DUTY_CYCLE" has value "-1" less than min "0"

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.hm-rega#298]
Der Fehler kommt schon einige Zeit. Nun wollte ich den auch mal melden.
Bei meiner, zum LANGW degradierten, CCU2 bekomme ich die Meldung

State value to set for "hm-rega.0.CCU2GW0001.0.DUTY_CYCLE" has value "-1" less than min "0"

wenn diese mal nicht erreichbar ist. Der Wert "-1" wird auch ins Objekt geschrieben und ich kann diesen weiterverarbeiten, jedoch stört die Meldung im Log. 

Auch ein löschen des Objekts ändert nichts daran.
{
  "_id": "hm-rega.0.CCU2GW0001.0.DUTY_CYCLE",
  "type": "state",
  "common": {
    "name": "hm-rega.0.CCU2GW0001.0.DUTY_CYCLE",
    "type": "number",
    "read": true,
    "write": false,
    "role": "value",
    "min": 0,
    "max": 100,
    "unit": "%",
    "desc": "Dutycycle"
  },
  "native": {
    "ID": "DUTYCYCLE",
    "TYPE": "INTEGER",
    "MIN": 0,
    "MAX": 100,
    "UNIT": "%",
    "DEFAULT": 0,
    "CONTROL": "NONE"
  },

hm-rega: 3.0.40 
node: v16.16.0
js-controller: 4.0.23
Raspberrymatic 3.65.6.20220723

**Comment by foxriver76** [comment]
Sollte mit Rega 3.0.40 nicht mehr auftreten https://github.com/ioBroker/ioBroker.hm-rega/commit/23d551e567d4ea247a6384608da50636399b9eb2

**Comment by MarkSau** [comment]
> Sollte mit Rega 3.0.40 nicht mehr auftreten 

Scheinbar nicht gelöst, da ich diese Version installiert habe
