### ISSUE TITLE
Translation of ENUMS in case where enums come across with $..... from CCU

### ISSUE THREAD

**Issue by looxer01** [ioBroker/ioBroker.hm-rega#30]
It very often happens that new user are not changing the enums in the CCU which leads to the fact that the REGA adapter receives enums as $......
It should be possible in the REGA adapter to use the same translation list as the CCU does which would result in less iritations of users.
Downside would be for cases where a CCU update leads to a requirement to update the ioBroker REGA translation list. I assume that would not happen often though.

Example of one of those discussions:

http://forum.iobroker.net/viewtopic.php?f=21&t=10096&start=40

**Comment by GermanBluefox** [comment]
Is there any list of all possible $names$ ?

**Comment by GermanBluefox** [comment]
Done with latest version of hm-rega

**Comment by foxriver76** [comment]
Guess, it can be closed then :-)
