### ISSUE TITLE
Make sure new "forbidden characters handling" from hm-rpc are also respected in hm-rega

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.hm-rega#32]
see https://github.com/ioBroker/ioBroker.hm-rpc/issues/75

Additionally: ${functionLight} also needs to be replaced

basically for: https://github.com/ioBroker/ioBroker.js-controller/issues/198

**Comment by GermanBluefox** [comment]
Done

**Comment by Apollon77** [comment]
Sent to forum for test

**Comment by foxriver76** [comment]
close? :-)
