### ISSUE TITLE
rfd no rooms in channel 0

### ISSUE THREAD

**Issue by fs-plugins** [ioBroker/ioBroker.hm-rega#320]
Adapter-Version 3.0.40
Admin 6.2.23

Protokoll XML-RPC
von den rfd-Geräten werden in channel 0 die Räume nicht übernommen
werden die Räume unter Objekte 'händisch' nachgetragen, sind sie bei der nächsten Aktualisierung wieder gelöscht
in channel 0 sind u.a. die Batteriemeldungen hinterlegt, deshalb ist es wichtig die Raumzordnung dabei zu haben
(bei HM-IP-Geräten besteht dieses Problem nicht)

was habe ich versucht:
Geräte neu einlesen 
Räume neu in Homematic zugeordnet, Neustart, Adapter Neustart
Räume per Hand dem channel 0 zugeordnet

**Comment by foxriver76** [comment]
Indeed, checked it, it is the same for me. Unfortunately I don't have the time/priority combo to dig deeper into this. 

We are currently using this script: https://github.com/ioBroker/ioBroker.hm-rega/blob/master/regascripts/rooms.fn
Maybe @jens-maus or someone who is familiar with rega scripting knows at a quick check why this isn't working, then I can adjust it.

**Comment by foxriver76** [comment]
Vermutlich ist es nur ein Change von https://github.com/ioBroker/ioBroker.hm-rega/blob/9bc37e9a0d263df9112a1d93a84870e465d845ea/regascripts/rooms.fn#L31

auf `EnumIDs` statt `EnumUsedIDs`

**Comment by fs-plugins** [comment]
danke für ansehen
habe das mal so geändert -> Neustart -> keine Besserung
mit Zeile 15 hab ich es dann auch noch probiert zusätzlich

könnte es sein, das die Ursache nicht im rega sondern im rpc liegt?
denn channel höher 0 bekommen die Räume zugeordnet

**Comment by foxriver76** [comment]
also ich hatte es kurz auf der CCU probiert und da ist der 0er mit raus gekommen. Wie genau bist du vorgegangen zum probieren?

**Comment by fs-plugins** [comment]
perfekt, nochmals dankeschön :)
