### ISSUE TITLE
Crash when reading system variables

### ISSUE THREAD

**Issue by derrapf** [ioBroker/ioBroker.hm-rega#33]
Referring to https://forum.iobroker.net/viewtopic.php?f=30&t=8039&p=159775#p159775 there is an issue when reading the Systemvariables. rega adapter aborts on reading with error
```
2018-07-06 12:05:57.921 - error: hm-rega.0 Cannot parse answer for
variables:
{"40":{"Name":"Alarmmeldungen","TypeName":"VARDP","DPInfo":"Anzahl%20Alarmmeldungen","Value":0,"ValueMin":0,"ValueMax":65000,"ValueUnit":"","ValueType":16,"ValueSubType":0,"ValueList":""},
"41":{"Name":"Servicemeldungen","TypeName":"VARDP","DPInfo":"Anzahl%20Servicemeldungen","Value":13,"ValueMin":0,"ValueMax":65000,"ValueUnit":"","ValueType":16,"ValueSubType":0,"ValueList":""},
"15116":{"Name":"Abwesenheit","TypeName":"VARDP","DPInfo":"Keiner%20im%20Haus%2C%20weil%20Haust%FCr%20abgeschlossen","Value":false,"Timestamp":"2018-07-05
14:30:08","ValueMin":null,"ValueMax":null,"ValueUnit":"","ValueType":2,"ValueSubType":2,"ValueList":"ist%20falsch%3Bist%20wahr"},
"1322":{"Name":"Alarmzone%201","TypeName":"ALARMDP","DPInfo":"Alarmmeldung%20Alarmzone%201","Value":false,"Timestamp":"1970-01-01
01:00:00","ValueMin":null,"ValueMax":null,"ValueUnit":"","ValueType":2,"ValueSubType":6,"ValueList":"nicht%20ausgel%F6st%3Bausgel%F6st"},
"2033":{"Name":"Arbeitstag_heute","TypeName":"VARDP","DPInfo":"Arbeitstag%20heute","Value":true,"Timestamp":"2018-06-26
03:03:46","ValueMin":null,"ValueMax":null,"ValueUnit":"","ValueType":2,"ValueSubType":2,"ValueList":"ist%20falsch%3Bist%20wahr"},
"2034":{"Name":"Arbeitstag_morgen","TypeName":"VARDP","DPInfo":"Arbeitstag%20morgen","Value":true,"Timestamp":"2018-06-26
03:03:46","ValueMin":null,"ValueMax":null,"ValueUnit":"","ValueType":2,"ValueSubType":2,"ValueList":"ist%20falsch%3Bist%20wahr"},
"7026":{"Name":"Aussentemperatur","TypeName":"VARDP","DPInfo":"Aussentemperatur","Value":3.141500,"Timestamp":"2018-06-26
03:03:46","ValueMin":-100,"ValueMax":100,"ValueUnit":"%B0C","ValueType":4,"ValueSubType":0,"ValueList":""},
"11971":{"Name":"Aussentemperatur-aussen","TypeName":"VARDP","DPInfo":"","Value":25.812000,"Timestamp":"2018-07
...
```
Full log attached
Regards Ralf
[iobroker.2018-07-06.log.txt](https://github.com/ioBroker/ioBroker.hm-rega/files/2170467/iobroker.2018-07-06.log.txt)

**Comment by Apollon77** [comment]
Idee Erinnerung: -inf vor dem parsen des json einfach ersetzen durch null.

**Comment by GermanBluefox** [comment]
Warum sind ALLE "Timestamp" mit Zeilenumbruch????
```
 "2018-06-26
03:03:46"
```

**Comment by Apollon77** [comment]
Weil log bestimmt irgendwo her kopiert wurde ;-). Alle Zeilenumbrüche entfernen und es bleiben zwei werte mit 

-inf

Als value übrig die nicht json konform sind.

**Comment by derrapf** [comment]
Wenn man aus Iobroker den Button "Download Log" drückt wird eine html Seite downgeloaded die aber kein echtes HTML ist sondern Text. Der Browser zeigt sie ohne Umbruch an. Wenn man sie in *.txt umbenennt und hochlädt entstehen die Zeilenumbrüche (Html kann man ja nicht hochladen). PS: Ich hatte auch Systemvariablen (String) mit dem Wert "???". Wäre das auch etwas das man abfangen müsste?

**Comment by Apollon77** [comment]
Wenn es ein ??? In Anführungszeichen ist dann kein Problem.

**Comment by GermanBluefox** [comment]
Ich bin der Meinung, dass Zeilenumbruch do da ist, sonst verstehe ich nicht, wieso JSON Parse Fehler kommt

**Comment by Apollon77** [comment]
Im Forum Thread war das ganze json und ich habe die Zeilenumbrüche entfernt. Dann gab es zwei stellen mit 

„value“: -inf,

Und -inf ist einfach kein valider Wert. Das ist das ungültige daran.
