### ISSUE TITLE
after new room assignment at CCU, new assignment is not visible at iobroker objects

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.hm-rega#34]
Hi,

i changed a room assignment for a device at my CCU, deleted the device at iobroker objects, restart RPC but the device come back with old room assigment at iobroker.

Then i restarted REGA and after that the device was visible with old and new room:

![image](https://user-images.githubusercontent.com/33424168/43244443-f17a870a-90aa-11e8-9e57-1f9d68f5e52a.png)

According to this thread https://forum.iobroker.net/viewtopic.php?f=8&t=15651 it might be a bug !?

**Comment by Apollon77** [comment]
This is "as designed". The room and function names are only synced once  because else changes on ioBroker side would also be overwritten.

**Comment by wendy2702** [comment]
What means "synced once" ?

If i delete a device from my Objects it is not known by iobroker anymore. If i then do a restart of RPC/REGA it should be handled as a first sync for this specific device and shown with new room assigment from my point of view.

**Comment by foxriver76** [comment]
Have you also deleted the device before the REGA restart? Because from reading your issue I imagine the scenario as:

- Rega knows the old room because not restarted
- you have deleted the device and restarted rpc
- Due that rega still only knows the old room, this old room is assigned to the newly created object
- Now you restart rega and now rega knows the new room
- Rega assigns the new room to the object too, but does not delete the old enum, because REGA doesnt know the context (it could also be a enum which is manually assigned in ioB by you)

**Comment by foxriver76** [comment]
The problem here is, that when I delete a channel or device which is part of a enumeration, the enumeration still holds the information and on recreating it, it will be marked as part of the enumeration again. So this is more likely a js-controller issue.

**Comment by DutchmanNL** [comment]
i will try 2.4.8 from git as its not on npm yet

**Comment by foxriver76** [comment]
Published to npm at 6 am but maybe not in ioB repo yet.

**Comment by DutchmanNL** [comment]
ah sorry you are right ... will install from command line all good

**Comment by DutchmanNL** [comment]
Not solved

Objects
<img width="1507" alt="Schermafbeelding 2019-09-04 om 13 54 10" src="https://user-images.githubusercontent.com/7318445/64252520-7aa1c700-cf1b-11e9-896b-e2689d2cd2a9.png">

Same objects after adapter restart HM-Rega 2.4.8 : 

<img width="1499" alt="Schermafbeelding 2019-09-04 om 13 55 12" src="https://user-images.githubusercontent.com/7318445/64252580-a02ed080-cf1b-11e9-9e4f-c46b938e5a5e.png">

**Comment by foxriver76** [comment]
kann dem Screenshot nicht entnehmen was gemacht wurde. Geschweige denn dass es keine hm-Rega Variablen zu sein scheinen, da der Filter auf Zigbee steht? Geht es um ein anderes Problem als oben beschrieben dann bitte schildern.

**Comment by foxriver76** [comment]
Ach so, das Issue hier wurde auch nicht als gelöst markiert, da es nicht behoben ist..

**Comment by foxriver76** [comment]
Siehe https://github.com/ioBroker/ioBroker.js-controller/issues/313

**Comment by DutchmanNL** [comment]
Das problem ist das der Rega objecte löscht die in ioBroker zugewiesen werden.

Beispiel : ich erstelle alle Räume in der ccu
Ich füge in ioBroker an der enum Gewerke. Zu
Nach hm-rega Neustart Sonne dieser wieder Weck und nur diejenigen drin die auch in der ccu stehen.

Wir hatten dasselbe Mal mit Funktionen siehe verlinkten issue von mir damals

**Comment by foxriver76** [comment]
Ah du meinst das hier #70 nur für Rooms, ja sehe den Fehler. Danke fürs melden, war hier ein bisschen durcheinander mit den Tickets.

**Comment by foxriver76** [comment]
@DutchmanNL so 2.4.9 sollte es hoffentlich beheben. Sorry, dass die Bugs zu dieser Enum-Geschichte hier so langsam reintrudeln, hatte allerdings damals [explizit Tester gesucht](https://forum.iobroker.net/topic/24164/aufruf-hm-rega-enum-sync-testen) und keiner hatte Zeit/Lust.

**Comment by DutchmanNL** [comment]
@foxriver76 kein problem dafür machen wir ja latest und bin ich auch dran hauptsache vor stable sind solche Sachen raus.

Wo hast du gefragt hab ich was verpasst?

Ich teste die neue Version heut Abend

**Comment by foxriver76** [comment]
Gefragt habe ich, siehe Verlinkungen im vorherigen Kommentar. Da hast du recht.

**Comment by DutchmanNL** [comment]
fixed in 2.4.9

**Comment by foxriver76** [comment]
original issue fixed via https://github.com/ioBroker/ioBroker.js-controller/pull/670
