### ISSUE TITLE
Namen von Homematic IP und IPW werden nicht übernommen.

### ISSUE THREAD

**Issue by Continueless** [ioBroker/ioBroker.hm-rega#349]
Hallo,

der Adapter übernimmt von den IP und IPW Produkten die Namen nicht in die Objekte. Bei den alten Produkten werden die Namen übernommen. Es wäre schon wichtig das die Kanalnamen übernommen werden, die Gerätenamen sind nicht so wichtig.

Die Dimmaktoren z.b. haben 3 Kanäle. Wenn die nicht benannt sind, dann ist es schon anstrengend und auch schlecht auszuwerten.

Händisch lassen sich die Namen nachtragen, aber ich habe hunderte Kanäle, die ich dann nochmals eintragen müsste. Außerdem ist das dann alles wieder weg, wenn geupdated wird.

Im openhab binding funktioniert das übrigens problemlos !

Grüße

**Comment by Apollon77** [comment]
Für Namen ist der hm-rega Adapter Verantwortlich. Die beiden arbeiten zusammen. Ist dieser Installiert?

**Comment by foxriver76** [comment]
Wenn von alt geht, dann vermutlich in rega nicht die IP Instanz hinterlegt.

**Comment by Continueless** [comment]
ich kann keine Homematic IP aktvieren, da dann eine rpc instanz verlangt wird, die ich nicht auswählen kann.

In rfd ist eine der rpc instanzen gewählt.
