### ISSUE TITLE
RSSI value fixed

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.hm-rega#352]
adaption needed, see https://github.com/jens-maus/RaspberryMatic/issues/897#issuecomment-1418258733

**Comment by jens-maus** [comment]
One question regarding this `RSSI_PEER`/ `RSSI_DEVICE` polling using ioBroker.hm-rega I would like to raise is: Why are these values pulled via hm-rega in first place? These values should also be delivered/updates using xmlrpc, thus ioBroker.hm-rpc would be IMHO the more appropriate place for such things... But this is of course just an idea without having a look the source code, etc. myself yet.

**Comment by foxriver76** [comment]
It is due to the whole logic of Rega/RPC adapter. Rega can poll, RPC can't (AFAIK). Thus when adapter starts, we want to ensure values are up-to-date. Thus, one poll over all dps is done, after then RPC can keep values up-to-date.

**Comment by jens-maus** [comment]
Ah ok, got it. This makes sense of course. So all you then probably need is to identify a way if either the RSSI values overflow after the -256 substraction now or (better) check for the `ValueType()` of the datatype of `RSSI_DEVICE/PEER` and if it isn't byte but integer (16) then omit the substraction (which always was a workaround for a ReGa bug). But this of course would been you need to transfer the information from the datapoints rega script to the calling process where you do the substraction or you move the substraction to the rega script hm-rega uses... up to you :)
