### ISSUE TITLE
HM-Rega write 0 value state for HM-IP devices

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.hm-rega#36]
I noticed in my influxdb graphs that i have 0 values for temperatures related to thermostats of the HomeMatic IP series.

Based on the logging it looks like, after a CCU reboot, the HM-Rega write 0 as value to the states.
I wondering why the HM-Rega is updating these values, shouldn't that been handled by the HM-RPC ?
Also when a CCU reboot happens (i also rebooted HM-Rega at that time) the 0 value should not be writte but the real value of the temperature.

See below logging summary of a radiator device (HMIP-eTRV)

![image](https://user-images.githubusercontent.com/7318445/45929633-cd75af00-bf54-11e8-842d-4d4e19ab3d92.png)

**Comment by Apollon77** [comment]
Wenn die hm-rega gestartet wird dann holt diese ebenso zusammen mit den Namen und so auch den aktuellen Wert ab und schreibt Ihr einmalig in die States (quasi als Startwert, hm-rpc macht dann die Aktualisierungen danach). Bedeutet: Scheinbar liefert die CCU an der Stelle einfach diese 0 ...

**Comment by foxriver76** [comment]
Ich habe derzeit ein ähnliches Problem beobachtet, im Zusammenhang mit diesem Verhalten. Ein Rolladenaktor wird bei Neustart der Rega mit dem aktuellen Wert beschrieben, allerdings schreibt REGA beispielsweise statt 30 % den Wert 0.3 % in den State. Vermutlich müssten hierbei die Meta Daten berücksichtigt werden.

**Comment by foxriver76** [comment]
@Apollon77 Warum setzen wir überhaupt von Rega aus die Datenpunkte beim Start? Ich sehe das wie Dutch: erwarten würde ich das nur von hm-rpc.

**Comment by foxriver76** [comment]
Das von mir besprochene Problem ist gefixt mit https://github.com/ioBroker/ioBroker.hm-rega/commit/8cf025239437204d435f34417061818bce25e444
Falls es bei @DutchmanNL auftritt sollte man mal das https://github.com/ioBroker/ioBroker.hm-rega/blob/master/regascripts/datapoints.fn Skript auf der CCU ausführen und schauen ob dort andere Werte raus kommen. Letztendlich werden nur mit diesem Skript die Datenpunkte von hm-rpc ausgelesen.

**Comment by Apollon77** [comment]
Der hm-rpc bekommt nur "Push infos" bei änderungen. Die Rega sorgt damit dafür das beim start der rega alle initialen Werte einmalig gefüllt werden

**Comment by Apollon77** [comment]
PS: Absiucht das https://github.com/ioBroker/ioBroker.hm-rega/commit/8cf025239437204d435f34417061818bce25e444#diff-c7bce6ed06a32d678b1e0af81b039d2eR1254 noch drin ist?
