### ISSUE TITLE
[Enhancement] Enable HTTPS and Auth like in RPC

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.hm-rega#37]
see https://github.com/ioBroker/ioBroker.hm-rpc/issues/94
The https ports are are the same as usual expect that they start with an additional 4.

**Comment by Zefau** [comment]
Vielen Dank für die Implementierung. Brauchst du noch Unterstützung? 
Funktioniert bei mir bereits soweit. 
Lediglich das Log zeigt noch "http" statt "https": 
`xmlrpc client is trying to connect to 192.168.178.30:42010/ with ["http://192.168.178.29:42010","hm-rpc.0"]`

**Comment by foxriver76** [comment]
It should work fine, as long as CCU is configured correctly. Thanks for providing support.

I will adjust the logging in rpc. (This is the Rega ticket :) )

We started a testing thread for both https://forum.iobroker.net/viewtopic.php?f=36&t=18979

Von meinem iPhone gesendet
