### ISSUE TITLE
Homebrew HB-UNI-Sen-RFID-RC

### ISSUE THREAD

**Issue by RasputinBerry** [ioBroker/ioBroker.hm-rega#379]
Ich habe o.g. [Homebrew RFID Leser](https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC) nachgebaut ... funktioniert in der RaspberryMatic.
Die Datenpunkte werden, nach Neustart des hm-rega-Adapters, im ioBroker angelegt, aber (scheinbar?) nicht aktualisiert.
Anders formuliert:
Wenn ich die RFID Karte an den Leser halte, wird ein Programm in der RaspberryMatic ausgeführt, im ioBroker passiert nix. 
Mache ich etwas falsch ? 
Wäre schade, wenn das Teil nur in der RaspberryMatic funtioniert ...

![grafik](https://user-images.githubusercontent.com/56359831/234014818-5573293d-f39d-41e9-8fc7-defe848cb587.png)

**Comment by RasputinBerry** [comment]
Boah eh ... das war jetzt die **SCHNELLSTE** Antwort die ich je in einem Forum bekommen habe ... 

Leider reicht man Verständnis der Materie (bzw. Verständnis der "Additionel information") bei weitem nicht aus, wie solch ein "single dummy programm" aussehen muss.

Ich bin mal unverschämt und bedanke mich vorab für die Erleuchtung ...

**Comment by foxriver76** [comment]
In der CCU ein Programm, in dem du auf diebenötigten Buttons hörst in `WENN` und `DANN` kannst du leer lassen. Wenn Taster nicht genutzt werden, werden diese nicht automatisch synchronisiert (Limitierung auf CCU) Seite.

**Comment by RasputinBerry** [comment]
... ich habe das jetzt so verstanden:

![grafik](https://user-images.githubusercontent.com/56359831/234029097-114240ca-a841-4123-ad16-7e6b9d2d9233.png)

Leider rührt sich (noch immer) nix im ioBroker, alles sieht aus wie im ersten Screenshot.
