### ISSUE TITLE
DutyCycle wird nicht von CCU2 gelesen

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.hm-rega#47]
Hallo,
mit der Version 2.1.5 des Adapters kann aus der CCU2 (aktuelle Firmware) kein DutyCycle gelesen werden. Fehler liegt offenbar am Port auf dem die XML-Schnittstelle den DC auf der CCU2 abfragt. Dieser wurde von 2001 auf 32001 geändert wegen der Authentifizierung bei der neuen CCU3 (--> danke für die Erklärung @foxriver76 )

Siehe auch Forenbeitrag: https://forum.iobroker.net/viewtopic.php?f=20&t=21112#p221742

Gruß Steffen

**Comment by foxriver76** [comment]
- realates to #40 (port 32001 does not seem to work on CCU2) and https://github.com/jens-maus/RaspberryMatic/issues/533
- As soon as a new version of Raspberrymatic is published we should change the script back to 2001, becasue of the following fix this will then work for CCU2 as well as Auth-enabled CCU3 again: https://github.com/jens-maus/RaspberryMatic/commit/4f9c2d50bf12a96349f7b5765987ee6d120837b4
