### ISSUE TITLE
Namen werden nicht komplett gefüllt seit V 2.1.3

### ISSUE THREAD

**Issue by MikePape** [ioBroker/ioBroker.hm-rega#48]
Bei uns werden die Namen nicht mehr komplett gefüllt:

![image](https://user-images.githubusercontent.com/46883316/51456677-e6e60680-1d4e-11e9-8b1a-298df19c9fb1.png)

Damit wird auch in den Scripts die Auswahl nicht mehr richtig angezeigt:

![image](https://user-images.githubusercontent.com/46883316/51456716-0846f280-1d4f-11e9-8e87-ec1abeb33ff4.png)

Kann es an der Version liegen?

**Comment by foxriver76** [comment]
Kann es nachstellen, nur noch device und channels werden benannt, einzelne Datenpunkte nicht.

**Comment by foxriver76** [comment]
Sollte gefixt sein, werde es gleich auf npm pushen, da es Kernfunktionalität von Rega ist.
