### ISSUE TITLE
DutyCycle Object shows name CCU2 instead of CCU3

### ISSUE THREAD

**Issue by DanielWeeber** [ioBroker/ioBroker.hm-rega#49]
see above

**Comment by DanielWeeber** [comment]
https://github.com/eq-3/occu/issues/91

Thank you for your very fast response.

**Comment by foxriver76** [comment]
As mentioned in the other issue, it seems like that no one will fix it for us --> we could take an approach:

```
!# Version.fn 0.1
string stderr;
string stdout;
system.Exec('cat /VERSION', &stdout, &stderr);
WriteLine(stdout);
```

which results in 

```
VERSION=3.41.11.20181222
PRODUCT=raspmatic_rpi3
PLATFORM=rpi3
```

than we set the CCU name to 'CCU' + first number of version and introduce a new state firmwareVersion which will store the whole version number. And marking the old version state explicitly as coprocessor version.

**Comment by DanielWeeber** [comment]
Sounds promising.

Here is the output of my CCU3 to help you:

> VERSION=3.41.11
> PRODUCT=ccu3
> PLATFORM=rpi3

**Comment by DanielWeeber** [comment]
Working! Thanks.

**Comment by foxriver76** [comment]
You are welcome.

For documentation: I removed coprocessor fw version, because from my point of view it was never intended to show this kind of information in the adapter, so just replaced the state with the real CCU firmware, what should be the information, the user expects in this state.
