### ISSUE TITLE
Common name falsch befühlt bei ALARM Onjekten

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.hm-rega#52]
Der Name unter Common.name bei den ALARM Objekten wird anders gefüllt als bei den anderen Feldern. Es wäre wünschenswert wenn die Bezeichnung einheitlich der sprechende Name wäre. Die Seriennr ist dort eher ungünstig. Eine Pusmeldung: Kommunikationsstörung bei Wandthermostat Wohnzimmer ist informativer als eine Nachricht: Kommunikationsstörung MEQ1234567

![unbenannt](https://user-images.githubusercontent.com/22763577/51912400-8d2baf00-23d4-11e9-9fa2-7873fb400208.JPG)

Ich benutzte verschiedene Scripte. Dort frage ich auf die ALRAM Felder ab. 

Über

var Bezeichnung =  getObject(id).common.name.substr(0, obj.common.name.indexOf(':'));

habe ich mir die Bezeichnung geholt. Über

var ID_Name = id.split('.')[2];

Die ID. Derzeit ist bei den Alarmfeldern die ID eingetragen

**Comment by foxriver76** [comment]
Rega Version? Ein mal Rega neugestartet, seit die Alarmmeldungen angelegt wurden?

**Comment by foxriver76** [comment]
Nein, den REGA Adapter meine ich ;-)

**Comment by foxriver76** [comment]
Das Renaming passiert derzeit nur beim Neustart des Adapters oder eben bei Änderung des updated States. Ich schaue bei Zeit mal, dass das auch ohne Neustart der Instanz klappt. Derzeit: Alarm wird angelegt mit ID als Namen --> Rega startet neu --> Name wird geändert.

**Comment by Baenker** [comment]
Wer lesen kann. Sorry. Ich dachte wenn ich eine neue Version installiere wird automatisch neu gestartet?

Version: 2.2.0 und RPC1.9.4 also überall Latest.

Habe vorsorglich Beide Adapter mal gestoppt und neu gestartet. Danach finde ich im Log auch:

	info	renamed hm-rpc.0.LEQ0888171.0.CONFIG_PENDING_ALARM to "Gäste WC Fenster:0.CONFIG_PENDING_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.0.LOWBAT_ALARM to "Gäste WC Fenster:0.LOWBAT_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.0.STICKY_UNREACH_ALARM to "Gäste WC Fenster:0.STICKY_UNREACH_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.0.UNREACH_ALARM to "Gäste WC Fenster:0.UNREACH_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.1.ERROR-1_ALARM to "Gäste WC Fenster:1.ERROR-1_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.1.ERROR-2_ALARM to "Gäste WC Fenster:1.ERROR-2_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.1.ERROR-3_ALARM to "Gäste WC Fenster:1.ERROR-3_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.1.ERROR-4_ALARM to "Gäste WC Fenster:1.ERROR-4_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.1.ERROR-5_ALARM to "Gäste WC Fenster:1.ERROR-5_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.1.ERROR-6_ALARM to "Gäste WC Fenster:1.ERROR-6_ALARM"
	info	renamed hm-rpc.0.LEQ0888171.1.ERROR-7_ALARM to "Gäste WC Fenster:1.ERROR-7_ALARM"

Nur ändert sich nichts im Objekte-Reiter.

**Comment by foxriver76** [comment]
Und bei einem erneuten Neustart des REGA Adapters tauchen dann wieder die Log Meldungen auf?

**Comment by Baenker** [comment]
Hätte es eigentlich bejaht. Da ich ähnliche renaiming sachen schon oft nach Neustarts gesehen hatte.

Diesmal aber nicht. Dafür sind nach nach dem erneuten Neustart die Namen nun geändert worden. Somit schließe ich hier, da es kein Fehler vom Adapter ist. Danke für die Unterstützung

**Comment by Baenker** [comment]
Sorry wollte schlißen

**Comment by foxriver76** [comment]
Zukünftig werden die Alarmzustände sofort mit dem korrekten Namen angelegt. Sprich der Restart der Instanz ist nicht mehr nötig.
