### ISSUE TITLE
Anzeige der Maintenance-Meldungen , obwohl in CCU ausgeblendet.

### ISSUE THREAD

**Issue by mameier1234** [ioBroker/ioBroker.hm-rega#54]
In der CCU kann man ja einstellen, dass man Fehlermeldungen , die sich von selbst erledigt haben, automatisch in der CCU bestätgigen kann. Laut JensMaus (Rasperymatic) werden die aber nur ausgeblendet...

Im IO-Broker bleibt der Datenpunkt "Maintenance" so lange auf Fehler, bis in der CCU einmal in die Fehler gegangen wird, obwohl da keine mehr sind...

aus dem HomematikForum:

Das kann passieren, denn in neueren RaspberryMatic Versionen existiert ja die Möglichkeit Servicemeldungen in der WebUI zu "verstecken". D.h. man kann ja je gerät sagen ob man service Meldungen haben will oder nicht und dann zeigt die WebUI die Servicemeldungen entweder an oder nicht. Dieses Feature nutzt jedoch einen Umstand in der WebUI bzw. ReGaHss aus bei der ServiceMeldungen als "enabled" oder "disabled" markiert werden können. Die Methode die dann die aktuellen Servicemeldungen darstellt wertet dann diese Flags aus und zeigt sie entweder an oder nicht. Nun kann es aber sein (und pocketControl hatte das am Anfang z.B. auch), das externe Applikationen diese Abfrage nach angeschalteten/abgeschalteten Servicemeldungen (noch) nicht implementiert haben und daher diese dann trotzdem alle Servicemeldungen auflisten lassen auch wenn teile davon eigentlich deaktiviert sind.

Für die die sich mit ReGa-Skripting auskennen (und für Entwickler externer Anwenden) muss das z.B. so aussehen:

`var servs = dom.GetObject(ID_SERVICES);
string id;
foreach(id, servs.EnumIDs())
{
  var r=dom.GetObject(id);
  if(r)
  {
    if(r.IsTypeOf(OT_ALARMDP) && (r.Used() == true) && (r.Enabled() == true) && (r.AlState() == asOncoming))
    {
      WriteLine("ServiceMeldung: " # r.Name() # "." # r.ID() # "." # r.Timestamp().ToInteger() # "." # r.AlOccurrenceTime().ToInteger() # "." # r.AlCounter());
    }
  }
}`

**Comment by foxriver76** [comment]
Könntest du mal die Version von GitHub testen (Upload nicht vergessen) und Feedback geben :-)

**Comment by mameier1234** [comment]
Gerade getestet... das selbe wie vorher.. habe an einem Thermostat ne Batterie rausgemacht... Maintenance geht erwartungsgemäß auf 1, in der CCU : Servicemeldung 1, dann Batterie wieder rein.. CCU: Servicemeldung 0, Maintenance bleibt auf 1.. Dann einmal in der CCU die Servicemeldungen aufgerufen: Hinweis, dass es keine Servicemeldungen gibt und innerhalb der Pollingzeit des RegaAdapter geht der MaintenanceDatenpunkt sofort wieder auf 0....

**Comment by foxriver76** [comment]
Kann das nicht nachstellen. Upload gemacht?

**Comment by mameier1234** [comment]
ja . 2.2.2 installiert...

**Comment by foxriver76** [comment]
Mach mal auf der Konsole 
iobroker upload hm-rega
Und dann starte den Adapter neu und dann probier es bitte nochmal.

**Comment by mameier1234** [comment]
Jetzt hat es geklappt ... Obwohl ich den Upload vorher aus der Oberfläche gemacht hatte . Super !
