### ISSUE TITLE
Fehler beim Update

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.hm-rega#55]
Bin gerade von der 2.2.1 auf die 2.30 gegangen. Folgende zwei Fehler fand ich danach im log. Weiß nicht ob es problematisch ist. Falls nicht issue einfach schließen.

hm-rega.0	2019-02-08 20:25:21.563	info	subscribe hm-rpc.0.BidCoS-RF.50.PRESS_SHORT
hm-rega.0	2019-02-08 20:25:21.482	info	starting. Version 2.3.0 in /opt/iobroker/node_modules/iobroker.hm-rega, node: v6.14.0
host.iobroker	2019-02-08 20:25:20.340	info	instance system.adapter.hm-rega.0 started with pid 17376
iobroker	2019-02-08 20:25:18.051	info	exit 0
iobroker	2019-02-08 20:25:18.041	info	Adapter "hm-rega" updated
iobroker	2019-02-08 20:25:17.982	info	upload [0] hm-rega.admin /opt/iobroker/node_modules/iobroker.hm-rega/admin/homematic.png homematic.png image/png
iobroker	2019-02-08 20:25:17.925	info	upload [1] hm-rega.admin /opt/iobroker/node_modules/iobroker.hm-rega/admin/index.html index.html text/html
host.iobroker	2019-02-08 20:25:17.870	info	instance system.adapter.hm-rega.0 terminated with code 0 (OK)
hm-rega.0	2019-02-08 20:25:17.836	info	terminating
iobroker	2019-02-08 20:25:17.834	info	upload [2] hm-rega.admin /opt/iobroker/node_modules/iobroker.hm-rega/admin/index_m.html index_m.html text/html
host.iobroker	2019-02-08 20:25:17.815	info	stopInstance system.adapter.hm-rega.0 killing pid 11108
host.iobroker	2019-02-08 20:25:17.815	info	stopInstance system.adapter.hm-rega.0
host.iobroker	2019-02-08 20:25:17.814	info	object change system.adapter.hm-rega.0
iobroker	2019-02-08 20:25:17.797	info	Update "system.adapter.hm-rega.0"
iobroker	2019-02-08 20:25:17.746	info	upload [3] hm-rega.admin /opt/iobroker/node_modules/iobroker.hm-rega/admin/words.js words.js application/javascript
iobroker	2019-02-08 20:25:17.709	info	got /opt/iobroker/node_modules/iobroker.hm-rega/admin
iobroker	2019-02-08 20:25:11.368	info	npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.hm-rega"
hm-rega.0	2019-02-08 20:25:00.467	error	runScriptFile Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.hm-rega/lib/../regascripts/programs.fn'
hm-rega.0	2019-02-08 20:25:00.463	error	runScriptFile Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.hm-rega/lib/../regascripts/polling.fn'
iobroker	2019-02-08 20:24:15.813	info	npm install iobroker.hm-rega@2.3.0 --production --prefix "/opt/iobroker" (System call)
iobroker	2019-02-08 20:24:15.811	info	Update hm-rega from @2.2.1 to @2.3.0
iobroker	2019-02-08 20:24:14.436	info	upgrade hm-rega

**Comment by foxriver76** [comment]
Kam die Fehlermeldung nur während des Updates oder jetzt weiterhin?

**Comment by Baenker** [comment]
Nur beim update

**Comment by foxriver76** [comment]
Wenn die Instanz während dem Update lief, und die Dateien neu angelegt wurden durch npm, kann es durchaus dazu kommen. Insofern sollte alles passen, trotzdem danke fürs melden.
