### ISSUE TITLE
Zeilenumbruch im Log bei Abfrage auf Versions-Objekt

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.hm-rega#57]
Das Objekt Version der CCU scheint mehr als nur Zahlen und Punkte zu enthalten?

Mit folgende Script:

`var logging = true;
var debugging = false;

//Datenpunkt auswählen wo die installierte Version ersichtlich ist (aus Homematic.Rega Adapter)
var id_Version_installiert = "hm-rega.0.MEQ0228930.0.FIRMWARE_VERSION"/*hm-rega.0.MEQ0228930.0.FIRMWARE_VERSION*/;

function test() {
    var Version_installiert = getState(id_Version_installiert).val;
       
    if(logging){
        log('Version ist nicht aktuell. Installiert: ' +Version_installiert +' Zeilenumbruch warum? ');
    }
            

}

test();`

erhalte ich folgendes Log:

`

javascript.0	2019-03-07 21:11:01.332	info	script.js.Test.Test_Abfrage: registered 0 subscriptions and 0 schedules
javascript.0	2019-03-07 21:11:01.332	info	Zeilenumbruch warum?
javascript.0	2019-03-07 21:11:01.332	info	
javascript.0	2019-03-07 21:11:01.332	info	script.js.Test.Test_Abfrage: Version ist nicht aktuell. Installiert: 2.41.5
javascript.0	2019-03-07 21:11:01.314	info	Start javascript script.js.Test.Test_Abfrage
`

**Versions:**
 - hm-rpc version: <1.98>
 - hm-rega version: <2.30>
 
 - CCU model: <CCU 2>
 - CCU firmware: <2.41.5>

**Comment by foxriver76** [comment]
Stimmt
