### ISSUE TITLE
Weitere Infos unter CCU-Name

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.hm-rega#59]
Derzeit gibt es unter unter den Objekten den Punkt CCU(Name). Darunter wird z. B. auf Wunsch der DutyCycle geschrieben oder die Firmware-Version.
Ich fände es gut wenn dort noch einige weitere Daten hinzukommen könnten.
In HM-Script kann man folgende Daten relativ einfach abfragen:

WriteLine("Version: " # dom.Version());
WriteLine("ReGaHss-Version: " # dom.BuildLabel());
WriteLine("Anzahl Geräte: " # (dom.GetObject(ID_DEVICES)).Count());
WriteLine("Anzahl Kanäle: " # dom.GetObject(ID_CHANNELS).Count());
WriteLine("Anzahl Datenpunkte: " # dom.GetObject(ID_DATAPOINTS).Count());
WriteLine("Anzahl SysVars: " # dom.GetObject(ID_SYSTEM_VARIABLES).Count());
WriteLine("Anzahl Programme: " # dom.GetObject(ID_PROGRAMS).Count());

Gerade die Rega-Version ist teilweise wichtig zu wissen. Die Anderen Punkte wie Anzahl Geräte, Kanäle, Datenpunkt usw finde ich aber auch durchaus interessant und würde mir wünschen wenn die Daten eben auch dort gepflegt würden.

**Comment by foxriver76** [comment]
Würde sich anbieten, diese systemspezifischen Info mit ins DutyCycle Skript zu packen.

**Comment by foxriver76** [comment]
![Bildschirmfoto von 2019-04-05 23-23-14](https://user-images.githubusercontent.com/25484431/55657325-2e324e00-57fa-11e9-8b4d-18a239ab62d8.png)

**Comment by Baenker** [comment]
Wau. Das ging ja schnell. Vielen Dank. Habe es bei mir getestet sieht gut aus.
