### ISSUE TITLE
simple-api liefert Timestamp als String

### ISSUE THREAD

**Issue by patman15** [ioBroker/ioBroker.hm-rega#60]
**Describe the bug**
Seit der Version 2.1.6 hab ich das Phänomen, dass Timestamps von gewissen Werten von hm-rega via der simple-api als Text statt als Integer geliefert werden. Zum Beispiel liefert
`http://iobroker.lan:8082/getBulk/hm-rega.0.9308,hm-rega.0.18871,hm-rega.0.9307,hm-rega.0.11776,hm-rega.0.9071,...`
den vierten Wert als Text.
```
[{"val": 7.319, "ts": 1553901206265},
 {"val": 568, "ts": 1553900613850},
 {"val": 3.770225,"ts": 1553901206262},
 {"val": 2.1,  "ts": "2019-03-30 00:00:01"},
 {"val": true,  "ts": 1553901206258},...
```

Ich habe mit sonst gleichem Setup verschiedenste hm-rega Versionen ausprobiert und es tritt erst ab 2.1.6 auf, während 2.1.3 nicht betroffen ist. Deswegen glaube ich auch, dass es am hm-rega und nicht am simple-api oder sonst was liegt. Habe mehrfach zwischen 2.1.3 und 2.1.6 bzw. 2.3.2 gewechselt und jeweils 2.1.3 hat funktioniert und die anderen nicht.

Siehe auch: https://forum.iobroker.net/topic/21423/hm-rega-simple-api-timestamp-als-string

Ich verwende die interne API des web-adapters, aber auch ein separat installierter simple-api Adapter hat den Fehler gezeigt. Interessanter Weise ist das `/get/` Kommando im Gegensatz zu `/getBulk/`nicht betroffen.

Hab mir die Änderungen im Code zwischen 2.1.3 und 2.1.6 angeschaut, aber leider ist mir nichts aufgefallen. Bitte daher um Unterstützung bzw. Info, wenn zur Analyse noch etwas benötigt wird.

**Expected behavior**
Alle Werte als Integer in Millisekunden

**Versions:**
 - hm-rpc version: 1.9.9
 - hm-rega version: 2.3.2 (da ist es aufgefallen) 2.1.6+ ist betroffen
 - JS-Controller version: 1.4.2
 - Node version: 8.10.0
 - Operating system: Ubuntu 18.04.2 LTS (GNU/Linux 3.16.63-37 aarch6
 - CCU model: CCU2
 - CCU firmware:  2.35.16

**Comment by foxriver76** [comment]
Vor 2.1.6, gab es das Verhalten, welches in https://github.com/ioBroker/ioBroker.hm-rega/issues/45 beschrieben ist. Nun wird so ein Update mitgeteilt. Das ist die Anpassung, die Probleme macht: https://github.com/ioBroker/ioBroker.hm-rega/issues/45

Kann das zeitnah fixen.

**Comment by foxriver76** [comment]
Teste mal bitte von GitHub + Upload

**Comment by patman15** [comment]
@foxriver76 vielen Dank für den raschen fix, v2.3.3 funktioniert wieder.
