### ISSUE TITLE
Synchronize groups

### ISSUE THREAD

**Issue by alekob** [ioBroker/ioBroker.hm-rega#61]
**Is your feature request related to a problem? Please describe.**
Group devices (e.g. group of thermostat's) is not synchronized. Therefore it is not possible to control such a group of devices

**Describe the solution you'd like**
Sync groups to enum.groups

**Comment by foxriver76** [comment]
It is possible to control auch a group and it is called virtual devices. You need a separat hm rpc instance for this and have to configure Rega for this instance too.
