### ISSUE TITLE
seit CCU-2 Update auf v2.47.10 Probleme beim aktualisieren von Systemvariablen

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.hm-rega#63]
es gab heute ein Firmwareupdate für die CCU-2 auf v.2.47.10

Seit dem Einspielen scheint es Probleme mit dem hn-rega Adapter zu geben.
Die Systemvariablen auf der CCU-2 werden nicht mehr aktualisiert.

Folgende LOG-Einträge finde ich hierzu:
`hm-rega.0	2019-06-25 23:35:34.334	warn	Got unexpected ID: hm-rega.0.5111
hm-rega.0	2019-06-25 23:35:22.824	warn	Got unexpected ID: hm-rega.0.11620
hm-rega.0	2019-06-25 23:48:15.063	error	Cannot parse answer for favorites:
hm-rega.0	2019-06-25 23:48:15.063	error	"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\
hm-rega.0	2019-06-25 23:48:15.063	error	<-- invalid response:
hm-rega.0	2019-06-25 23:48:15.058	error	"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\
hm-rega.0	2019-06-25 23:48:15.058	error	<-- invalid response:`

**Comment by foxriver76** [comment]
Bitte mal debug log einschalten und ab Instanzstart posten und zwar von der Log herunterladen Seite o. Platte, da sonst angeschnitten. Anscheinend wurde etwas an der Struktur des XML Dokumenta geändert, das als Antwort kommt.

**Comment by foxriver76** [comment]
Log Inn Forum sagt, dass 403 Forbidden zurück kommt.

**Comment by foxriver76** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=26&t=51396
Problem betrifft auch andere Plugins und ich gehe aktuell davon aus, dass es ein Bug seitens eq3 ist und keine gewollte Änderung.

**Comment by foxriver76** [comment]
Seitens eq3 wurde eine neue Firmware released die Usern zufolge das Problem löst.

**Comment by BramTown** [comment]
@foxriver76  - Danke, das löst das Problem !
