### ISSUE TITLE
Access to invisble system variables

### ISSUE THREAD

**Issue by drtp** [ioBroker/ioBroker.hm-rega#65]
Currently, the hm-rega adapter has only access to visible system variables of the CCU. It seems, it only seeks for EnumUsedIDs. Would it be possible to include a switch that it also can scan for EnumIDs in order to additionally find the invisible system variables? 

This would be very helpful for some internally created system variables like those of the HMIP weather sensors, e.g. the system variable for the daily rain counter.

Best regards,

Thorsten

**Comment by foxriver76** [comment]
API does not provide this information, because these variables are 'invisible' from the outside. ;-)
If you think that should be the case (I don't think so), you should open an issue at https://github.com/eq-3/occu

**Comment by Baenker** [comment]
@foxriver76 bist Du Dir sicher? In der App "PocketControl" kann ich auch die versteckten Systemvariablen sehen ... Da die App ja auch extern ist sollte es doch mit ioBroker auch irgendwie möglich sein?

In PocketControl gibt es dazu unter Einstellungen eine Option "Zeige interne Systemvariablen"

**Comment by foxriver76** [comment]
No, schaue es mir an, deshalb Comment gelöscht.

**Comment by Baenker** [comment]
Noch ein Hinweis:

In der Datei regascripts/variables.fn wird abgefragt mit:

foreach (sSysVarId, dom.GetObject(ID_SYSTEM_VARIABLES).EnumUsedIDs()) {

"Black" aus den Homematic Forum hatte dort im Forum folgendes geschrieben:

"Es kommt dauf an, wie die Systemvariablen abgefragt werden. EnumUsedIDs oder EnumIDs.. EnumIDs liefert dir dann alle."

Ich vermute also wenn dort die Zeile geändert wird in:

foreach (sSysVarId, dom.GetObject(ID_SYSTEM_VARIABLES).EnumIDs()) {

könnte es schon funktionieren. Das würde aber dazu führen das dann alle versteckten Systemvariablen sichtbar sind!? Ob das gut ist kann ich nicht beurteilen. Gerade für Einsteiger wahrscheinlich schwierig.

Aber die versteckten für die Wetterstation sind natürlich schon nicht uninteressant. Anderseits bei mir sind fast alle von den Zwischensteckern. Da finde ich es nicht tragisch wenn man die sieht.

**Comment by foxriver76** [comment]
Bekommt ihr mit diesem Skript auch eure unsichtbaren? 

```
!# variables.fn 1.5
!#
!# Dieses Script gibt die Systemvariablen als JSON String aus
!#
!# 3'2013-6'2014 hobbyquaker https://github.com/hobbyquaker
!#

object oSysVar;
string sSysVarId;
string sValueType;
string sValue;
boolean bFirst = true;

Write('{');

!# due to the fact that service messages can be automatically acknowledged, we have to loop over all and check
var servs = dom.GetObject(ID_SERVICES);
string id;
integer serviceMessages = 0;

foreach(id, servs.EnumIDs())
{
  var service = dom.GetObject(id);
  if(service)
  {
    if(service.IsTypeOf(OT_ALARMDP) && (service.Used() == true) && (service.Enabled() == true) && (service.AlState() == asOncoming))
    {
      serviceMessages = serviceMessages + 1;
    }
  }
}

WriteLine('"40":{"Name":"Alarmmeldungen","TypeName":"VARDP","DPInfo":"Anzahl%20Alarmmeldungen","Value":' # serviceMessages # ',"ValueMin":0,"ValueMax":65000,"ValueUnit":"","ValueType":16,"ValueSubType":0,"ValueList":""},');
Write('"41":{"Name":"Servicemeldungen","TypeName":"VARDP","DPInfo":"Anzahl%20Servicemeldungen","Value":' # dom.GetObject(41).Value() # ',"ValueMin":0,"ValueMax":65000,"ValueUnit":"","ValueType":16,"ValueSubType":0,"ValueList":""}');

foreach (sSysVarId, dom.GetObject(ID_SYSTEM_VARIABLES).EnumIDs()) {

  WriteLine(',');

  
  oSysVar     = dom.GetObject(sSysVarId); 
  sValueType  = oSysVar.ValueType();
    
  Write('"' # sSysVarId # '":{"Name":"');
  WriteURL(oSysVar.Name());
  Write('","TypeName":"' # oSysVar.TypeName());
  Write('","DPInfo":"');
  WriteURL(oSysVar.DPInfo());

  Write('","Value":');
  if (sValueType == 20) {
    Write('"');
  	WriteURL(oSysVar.Value());
    Write('"');
  } else {
    sValue = oSysVar.Value();
    if (sValueType == 2) {
        if (sValue) {
            Write("true");
        } else {
            Write("false");
        }
    } else {
       if (sValue == "") {
            Write("0");
       } else {
            Write(sValue);
       }
    }
  }
  string sValueMin = oSysVar.ValueMin();

  if (sValueMin == '') {
      sValueMin = 'null';
  }

  string sValueMax = oSysVar.ValueMax();

  if (sValueMax == '') {
      sValueMax = 'null';
  }

  Write(',"Timestamp":"' # oSysVar.Timestamp());
  Write('","ValueMin":' # sValueMin # ',"ValueMax":' # sValueMax # ',"ValueUnit":"');
  WriteURL(oSysVar.ValueUnit());
  Write('","ValueType":' # sValueType # ',"ValueSubType":' # oSysVar.ValueSubType());
  
  if (sValueType == 2) {
    Write(',"ValueList":"');
    WriteURL(oSysVar.ValueName0() # ';' # oSysVar.ValueName1());
  } else {
    Write(',"ValueList":"');
    WriteURL(oSysVar.ValueList());
  }

  Write('"}');
  
}

Write('}');
```

**Comment by foxriver76** [comment]
Jop, probier mal bitte das Skript via "Skript testen" auf der CCU

**Comment by Baenker** [comment]
Kann ich derzeit leider nicht testen. Erst heute Abend. Aber noch eine Frage:

Oben wird ja schon darauf abgefragt:

foreach(id, servs.EnumIDs())
{
  var service = dom.GetObject(id);
  if(service)
  {
    if(service.IsTypeOf(OT_ALARMDP) && (service.Used() == true) && (service.Enabled() == true) && (service.AlState() == asOncoming))
    {
      serviceMessages = serviceMessages + 1;
    }
  }
}

Allerdings wird dann wieder auf bestimmte eingegrenzt. Ich vermute also das man so die Stystemvariabeln "Alarmmeldung" und "Servicemeldungen" doppelt bekommt!?

**Comment by foxriver76** [comment]
Nein, oben wird die Anzahl aktiver Servicemeldungen + Alarmmeldungen gezählt

**Comment by foxriver76** [comment]
Bitte Feedback geben obs läuft, wenn Variablen Sync aktiviert ist, gibt es eine Checkbox um auch unsichtbare Variablen zu syncen.

**Comment by Baenker** [comment]
Gemach gemach. Bin gerade erst nach Hause gekommen. Ich melde mich in den nächsten zwei Stunden....

**Comment by Baenker** [comment]
Bei mir tauchen wie erwartet alle Variablen auf. Tendenziell halte ich die Checkbox für eine gute Lösung. Aber ich befürchte das dann viele Anfänger nie die Wetterdaten finden weil Sie nicht auf die Idee kommen das man dazu die versteckten Variablen abfragen sollte. Zu dem Thema gab ja auch schon einige Threads im Forum wenn ich mich nicht täusche. Ich wußte bis heute auch nicht das ich dort die Daten der Messsteckdose finde. Gut habe ich auch nie gebraucht oder vermisst :-)

Danke auf jeden Fall für Deinen Einsatz und das Du die Option einbaust.

**Comment by foxriver76** [comment]
Option wäre noch die Checkbox von Anfang an zu aktivieren. Was hälst du davon?

**Comment by foxriver76** [comment]
Klar kein Stress, hatte es nur schon eingebaut. Nach Installation von GitHub und Upload steht die Option zur Verfügung.

**Comment by Baenker** [comment]
Habe es installiert. Die versteckten sind nun da leider nicht mehr meine alten normalen Systemvariablen?

Wie ich schon schrieb generell schwierig. Für die, die es nicht brauchen wäre die Option besser das es nicht aktiviert ist. Wer sind die Nutzer von ioBroker? Mehrheitlich Anfänger die es nicht wissen oder mehrheitlich erfahrene Nutzer? Ich kann es nicht beurteilen. Ich glaube ich würde die Checkbox aktiv setzen. Stören tun die Systemvariablen ja eigentlich auch nicht...

**Comment by Baenker** [comment]
Ok alles wieder da. Adapter stoppen und wieder starten.

Die nächste Frage wäre ja eigentlich auch was macht man bei den Programmen? Auch dort gibt es ja interne Programme? Ich vermute dort könnte die Abfrage auch umgestellt werden. Aber ist das wirklich sinnvoll? 
Und bei den Systemvariablen wird sich eq3 ja evtl auch etwas dabei gedacht haben diese nicht anzuzeigen? Von daher wäre es evtll dann doch sinnvoller die Checkbox nicht aktiv zu haben und nur User die wissen was Sie tun können die Checkbox aktivieren? Irgendwie gar nicht so einfach...

**Comment by foxriver76** [comment]
Ich kann es leider auch schwer einschätzen, da ich die CCU tatsächlich nur zur Kommunikation nutze und um Geräte zu verwalten. Habe dort keine Programme/SysVars, die ich aktiv nutze.

**Comment by Baenker** [comment]
So ist es bei mir eigentlich auch. Ich habe noch ein paar alte Systemvariablen die ich eigentlich nicht mehr brauche und nutze. Programme habe ich nur ein paar Dummy Programme damit z. B. Tasten in ioBroker funktionieren. Die versteckten Systemvariablen für die Messsteckdose wo der summierte Verbrauch gespeichert wird sind für mich nicht interessant aber da wird es bestimmt einige geben die diese Systemvariablen nutzen würden. Dafür gäbe es aber ja auch alternative Adapter. Spannend fände ich die Option nur für die Wetterstation bzw dort der summierte Regen vom Tag.

Also eigentlich ist es dann einfach. Die Checkbox ist per default nicht aktiv. Du brauchst es nicht. Ich brauche es nicht. Und zig tausend Installationen vorher haben es nie vermisst. Es gab nur vereinzelt  nachfragen. Man könnte ja noch einen Hinweis in der Readme machen das man mit der Option eben z. B. die Daten von Messsteckdosen bzw Wetterstationen bekommen kann sofern man die braucht.

**Comment by drtp** [comment]
Vielen Dank für die schnelle Umsetzung dieses Features mit Version 2.4.0.

Gruß,

Thorsten

**Comment by foxriver76** [comment]
@drtp Gerne. 
@Baenker Habe es jetzt so gemacht, denke auch dass es so am sinnvollsten ist, vielen Dank für deine Meinung.
