### ISSUE TITLE
Versteckte Variablen aktualisieren sicht nicht automatisch

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.hm-rega#66]
Die Werte der Wetterstation in der CCU von heute Morgen:

![2019-07-13 07_49_32-Window](https://user-images.githubusercontent.com/205119/61167733-2c87cd00-a543-11e9-8343-173fbdf19bab.png)

Zur selben Zeit im ioBroker:
![2019-07-13 07_49_24-Window](https://user-images.githubusercontent.com/205119/61167742-3e697000-a543-11e9-9461-f48f9b5e45ec.png)

Im ioBroker nach einem Neustart von hm-rega.0:
![2019-07-13 07_50_34-Window](https://user-images.githubusercontent.com/205119/61167746-47f2d800-a543-11e9-81c4-0861e2c4f8ad.png)

**Versions:**
 - hm-rpc version: 1.9.15
 - hm-rega version: 2.4.0
 - JS-Controller version: 1.5.12
 - Node version: 8.16.0
 - NPM: 6.4.1
 - Operating system: iobroker @docker
 - CCU model: raspberrymatic
 - CCU firmware: 3.45.7.20190622

**Comment by foxriver76** [comment]
Bitte 2.4.1 probieren
