### ISSUE TITLE
Keine korrekte Syncronisierung von Gewerk und Raum nach Änderung

### ISSUE THREAD

**Issue by intruder7777** [ioBroker/ioBroker.hm-rega#69]
Nach Änderung der Gewerk und Raumzuordnung in der CCU erfolgt keine korrekte Syncronisierung in ioBroker.
Ablauf
- Änderung der Zurdnung auf der CCU
![2](https://user-images.githubusercontent.com/45670139/62155770-08313c00-b30a-11e9-9d32-b127c5904350.png)

- REGA und RPC Adapter deaktiviert
- Gerät (Objekt) in ioBroker gelöscht
- REGA und RPC Adapter mit erneuter Syncronisierung gestartet
danach wurde das Gerät (Object) mit den alten Zuordnungen angelegt
![1](https://user-images.githubusercontent.com/45670139/62155938-51818b80-b30a-11e9-816a-ffb0ae677819.PNG)
Ergänzung:
Unter Aufzählungen blieben die Nummern (ich denke die alten Channels) nach dem Löschen des Gerätes übrig. Bei Rübergehen mit dem Mauszeiger wurde die SNr. des gelöschten Gerätes angezeigt.
![3](https://user-images.githubusercontent.com/45670139/62156271-f2704680-b30a-11e9-949a-f564f7156753.PNG)

**Comment by foxriver76** [comment]
Test 1: 
1. Ein neuen Kanal in CCU zu einem Gewerk hinzufügen
2. hm-rega neustarten
3. In Aufzählungen prüfen ob hinzugefügt
4. funktioniert!

Test 2:
1. Einen Kanal aus einem Gewerk in CCU entfernen
2. hm-rega neustarten
3. In Aufzählungen prüfen ob entfernt
4. Funktioniert nicht!

**Comment by foxriver76** [comment]
Sobald jemand folgende Tests positiv bestätigen kann, wäre das hier und vermutlich auch #34 gefixt: [Zu den Tests](https://forum.iobroker.net/topic/24164/aufruf-hm-rega-enum-sync-testen)

**Comment by intruder7777** [comment]
![image](https://user-images.githubusercontent.com/45670139/62206975-37d85680-b393-11e9-97ab-9bb9d2aae636.png)
hab jetzt das Änndern in der CCU nochmal durchgeführt. Jetzt habe ich aber alle Raum und Gewerkezuordnungen geköscht. ioBroker RPC und REGA angehalten, Gerät gelöscht und unter Aufzählungen blieben die Kanalnummern übrig. Nach Aktivierung der Adapter waren die alten ENUM Zuordnungen wieder da.

**Comment by intruder7777** [comment]
Eigentlich müssten doch mit Löschen der Objekte auch die Zuordnungen zu den ENUMS entfernt werden. Dies wiederum wäre wohl ein Fehler im Admin. Allerdings müsste REGA auch die neuen Einstellungen aus der CCU übernehmen.

**Comment by foxriver76** [comment]
Wenn du die Objekte in ioBroke löschst, wird die Zuordnung nicht gelöscht wegen dem js-c issue. Jedoch sollte jede Änderung aus der CCU nun korrekt synchronisiert werden. Sprich löschst du ein Gerät aus einem enum auf der CCU wird dies nach einem rega Neustart auch in ioBroker aus der enum gelöscht. Gleiches mit hinzufügen (das hat allerdings vorher schon du funktioniert). Also ist dein offenes Problem nur noch, dass die Zuordnung ID zu Enum bei löschen des Objektes nicht gelöscht wird? Oder ist sonst noch was offen diesbezüglich?

**Comment by intruder7777** [comment]
"....Sprich löschst du ein Gerät aus einem enum auf der CCU wird dies nach einem rega Neustart auch in ioBroker aus der enum ...." genau das passiert ja eben nicht. aber egal....

**Comment by foxriver76** [comment]
Ne nicht egal. Bist du auf der Version 2.3.__4__?

**Comment by intruder7777** [comment]
Sogar schon weiter.... 2.4.3

**Comment by foxriver76** [comment]
Sorry Zahlendreher, meinte auch 2.4.3.

Und du tust es wie folgt? Welcher Fall von denen ist es genau, dann schaue ich bei mir nochmal.

### Test 1: Gerät aus Enum Rooms entfernen
1. In CCU einen Kanal aus einem Raum entfernen
2. hm-rega neustarten
3. Prüfen ob im Log auf Info Level geloggt wird, dass das Gerät aus Enum Rooms entfernt wurde
4. Unter Tab Aufzählungen prüfen, dass das Gerät aus der Enum entfernt wurde

### Test 2: Gerät aus Enum Favorites entfernen
1. In CCU einen Kanal aus den Favoriten für einen User entfernen
2. hm-rega neustarten
3. Prüfen ob im Log auf Info Level geloggt wird, dass die Anzahl (bitte auch mal mit mehreren probieren) an gelöschten Favoriten aus den Favoriten entfernt wurde (mit Angabe des korrekten Nutzernamens)
4. Unter Tab Aufzählungen prüfen, dass das Gerät aus der Enum entfernt wurde


### Test 3: Gerät aus Enum Functions entfernen
1. In CCU einen Kanal aus einer Functions Enum entfernen
2. hm-rega neustarten
3. Prüfen ob im Log auf Info Level geloggt wird, dass das Gerät aus Enum Functions entfernt wurde
4. Unter Tab Aufzählungen prüfen, dass das Gerät aus der Enum entfernt wurde

**Comment by intruder7777** [comment]
jetzt nochmal mit bildlicher Doku
im folgenden Bild ist der Kanal 7 noch vorhanden in der CCU unter Räume. Ich werde ihn dort löschen
![100](https://user-images.githubusercontent.com/45670139/62354078-59a91900-b50c-11e9-900c-81ffcc9aede5.png)
hier noch der Stand wie es unter Objekte im ioBroker aussieht
![102](https://user-images.githubusercontent.com/45670139/62354144-7cd3c880-b50c-11e9-8fb7-6d77f30186e6.png)
jetzt sieht man dass Kanal 7 gelöscht wurde aus dem Raum
![101](https://user-images.githubusercontent.com/45670139/62354181-937a1f80-b50c-11e9-9c94-1c3e21e5aab5.png)
REGA Adapter wurde neu gestartet und unter Objekte hat sich nichts verändert. Auch unter Aufzählungen ist der Kanal 7 weiterhin in diesem Raum vorhanden

**Comment by intruder7777** [comment]
also in dem Fall Punkt 1. im Log stand dieses
`

hm-rega.0 | 2019-08-02 09:03:58.572 | info | got state values
-- | -- | -- | --
hm-rega.0 | 2019-08-02 09:03:57.653 | info | request state values
hm-rega.0 | 2019-08-02 09:03:57.651 | info | added/updated 1 objects
hm-rega.0 | 2019-08-02 09:03:57.294 | info | deleted 0 variables
hm-rega.0 | 2019-08-02 09:03:57.293 | info | added/updated 58 variables
hm-rega.0 | 2019-08-02 09:03:57.157 | info | got 58 variables
hm-rega.0 | 2019-08-02 09:03:56.747 | info | deleted 0 programs
hm-rega.0 | 2019-08-02 09:03:56.747 | info | added/updated 13 programs
hm-rega.0 | 2019-08-02 09:03:56.689 | info | got 13 programs
hm-rega.0 | 2019-08-02 09:03:55.019 | info | nothing to update on rooms (enum.rooms)
hm-rega.0 | 2019-08-02 09:03:55.016 | info | nothing to update on functions (enum.functions)
hm-rega.0 | 2019-08-02 09:03:55.013 | info | nothing to update on favorites (enum.favorites) for Admin
hm-rega.0 | 2019-08-02 09:03:52.485 | info | no favorites found (enum.favorites) for backup
hm-rega.0 | 2019-08-02 09:03:52.454 | info | time difference local-ccu 0s
hm-rega.0 | 2019-08-02 09:03:52.375 | info | ReGaHSS 192.168.100.80 up
hm-rega.0 | 2019-08-02 09:03:52.253 | info | subscribe hm-rpc.1.BidCoS-RF.50.PRESS_SHORT
hm-rega.0 | 2019-08-02 09:03:50.490 | info | starting. Version 2.4.3 in /opt/iobroker/node_modules/iobroker.hm-rega, node: v10.16.0

`

**Comment by foxriver76** [comment]
Stimmt, da hat was nicht gepasst. Installiere mal bitte von GitHub

**Comment by foxriver76** [comment]
Damit unter Objekte die Änderung der Enums sichtbar wird, muss oben der aktualisieren Button gedrückt werden oder die Seite neu geladen werden

**Comment by foxriver76** [comment]
Änderung der Enums sollte nun auch detailliert geloggt werden beim Start von rega

**Comment by intruder7777** [comment]
so, nochmal probiert. hab jetzt nicht extra was geändert in der ccu. den Kanal 7 aus obigen Beispiel habe ich so gelassen. 
im Log erkennt er auch alles richtig nur unter Objekte und Aufzählungen tut sich nichts. Hab auch aktualisiert.
![103](https://user-images.githubusercontent.com/45670139/62374135-89bbe080-b53b-11e9-939e-fcb3783d642d.png)

**Comment by intruder7777** [comment]
hier ....D076.7 ist zu sehen dass es von Aussenbeleuchtung removed wurde. aber eben bloß im LOG. Sonst nicht

**Comment by foxriver76** [comment]
Kann es leider nicht nachstellen - hier mal als Video, evtl. erkennst du, was du anders machst:
https://wetransfer.com/downloads/f70e4192c770c70b2cf713740507aea720190802151307/58014a0cef518ff9da8c430e0c8518e120190802151307/9ebb55
