### ISSUE TITLE
After update to CCU2 firmware 2.47.20 alarams and service message have the same value

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.hm-rega#72]
After upgrading the CCU2 firmware to version 2.47.20 the variables for alarms are the same as for service messages. i.e. if I have 2 services messages on the CCU2 and 0 alarams, then in ioBroker there are 2 alarams and 2 service messages. If the services message on CCU2 decreases the alarms counter ist set to 1 in ioBroker (same as services messages).
Also deleting the whole hm-rega.0 objects and restart the hm-rega adapter did not solve the problem.

**Comment by modmax** [comment]
After set to debug-level the hm-rega deliveried following messages:
`
2019-09-25 18:47:06.700 - debug: hm-rega.0 --> variables.fn
2019-09-25 18:47:06.702 - debug: hm-rega.0 --> !# variables.fn 1.5 !# !# Dieses Script gibt die Systemvariablen als JSON String
2019-09-25 18:47:07.015 - debug: hm-rega.0 <-- {"40":{"Name":"Alarmmeldungen","TypeName":"VARDP","DPInfo":"Anzahl%20Alarmmeldungen","Value":1,"ValueMin":0,"ValueMax":65000,"ValueUnit":"","ValueType":16,"ValueSubType":0,"ValueList":""},
"41":{"Name":"Servicemeldungen","TypeName":"VARDP","DPInfo":"Anzahl%20Servicemeldungen","Value":1,"ValueMin":0,"ValueMax":65000,"ValueUnit":"","ValueType":16,"ValueSubType":0,"ValueList":""},
"950":{"Name":"CCU-Reboot","TypeName":"VARDP","DPInfo":"CCU%20wird%20rebootet","Value":false,"Timestamp":"2019-09-24 20:52:16","ValueMin":null,"ValueMax":null,"ValueUnit":"","ValueType":2,"ValueSubType":2,"ValueList":"nein%3Bja"}}
`
Perhaps there has something changed in the rega-Implementation ???

**Comment by foxriver76** [comment]
Thanks for reporting, should be fixed in 2.4.11
