### ISSUE TITLE
nach update auf 2.4.11 error: Cannot parse answer for variables:

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.hm-rega#73]
Habe die Version 2.4.11 installiert und bekomme im Log den Error: _Cannot parse answer for variables:_

mit debug gestartet:

hm-rega.0 | 2019-09-26 09:22:21.561 | error | (2068) Cannot parse answer for variables:
-- | -- | -- | --
hm-rega.0 | 2019-09-26 09:22:21.557 | debug | (2068) <--
hm-rega.0 | 2019-09-26 09:22:21.551 | debug | (2068) --> !# variables.fn 1.5 !# !# Dieses Script gibt die Systemvariablen als JSON String
hm-rega.0 | 2019-09-26 09:22:21.548 | debug | (2068) --> variables.fn

Node: v10.16.3
NPM:6.10.3
JS-Controller: 2.0.9

**Comment by MarkSau** [comment]
und etwas später

hm-rega.0 | 2019-09-26 09:27:03.278 | warn | (2207) Got unexpected ID: hm-rega.0.3964
-- | -- | -- | --

**Comment by foxriver76** [comment]
Jo, sehe schon den Fehler. Hatte nur variablesInv getestet, Fix kommt gleich

**Comment by MarkSau** [comment]
Klappt…super…danke
