### ISSUE TITLE
Keine Verbindung  'Pending request for more than 850000 ms'

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/ioBroker.hm-rega#76]
ich habe heute morgen keine Verbindung zur CCU trotz grünem Adapter.
Im Log hab ich folgendes gefunden:
```
2019-10-14 07:09:48.986 - warn: hm-rega.0 Pending request for more than 850000 ms
```
was kann das sein? Die Verbindung wurde erst nach einem manuellen neustarten des Adapters aufgenommen.

Gruß
Matten Matten

```
System:
tinkerboard
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1800 MHz
Modell: ARMv7 Processor rev 1 (v7l)
RAM: 1.96 GB
System Betriebszeit: 3 T. 23:06:10
Node.js: v10.16.3
NPM: 6.9.0
Festplatte Größe: 14.43 GB
Festplatte frei: 12.73 GB
Anzahl der Adapter: 256
Betriebszeit: 3 T. 21:49:49
Aktive Instanzen 22
```

**Comment by Matten-Matten** [comment]
Auf meiner zweiten ioBroker Installation  die auch mit der CCU verbunden ist, gab es keine Unterbrechung.

**Comment by foxriver76** [comment]
Müsste https://github.com/ioBroker/ioBroker.hm-rega/blob/80a6593460bf68f787bb2e0899774f2425efab54/lib/rega.js#L245 rein gehen und keine Skripte mehr ausführen, da wohl noch ein Request in Bearbeitung ist laut Adapter. Wurde wohl probiert ein Skript auszuführen vom Adapter, das end Event ist nie gekommen und somit steckt das ewig in der Queue und er führt für die gesamte Laufzeit keine Skripte mehr aus.

Ich werde da mal was einbauen, dass die Queue auch mal geleert wird wenn etwas zu lange drin ist.. auch wenn das Verhalten äußerst merkwürdig ist.

**Comment by foxriver76** [comment]
Es muss davor schon mal Meldungen gegeben haben. Kannst du mal den Anfang der Meldungen zeigen? Die erste warn Meldung muss `Pending request for more than 25000 ms` gewesen sein. Und davor evtl. eine Errormeldung a la `post request error: ...`?

**Comment by Matten-Matten** [comment]
Ich schaue bei Gelegenheit nach
