### ISSUE TITLE
Rega seit CCU2 Firmware Update auf 2.49.17 Gelb

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.hm-rega#80]
Hallo, 
seit einen neuen Update der CCU2 auf V 2.49.17 ist der Adapter Gelb.
Wird aber kurz Grün.
Der Rega wird auch nicht mehr in Discovery gefunden. 

Meine Adapter Version: 2.5.0

Log:

`

hm-rega.0 | 2019-12-10 14:14:58.299 | error | (11564) CCU 192.168.178.99 unreachable
-- | -- | -- | --
hm-rega.0 | 2019-12-10 14:14:58.298 | error | (11564) post request error: connect ECONNREFUSED 192.168.178.99:8181
hm-rega.0 | 2019-12-10 14:14:56.288 | debug | (11564) --> Write(system.Date("%F %X").ToTime().ToInteger());
hm-rega.0 | 2019-12-10 14:14:56.287 | info | (11564) ReGaHSS 192.168.178.99 up
hm-rega.0 | 2019-12-10 14:14:50.463 | error | (11564) Cannot parse answer for devices: undefined
hm-rega.0 | 2019-12-10 14:14:50.462 | debug | (11564) --> devices.fn
hm-rega.0 | 2019-12-10 14:14:26.160 | error | (11564) CCU 192.168.178.99 unreachable
hm-rega.0 | 2019-12-10 14:14:26.160 | error | (11564) post request error: connect ECONNREFUSED 192.168.178.99:8181
hm-rega.0 | 2019-12-10 14:14:24.128 | debug | (11564) --> Write(system.Date("%F %X").ToTime().ToInteger());
hm-rega.0 | 2019-12-10 14:14:24.128 | info | (11564) ReGaHSS 192.168.178.99 up
hm-rega.0 | 2019-12-10 14:13:53.986 | error | (11564) CCU 192.168.178.99 unreachable
hm-rega.0 | 2019-12-10 14:13:53.986 | error | (11564) post request error: connect ECONNREFUSED 192.168.178.99:8181

`

**Comment by foxriver76** [comment]
Kann im Changelog nichts diesbezüglich erkennen: https://www.eq-3.de/downloads/software/HM-CCU2-Firmware_Updates/HM-CCU-2.49.17/HM-CCU2-Changelog.2.49.17.pdf

Adapter Neustart probiert?

**Comment by Azathoth88** [comment]
Selbes Problem. Adapter & CCU neu gestartet.


hm-rega.0 | 2019-12-10 19:20:56.891 | error | (13361) CCU 192.168.178.23 unreachable
hm-rega.0 | 2019-12-10 19:20:56.890 | error | (13361) post request error: connect ECONNREFUSED 192.168.178.23:8181
hm-rega.0 | 2019-12-10   19:20:56.887 | debug | (13361)   --> Write(system.Date("%F %X").ToTime().ToInteger());

Die Firewall ist auf Vollzugriff gestellt.
https://i.imgur.com/xPeW5mc.png

**Comment by sigi2345** [comment]
> Ansonsten checke mal bitte die CCU Firewall, evtl wurden mit dem Update Einstellungen überschrieben,

Nein ist so wie die alten Einstellungen. Neustart, Neuinstallation, Fehler bleibt. 
Denke hat was mit Port 8181 zu tun, diese Angabe im Log hatte ich bis jetzt noch nie.
Irgendwas muss geändert worden sein.
Aufgefallen ist mir beim Einstieg in die WEB UI das jetzt die SID @XXXXXXXX sich immer ändert. Das war vorher nicht so.

**Comment by sigi2345** [comment]
> Selbes Problem. Adapter & CCU neu gestartet.

Auch auf 2.49.17 ?

**Comment by Azathoth88** [comment]
Meine Konstellation: REGA 2.5.0 & CCU 2.49.17

**Comment by foxriver76** [comment]
Rega 2.4.12 geht?

**Comment by sigi2345** [comment]
> Rega 2.4.12 geht?

Nein:

`

hm-rega.0 | 2019-12-10 20:03:50.886 | error | (7572) CCU 192.168.178.99 unreachable
-- | -- | -- | --
hm-rega.0 | 2019-12-10 20:03:50.886 | error | (7572) post request error: connect ECONNREFUSED 192.168.178.99:8181
hm-rega.0 | 2019-12-10 20:03:48.830 | debug | (7572) --> Write(system.Date("%F %X").ToTime().ToInteger());
hm-rega.0 | 2019-12-10 20:03:48.828 | info | (7572) ReGaHSS 192.168.178.99 up
hm-rega.0 | 2019-12-10 20:03:48.678 | info | (7572) subscribe hm-rpc.0.BidCoS-RF.50.PRESS_SHORT
hm-rega.0 | 2019-12-10 20:03:48.662 | info | (7572) starting. Version 2.4.12 in C:/Program Files/iobroker/Test/node_modules/iobroker.hm-rega, node: v10.16.3
hm-rega.0 | 2019-12-10 20:03:48.542 | debug | (7572) States connected to redis: 127.0.0.1:9000
hm-rega.0 | 2019-12-10 20:03:48.535 | debug | (7572) statesDB connected
hm-rega.0 | 2019-12-10 20:03:48.534 | debug | (7572) States create PubSub Client
hm-rega.0 | 2019-12-10 20:03:48.531 | debug | (7572) Objects connected to redis: 127.0.0.1:9013
hm-rega.0 | 2019-12-10 20:03:48.530 | debug | (7572) Redis States: Use Redis connection: 127.0.0.1:9000
hm-rega.0 | 2019-12-10 20:03:48.529 | debug | (7572) objectDB connected
hm-rega.0 | 2019-12-10 20:03:48.523 | debug | (7572) Objects client initialize lua scripts
hm-rega.0 | 2019-12-10 20:03:48.522 | debug | (7572) Objects create PubSub Client
hm-rega.0 | 2019-12-10 20:03:48.518 | debug | (7572) Objects client ready ... initialize now
hm-rega.0 | 2019-12-10 20:03:48.502 | debug | (7572) Redis Objects: Use Redis connection: 127.0.0.1:9013
host.Medion(Test) | 2019-12-10 20:03:47.656 | info | instance system.adapter.hm-rega.0 started with pid 7572
host.Medion(Test) | 2019-12-10 20:03:47.643 | info | "system.adapter.hm-rega.0" enabled
host.Medion(Test) | 2019-12-10 20:03:33.911 | info | iobroker exit 0
host.Medion(Test) | 2019-12-10 20:03:32.882 | info | iobroker Adapter "hm-rega" updated

`

**Comment by Azathoth88** [comment]
> Rega 2.4.12 geht?
Bei mir schon.
https://i.imgur.com/qWOyqfd.png

**Comment by sigi2345** [comment]
> > Rega 2.4.12 geht?
> 
> Nein:
> 
> `
> 
> hm-rega.0	2019-12-10 20:03:50.886	error	(7572) CCU 192.168.178.99 unreachable
> hm-rega.0	2019-12-10 20:03:50.886	error	(7572) post request error: connect ECONNREFUSED 192.168.178.99:8181
> hm-rega.0	2019-12-10 20:03:48.830	debug	(7572) --> Write(system.Date("%F %X").ToTime().ToInteger());
> hm-rega.0	2019-12-10 20:03:48.828	info	(7572) ReGaHSS 192.168.178.99 up
> hm-rega.0	2019-12-10 20:03:48.678	info	(7572) subscribe hm-rpc.0.BidCoS-RF.50.PRESS_SHORT
> hm-rega.0	2019-12-10 20:03:48.662	info	(7572) starting. Version 2.4.12 in C:/Program Files/iobroker/Test/node_modules/iobroker.hm-rega, node: v10.16.3
> hm-rega.0	2019-12-10 20:03:48.542	debug	(7572) States connected to redis: 127.0.0.1:9000
> hm-rega.0	2019-12-10 20:03:48.535	debug	(7572) statesDB connected
> hm-rega.0	2019-12-10 20:03:48.534	debug	(7572) States create PubSub Client
> hm-rega.0	2019-12-10 20:03:48.531	debug	(7572) Objects connected to redis: 127.0.0.1:9013
> hm-rega.0	2019-12-10 20:03:48.530	debug	(7572) Redis States: Use Redis connection: 127.0.0.1:9000
> hm-rega.0	2019-12-10 20:03:48.529	debug	(7572) objectDB connected
> hm-rega.0	2019-12-10 20:03:48.523	debug	(7572) Objects client initialize lua scripts
> hm-rega.0	2019-12-10 20:03:48.522	debug	(7572) Objects create PubSub Client
> hm-rega.0	2019-12-10 20:03:48.518	debug	(7572) Objects client ready ... initialize now
> hm-rega.0	2019-12-10 20:03:48.502	debug	(7572) Redis Objects: Use Redis connection: 127.0.0.1:9013
> host.Medion(Test)	2019-12-10 20:03:47.656	info	instance system.adapter.hm-rega.0 started with pid 7572
> host.Medion(Test)	2019-12-10 20:03:47.643	info	"system.adapter.hm-rega.0" enabled
> host.Medion(Test)	2019-12-10 20:03:33.911	info	iobroker exit 0
> host.Medion(Test)	2019-12-10 20:03:32.882	info	iobroker Adapter "hm-rega" updated
> `

EDIT:

Jetzt ist er Grün:
`

  |   |   |  
-- | -- | -- | --
hm-rega.0 | 2019-12-10 20:06:26.530 | debug | (7572) system.adapter.admin.0: logging true
hm-rega.0 | 2019-12-10 20:06:09.074 | debug | (7572) system.adapter.admin.0: logging false
hm-rega.0 | 2019-12-10 20:05:50.137 | debug | (7572) system.adapter.admin.0: logging true
hm-rega.0 | 2019-12-10 20:05:45.798 | debug | (7572) system.adapter.admin.0: logging false
hm-rega.0 | 2019-12-10 20:04:21.116 | debug | (7572) Script ignored, because still pending.
hm-rega.0 | 2019-12-10 20:04:21.115 | info | (7572) ReGaHSS 192.168.178.99 up

`

**Comment by foxriver76** [comment]
Kann es aktuell leider nicht nachvollziehen. 

Note: https://github.com/iobroker/iobroker.hm-rega/compare/80a6593..ffbd33d

**Comment by foxriver76** [comment]
Mit meiner Raspberrymatic eben nochmal beides probiert mit 2.5.0 -> sowohl ohne SSL als auch mit funktioniert der Verbindungsaufbau.

**Comment by foxriver76** [comment]
Im anderen Ticket https://github.com/ioBroker/ioBroker.hm-rega/issues/82 hat wohl auch ein Downgrade der CCU Version geholfen. 
Kann auf Adapterseite absolut keine Änderung erkennen, die das verursacht, allerdings strange dass es bei euch dann mit 2.4.12 problemlos läuft.

**Comment by sigi2345** [comment]
> Im anderen Ticket #82 hat wohl auch ein Downgrade der CCU Version geholfen.
> Kann auf Adapterseite absolut keine Änderung erkennen, die das verursacht, allerdings strange dass es bei euch dann mit 2.4.12 problemlos läuft.

Bericht 1:

Zurück auf die 2.4.12
CCU2 Firmware auf 2.47.20
Rega wird gefunden und Grün
RPC Gelb und die CCU2 reagiert nicht oder nur sehr träge und keine Werte in den Objekten
Adapter gestoppt, CCU2 geht wieder normal
Adapter wieder gestartet
Rega Grün, RPC Gelb keine Werte

--------------------------------------------------------------------------------------------------------
Bericht 2:

Also mal die **WINDOWS** Firewall deaktiviert!!!
Alles läuft jetzt einwandfrei, Werte kommen in den Objekten an.
Port 2001,2010,8107 in der Windows Firewall freigegeben
Firewall wieder aktiviert
Alles OK!

Fazit:

Es war die WINDOWS Firewall

Ich werde mal auf die Neue Firmware und auf die Neue Version von Dir gehen und testen. 
Bericht folgt.

Sigi

**Comment by sigi2345** [comment]
Zur INFO:

Changelog
2.49.18
[HMCCU-469] Probleme beim Verbindungsaufbau von Drittanbieter-Apps zur CCU2 behoben.

**Comment by foxriver76** [comment]
Danke Sigi. Kann somit geschlossen werden?

**Comment by sigi2345** [comment]
> Danke Sigi. Kann somit geschlossen werden?

Laut Forum geht es, mache gerade das Update. Melde mich gleich.

**Comment by sigi2345** [comment]
> > Danke Sigi. Kann somit geschlossen werden?

Ja, kann geschlossen werden.
Mit neuer Firmware geht es einwandfrei.

Sigi

**Comment by Azathoth88** [comment]
Kann ich ebenfalls bestätigen. Mit der neuen CCU-Firmware funktioniert es.

**Comment by foxriver76** [comment]
Danke für die Rückmeldungen.

**Comment by Mic-M** [comment]
Bei mir geht es nicht: Update auf 2.49.18 Firmware, alles geht weiterhin unter 2.4.12. Dann Adapter von 2.4.12  auf 2.5.0 gehoben und wieder die Fehler wie in Issue #81
