### ISSUE TITLE
Keine Synchronisation mehr - CCU2 2.49.17 - hm-rega 2.4.12

### ISSUE THREAD

**Issue by eifeler-thd** [ioBroker/ioBroker.hm-rega#82]
Hallo,
nachdem ich festgestellt habe, dass keine Änderungen mehr von CCU2 Variablen von hm-rega registriert wurden, habe ich den Adapter deinstalliert und erneut installiert.
Das Resultat ist, dass keine CCU2 Variablen und Programme unter Objekte im io-Broker mehr aufgelistet werden. Ein Upgrade auf hm-rega 2.5.0 verhalf nicht zur Problemlösung. Hier scheint mir ein weiteres Problem zu existieren, weil der Adapter nur noch gelb anzeigt.
Gruß, Thomas 

**Screenshots & Logfiles**
hm-rega.0 | 2019-12-11 07:48:27.460 | info | (5583) ReGaHSS 192.168.178.33 up
-- | -- | -- | --
hm-rega.0 | 2019-12-11 07:47:57.322 | error | (5583) CCU 192.168.178.33 unreachable
hm-rega.0 | 2019-12-11 07:47:57.320 | error | (5583) post request error: connect ECONNREFUSED 192.168.178.33:8181
hm-rega.0 | 2019-12-11 07:47:57.233 | info | (5583) ReGaHSS 192.168.178.33 up
hm-rega.0 | 2019-12-11 07:47:56.765 | info | (5583) subscribe hm-rpc.0.BidCoS-RF.50.PRESS_SHORT
hm-rega.0 | 2019-12-11 07:47:56.691 | info | (5583) starting. Version 2.4.12 in /opt/iobroker/node_modules/iobroker.hm-rega, node: v10.17.0
host.raspberrypi | 2019-12-11 07:47:53.157 | info | instance system.adapter.hm-rega.0 started with pid 5583
host.raspberrypi | 2019-12-11 07:47:53.084 | info | "system.adapter.hm-rega.0" enabled

**Versions:**
 - hm-rpc version: 1.10.3
 - hm-rega version: 2.4.12
 - JS-Controller version: 2.1.1
 - Node version: 10.17.0
 - Operating system: <os-name>
 - CCU model: CCU2
 - CCU firmware: 2.49.17

**Comment by eifeler-thd** [comment]
Nach einem Downgrade der CCU2 Firmeware auf Version 2.47.20 funktioniert die Kommunikation zwischen hm-rega und der CCU wieder. 
So ein Bug lag in der Vergangenheit schon einmal bei eq3 vor.

**Comment by foxriver76** [comment]
Hm interessant dass ein Downgrade der CCU auch hilft, im anderen Ticket funktioniert wohl auch die Konstellation Rega 2.4.12 -- CCU 2.47.20, wobei ich absolut nicht erkennen kann was sich auf Adapter-Seite diesbezüglich geändert hat. Maybe coincidence :man_shrugging:

**Comment by foxriver76** [comment]
Duplicate of https://github.com/ioBroker/ioBroker.hm-rega/issues/80

**Comment by BrianLukas** [comment]
Hallo, ich hab genau das gleiche Problem...

**Comment by foxriver76** [comment]
In den Issues sind jeweils die Lösungen für die beschriebenen Probleme. Falls es um etwas anderes geht bitte im Forum das Problem beschreiben.
