### ISSUE TITLE
Missing Duty Cycle when using debmatic

### ISSUE THREAD

**Issue by braindead1** [ioBroker/ioBroker.hm-rega#84]
**Describe the bug**
I'm running debmatic in a Proxmox VM. Instead of showing the serial number of the rf module the adapter shows "undefined" in the objects list. Besides that, the Duty Cycle is not available in the objects list. See screenshot below.

**Expected behavior**
Show the serial number of the rf module and the Duty Cycle in the objects list.

**Screenshots & Logfiles**
![image](https://user-images.githubusercontent.com/2136249/71555041-684a1c80-2a27-11ea-8ac7-a8f15b21a467.png)

**Versions:**
 - hm-rpc version: 1.12.2
 - hm-rega version: 2.5.1
 - JS-Controller version: 4,3,4
 - Node version: 10.16.2
 - Operating system: debian 10
 - CCU model: debmatic
 - CCU firmware: 3.47.22.38

**Additional context**
I'm running the following script in a program in the WebUI of debmatic to write the Duty Cycle into a system variable regularly. The tcl part is different than the tcl script the adapter uses.

dom.GetObject ("CUxD.CUX2801001:1.CMD_SETS").State("echo 'load tclrpc.so; puts [xmlrpc http://127.0.0.1:2001/ listBidcosInterfaces ]'|/bin/tclsh | awk '// { printf $10 }'");
dom.GetObject ("CUxD.CUX2801001:1.CMD_QUERY_RET").State(1);
string s_reply = dom.GetObject("CUxD.CUX2801001:1.CMD_RETS").State();

dom.GetObject ("CCU.DutyCycle").State (s_reply.ToFloat());

**Comment by foxriver76** [comment]
Please run files https://github.com/ioBroker/ioBroker.hm-rega/blob/master/regascripts/dutycycle.fn and https://github.com/ioBroker/ioBroker.hm-rega/blob/master/regascripts/system.fn
and post results here.

**Comment by braindead1** [comment]
I ran both files in the WebUI of debmatic (Skript testen).

dutycycle.fn has no output.

system.fn has the following output:

{
"ccuVersion": "3.47.22.38",
"regaVersion": "2.1.369",
"buildLabel": "R1.00.0388.0208",
"countDevices": 89,
"countChannels": 528,
"countDatapoints": 3576,
"countSystemVars": 24,
"countPrograms": 15
}

**Comment by foxriver76** [comment]
K, that’s the problem I will think about what can cause this issue and come back to you.

**Comment by foxriver76** [comment]
Best first step would be to replace stdout in the last line of ditycycle.fn with stderr.

**Comment by braindead1** [comment]
This is the output of dutycycle.fn if I replace stdout with stderr:

couldn't load file "tclrpc.so": tclrpc.so: wrong ELF class: ELFCLASS32

**Comment by foxriver76** [comment]
Okay I see the problem you only have `/bin/tclsh` while normally `tclsh` should work. I am not sure if this is a Debmatic issue but I will look into it at home.

**Comment by braindead1** [comment]
Thanks for taking care. I contacted @alexreinert the maintainer of debmatic. Maybe he can support on debmatic side.

**Comment by foxriver76** [comment]
I think I can use `/bin/tclsh` should be the correct path of the tclsh alias on every CCU type.

**Comment by foxriver76** [comment]
Please test with v2.5.2

**Comment by braindead1** [comment]
Thanks. Now it's working again as expected!
