### ISSUE TITLE
ProgramExecute - Keine Reaktion

### ISSUE THREAD

**Issue by sissiwup** [ioBroker/ioBroker.hm-rega#85]
Adapter 2.5.2
Hallo,

ich starte normalerweise Programme über den Adapter indem ich den Wert ProgramExecute auf 1 setze. Das geht seit der neuen Adapterversion nicht mehr.

**Comment by foxriver76** [comment]
Mit welcher Version ging es zuletzt? 2.5.1?

**Comment by foxriver76** [comment]
Bei mir klappt es mit 2.5.2. Allerdings wundert es mich, dass du eine 1 setzt, der State sollte ein Boolean sein. Wird dem Code zufolge jedoch auch mit 1 funktionieren. Bitte Debug Log von einer Ausführung posten. An dem betreffenden Code wurde allerdings nix geändert in den letzten Versionen.
