### ISSUE TITLE
Datapoint Update available

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.hm-rega#88]
Hello dear Dev! Thanks for your awesome work!
I just looked at my CCU Debmatic and noticed an available Update for my CCU. I’m wondering that this state is not visible in ioBroker. Same for Firmwareupgrades for devices. 

Would nice if it will find its way into ioBroker. 

THX Flexer

**Comment by foxriver76** [comment]
CCU updates can be noticed by this script https://forum.iobroker.net/topic/21170/script-zur-überprüfung-ob-eine-neue-firmware-für-die-ccu-verfügbar-ist

However it’s not part of the Rega API neither of xml-rpc API. Furthermore, it’s not officially documented and probably eq3 will block requests if traffic will get suspiciously high. For new devices I also don’t know a way to get these information with one of the two APIs. If you have more information on this topic let me know. 

Only thing I am currently aware of, is that xml-rpc sends firmwareUpdateStatus change events. Unfortunately I don’t think we can poll them.

**Comment by foxriver76** [comment]
According to docs it would work with xml-rpc polling of each devices `deviceDescription` which would produce a lot of overhead.

**Comment by foxriver76** [comment]
I've added an example to hm-rpc, which shows how to get information about devices firmware. 
See https://github.com/ioBroker/ioBroker.hm-rpc#custom-commands

As mentioned before this polling will lead to enormous overhead for updates which are (from my experience) very rare. Thus, I will try to get some information out of the event which is fired by XML-RPC, as mentioned in https://github.com/ioBroker/ioBroker.hm-rpc/issues/226

Unfortunately I didn't find any information of getting a devices FW status via Homematic script api.
