### ISSUE TITLE
Connection problems with v2.5.3 and 2.5.4

### ISSUE THREAD

**Issue by twonky4** [ioBroker/ioBroker.hm-rega#91]
**Describe the bug**
The hm-rega.0 instance status turn yellow and the log says:
```
hm-rega.0 | 2020-02-10 23:31:34.229 | error | (2032) CCU 123.45.67.89 unreachable
-- | -- | -- | --
hm-rega.0 | 2020-02-10 23:31:34.228 | error | (2032) post request error: connect ECONNREFUSED 123.45.67.89:8181
```
after the update from v2.5.2 to v2.5.4. I have the same problem with v2.5.3.

**To Reproduce**
1. Update from version 2.5.2 to 2.5.4
2. Look into the log

**Expected behavior**
I didn't changed anything else.
With version 2.5.2 I got also the error message but only one time at adapter startup and after 30s the connection turn into green. With 2.5.4 it stays yellow and I got the error every 30s.

**Screenshots & Logfiles**
[iobroker.2020-02-10.log](https://github.com/ioBroker/ioBroker.hm-rega/files/4183424/iobroker.2020-02-10.log)

**Versions:**
 - hm-rpc version: 1.12.6
 - hm-rega version: 2.5.4
 - JS-Controller version: 2.2.4
 - Node version: 10.15.3
 - Operating system: raspian
 - CCU model: raspberrymatic
 - CCU firmware: 3.47.22.20191130

**Additional context**
I have a multihost system. On one slave runs 3 instances of hm-rpc and hm-rega adapter.

**Comment by foxriver76** [comment]
You get it only once because there was a big which prevented Rega from trying again so the issue has to be somewhere else. Eg CCU Firewall.

**Comment by foxriver76** [comment]
See https://github.com/ioBroker/ioBroker.hm-rega/issues/87

**Comment by twonky4** [comment]
Ah, okay. Then I don't understand the written error. Everything from the adapter works well. The ports 8181 is not opend at my CCUs.

**Comment by foxriver76** [comment]
Port nicht offen oder offen? Rega versucht auf 8181 zu verbinden, entsprechend sollte dieser verfügbar gemacht werden. Alternativ 48181 als https Port.

**Comment by twonky4** [comment]
Weder Port 8181 noch 48181 sind an meinen CCUs offen. Wofür werden die gebraucht?

**Comment by twonky4** [comment]
Muss ich denn dafür separat an der CCU was aktivieren? Weil der hm-rpc adapter funktioniert ohne Probleme.

**Comment by foxriver76** [comment]
Womöglich muss man die 8181 separat freigeben - kann ich dir nicht sagen und kann sich je nach FW, Emulation theoretisch unterscheiden. Für die Logikschnittstelle (REGA) die nach außen hin unter 8181 erreichbar ist würde die Freigabe benötigt werden. Vermutlich sind die Ports von XML-RPC automatisch offen. Gibt ja auch noch extra Dropdowns für die Schnittstellen.

**Comment by twonky4** [comment]
Stimmt, die Firewalleinstellungen der CCU passten nicht.

Ich habe es von
![image](https://user-images.githubusercontent.com/3495103/74233289-a98e4700-4cca-11ea-8d8e-581151ffc77d.png)

nach

![image](https://user-images.githubusercontent.com/3495103/74233490-0d187480-4ccb-11ea-9e04-c9a977d7e3e6.png)

geändert und es läuft.

Wäre vielleicht auch was für die Doku? Da steht noch nichts zu den Firewall regeln.
