### ISSUE TITLE
iobroker needs to be rebooted after update

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.hm-rega#99]
Hello
I´m using an Intel NUC with proxmox and iobroker with Debian 10. Node.js v10.20.0, NPM 6.14.4.

Over the last weeks there have been a few updates of the hm-rega Adapter. After the last two updates I have some errors in the log like:
`2020-04-13 00:19:19.810  - [31merror[39m: hm-rega.0 (22791) runScriptFile Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.hm-rega/lib/../regascripts/polling.fn'
2020-04-13 00:19:19.810  - [31merror[39m: hm-rega.0 (22791) runScriptFile Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.hm-rega/lib/../regascripts/programs.fn'
2020-04-13 00:19:49.810  - [31merror[39m: hm-rega.0 (22791) runScriptFile Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.hm-rega/lib/../regascripts/polling.fn'
2020-04-13 00:19:49.811  - [31merror[39m: hm-rega.0 (22791) runScriptFile Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.hm-rega/lib/../regascripts/programs.fn'`

I can only get rid of these errors when I reboot iobroker. This behavior is since the last two updates.

Can someone imagine where this does come from?

Thank you
Jo

**Comment by foxriver76** [comment]
Reboot ioBroker or reboot the host? Seems like permission problems ..

**Comment by XxJooO** [comment]
Hallo foxriver,

nein, nur den ioBroker, der Host läuft weiter...

**Comment by XxJooO** [comment]
Und wie beschrieben: Der Fehler im Log tauchte erst beim Vorletzten Update auf. Auch da kam ein solcher Fehler und ich musste den Broker neu starten. Jetzt gestern wieder. Und, falls die Frage kommen sollte, der Installationsfixer ist schon mehrfach gelaufen - allerdings nicht mehr nach diesen beiden Updates von hm-rega.

**Comment by foxriver76** [comment]
Gestern nach update nehme ich an?

**Comment by XxJooO** [comment]
Korrekt

**Comment by foxriver76** [comment]
Also während update kann sein dass Dateien überschrieben, bei schlechtem Timing nicht gelesen werden können, da von FS gelesen wird. Allerdings wird ja nach Update automatisch der Adapter neu gestartet. Letztendlich sollte man das sowieso mal ummünzen und die files in den iob Storage schreiben.. dann sollte sowas auch nicht mehr vorkommen. 

Unabhängig davon, wie hast du das Update vollzogen?

**Comment by XxJooO** [comment]
Ich hatte unter Info-Aktualisierungen das Update angestossen und im Hintergrund ausführen lassen, da auch der zigbee Adapter ein Update wollte. 
Beim Update davor kann ich mich allerdings nicht mehr erinnern.

**Comment by foxriver76** [comment]
Info = Info Adapter?

**Comment by XxJooO** [comment]
Nein, hier

![image](https://user-images.githubusercontent.com/47712364/79117644-f60a0780-7d8b-11ea-95eb-517b43692035.png)

**Comment by foxriver76** [comment]
Ja, der Info Tab ist vom Info Adapter.

Es werden nun ab 2.6.3 die regascripts bei Adapterstart mit dem iob file storage synchronisiert und dann von dort gelesen, somit wird nicht mehr im `node_modules` Verzeichnis gelesen, welches während eines Updates angefasst wird. Auch werden die regascripts somit bei objects-redis Konfigurationen im redis abgelegt und von dort gelesen.

**Comment by XxJooO** [comment]
Leider kann ich Dir überhaupt nicht folgen... Sollte ich lieber über den Reiter Adapter schauen, welche Updates es gibt und darüber installieren?
Bzw. sprichst du von einer V. 2.6.3, die wird mir aktuell nicht angezeigt...
Grüße

**Comment by foxriver76** [comment]
Ist ne 2.6.4 geworden. Ich weiß nicht was der Info Adapter macht, im besten Fall setzt er das gleiche Kommando ab wie der Admin auch zum Upgrade. Bis neue Version angezeigt, kann es etwas dauern. Bei dem Upgrade kann es noch einmalig zu Problemen kommen.
